#include <cca/persistence/persistence.hpp>
#include "../representation/representation_test_access.hpp"
#include <unordered_map>
#include <utility>
namespace cca::persistence {
namespace {
using namespace cca::representation;
RepresentationValue copy_value(const RepresentationValue& value) {
    switch (value.kind()) {
    case ValueKind::Boolean: return RepresentationValue(value.asBoolean());
    case ValueKind::Integer: return RepresentationValue(value.asInteger());
    case ValueKind::FloatingPoint: return RepresentationValue(value.asFloatingPoint());
    case ValueKind::String: return RepresentationValue(std::string(value.asString()));
    case ValueKind::Enumeration: return RepresentationValue(EnumerationValue(std::string(value.asString())));
    case ValueKind::Identifier: return RepresentationValue(RepresentationId(value.asIdentifier().toString()));
    case ValueKind::Collection: { std::vector<RepresentationValue> values; for (const auto& item : value.asCollection()) values.push_back(copy_value(item)); return RepresentationValue(std::move(values)); }
    }
    return RepresentationValue(std::string{});
}
std::unique_ptr<RepresentationDocument> copy_document(const RepresentationDocument& source) {
    auto result = std::make_unique<RepresentationDocument>(RepresentationMetadata(std::string(source.metadata().author()), std::string(source.metadata().version()), std::string(source.metadata().provenance())));
    std::unordered_map<std::string, RepresentationEntity*> entities;
    for (const auto& reference : source.entities()) { const auto& entity = reference.get(); auto& copy = result->createEntity(RepresentationType(std::string(entity.type().name()))); RepresentationInternalAccess::replaceId(copy, RepresentationId(entity.id().toString())); entities.emplace(entity.id().toString(), &copy); for (const auto& property_reference : entity.properties()) { const auto& property = property_reference.get(); auto& copied_property = copy.addProperty(std::string(property.name()), RepresentationType(std::string(property.type().name())), copy_value(property.value())); RepresentationInternalAccess::replaceId(copied_property, RepresentationId(property.id().toString())); } }
    for (const auto& reference : source.relationships()) { const auto& relationship = reference.get(); auto& copy = result->createRelationship(*entities.at(relationship.source().id().toString()), *entities.at(relationship.target().id().toString()), RepresentationType(std::string(relationship.type().name()))); RepresentationInternalAccess::replaceId(copy, RepresentationId(relationship.id().toString())); for (const auto& property_reference : relationship.properties()) { const auto& property = property_reference.get(); auto& copied_property = copy.addProperty(std::string(property.name()), RepresentationType(std::string(property.type().name())), copy_value(property.value())); RepresentationInternalAccess::replaceId(copied_property, RepresentationId(property.id().toString())); } }
    RepresentationInternalAccess::setIdentifierState(*result, RepresentationInternalAccess::nextIdentifierOrdinal(source), RepresentationInternalAccess::identifiersExhausted(source));
    RepresentationInternalAccess::setLifecycleState(*result, RepresentationInternalAccess::lifecycleState(source));
    return result;
}
}
PersistenceMetadata::PersistenceMetadata() noexcept=default; PersistenceMetadata::PersistenceMetadata(std::string w,std::string d):workspace_name_(std::move(w)),description_(std::move(d)){} PersistenceMetadata::~PersistenceMetadata()=default; PersistenceMetadata::PersistenceMetadata(const PersistenceMetadata&)=default; PersistenceMetadata& PersistenceMetadata::operator=(const PersistenceMetadata&)=default; PersistenceMetadata::PersistenceMetadata(PersistenceMetadata&&) noexcept=default; PersistenceMetadata& PersistenceMetadata::operator=(PersistenceMetadata&&) noexcept=default; const std::string& PersistenceMetadata::workspaceName() const noexcept{return workspace_name_;} const std::string& PersistenceMetadata::description() const noexcept{return description_;}
ExecutionContextSnapshot::ExecutionContextSnapshot(std::size_t i,cca::process::ExecutionState s,std::vector<cca::representation::RepresentationId> t):index_(i),state_(s),trace_(std::move(t)){} ExecutionContextSnapshot::~ExecutionContextSnapshot()=default; ExecutionContextSnapshot::ExecutionContextSnapshot(const ExecutionContextSnapshot&)=default; ExecutionContextSnapshot& ExecutionContextSnapshot::operator=(const ExecutionContextSnapshot&)=default; ExecutionContextSnapshot::ExecutionContextSnapshot(ExecutionContextSnapshot&&) noexcept=default; ExecutionContextSnapshot& ExecutionContextSnapshot::operator=(ExecutionContextSnapshot&&) noexcept=default; std::size_t ExecutionContextSnapshot::processDefinitionIndex() const noexcept{return index_;} cca::process::ExecutionState ExecutionContextSnapshot::state() const noexcept{return state_;} const std::vector<cca::representation::RepresentationId>& ExecutionContextSnapshot::trace() const noexcept{return trace_;}
class PersistencePackage::Impl { public: std::unique_ptr<cca::representation::RepresentationDocument> workspace; PersistenceMetadata metadata; std::vector<std::string> policies; std::vector<cca::process::ProcessDefinition> defs; std::vector<ExecutionContextSnapshot> contexts; PersistenceFormat format{PersistenceFormat::Canonical}; };
PersistencePackage::PersistencePackage(const cca::representation::RepresentationDocument& w,const PersistenceMetadata& m,std::vector<std::string> p,std::vector<cca::process::ProcessDefinition> d,std::vector<ExecutionContextSnapshot> c,PersistenceFormat f):impl_(std::make_unique<Impl>()){impl_->workspace=copy_document(w); impl_->metadata=m; impl_->policies=std::move(p); impl_->defs=std::move(d); impl_->contexts=std::move(c); impl_->format=f;} PersistencePackage::~PersistencePackage()=default; PersistencePackage::PersistencePackage(const PersistencePackage& o):impl_(std::make_unique<Impl>()){impl_->workspace=copy_document(*o.impl_->workspace); impl_->metadata=o.impl_->metadata; impl_->policies=o.impl_->policies; impl_->defs=o.impl_->defs; impl_->contexts=o.impl_->contexts; impl_->format=o.impl_->format;} PersistencePackage& PersistencePackage::operator=(const PersistencePackage& o){if(this!=&o){auto copy=std::make_unique<Impl>(); copy->workspace=copy_document(*o.impl_->workspace); copy->metadata=o.impl_->metadata; copy->policies=o.impl_->policies; copy->defs=o.impl_->defs; copy->contexts=o.impl_->contexts; copy->format=o.impl_->format; impl_=std::move(copy);} return *this;} PersistencePackage::PersistencePackage(PersistencePackage&&) noexcept=default; PersistencePackage& PersistencePackage::operator=(PersistencePackage&&) noexcept=default; const cca::representation::RepresentationDocument& PersistencePackage::workspace() const noexcept{return *impl_->workspace;} const PersistenceMetadata& PersistencePackage::metadata() const noexcept{return impl_->metadata;} const std::vector<std::string>& PersistencePackage::policies() const noexcept{return impl_->policies;} const std::vector<cca::process::ProcessDefinition>& PersistencePackage::processDefinitions() const noexcept{return impl_->defs;} PersistenceFormat PersistencePackage::format() const noexcept{return impl_->format;} const std::vector<ExecutionContextSnapshot>& PersistencePackage::executionContexts() const noexcept{return impl_->contexts;}
class PersistenceResult::Impl { public: bool ok=false; std::string code=""; std::string message=""; std::unique_ptr<PersistencePackage> package; }; PersistenceResult::PersistenceResult():impl_(std::make_unique<Impl>()){} PersistenceResult::PersistenceResult(PersistenceResult&&) noexcept=default; PersistenceResult& PersistenceResult::operator=(PersistenceResult&&) noexcept=default; PersistenceResult::~PersistenceResult()=default; bool PersistenceResult::succeeded() const noexcept{return impl_->ok;} const std::string& PersistenceResult::code() const noexcept{return impl_->code;} const std::string& PersistenceResult::message() const noexcept{return impl_->message;} const PersistencePackage* PersistenceResult::package() const noexcept{return impl_->package.get();}
PersistenceResult PersistenceEngine::save(const cca::representation::RepresentationDocument& w,const PersistenceMetadata& m,const std::vector<std::string>& p,const std::vector<cca::process::ProcessDefinition>& d,const std::vector<ExecutionContextSnapshot>& c,PersistenceFormat f) const { PersistenceResult r; const auto validation=cca::representation::ValidationService{}.validate(w); if(!validation.valid){r.impl_->code="INVALID_REPRESENTATION"; r.impl_->message="Workspace Representation is invalid"; return r;} r.impl_->package=std::make_unique<PersistencePackage>(w,m,std::vector<std::string>(p),std::vector<cca::process::ProcessDefinition>(d),std::vector<ExecutionContextSnapshot>(c),f); if(const auto checked=validate(*r.impl_->package); !checked.succeeded()){r.impl_->package.reset(); r.impl_->code=checked.code(); r.impl_->message=checked.message(); return r;} r.impl_->ok=true; r.impl_->code="OK"; r.impl_->message="saved"; return r; }
PersistenceResult PersistenceEngine::validate(const PersistencePackage& p) const { PersistenceResult r; if(p.format()!=PersistenceFormat::Canonical){r.impl_->code="INVALID_FORMAT"; r.impl_->message="unsupported format"; return r;} for(const auto& context:p.executionContexts()){if(context.processDefinitionIndex()>=p.processDefinitions().size()){r.impl_->code="INVALID_CONTEXT"; r.impl_->message="execution context references an absent process definition"; return r;}} r.impl_->ok=true; r.impl_->code="OK"; r.impl_->message="valid"; return r; }
PersistenceResult PersistenceEngine::load(const PersistencePackage& p) const { auto r=validate(p); if(r.succeeded()){r.impl_->package=std::make_unique<PersistencePackage>(p); r.impl_->message="loaded";} return r; }
}
