from pathlib import Path
import json,statistics,xml.etree.ElementTree as E,hashlib
R=Path.cwd();O=R/'.cache/mo1305-r6-diagnostic';base=R/'repositories/cca-conformance/evidence/mo1305-phase1-r6/resource'
f=json.loads((base/'maximum-permitted-headers-failed-sample.json').read_bytes());c=json.loads((base/'maximum-permitted-headers.json').read_bytes());raw=json.loads((R/c['runs'][-1]['raw']['path']).read_bytes());catalog=json.loads((R/'repositories/cca-conformance/fixtures/mo1305-phase1/measurement/catalog.json').read_bytes())['records'];expected=next(x for x in catalog if x['id']=='projection-operation-timeout')['expected'];assert expected['statusCode']==f['http']['status']==504 and expected['responseSha256']==f['http']['responseSha256'];assert (f['case'],f['phase'],f['index'])==('maximum-permitted-headers','warm',2)
t=f['observations'][0]['operationTiming'];metrics=f['observations'][0]['record'];assert metrics['operationUs']==60443611 and (int(t['endNs'])-int(t['startNs'])+999)//1000==60443611
roundtrip=(int(f['responseEnd']['ns'])-int(f['requestStart']['ns']))//1000;assert roundtrip==60496188
r103=next(r for r in raw['records'] if r['sequence']==103);assert int(r103['completedNs'])-int(r103['captureNs'])==56254381600
comparisons=[]
for s in c['records']:
 run=next(r for r in c['runs'] if r['sessionId']==s['provenance']['sessionId']);native=json.loads((R/run['raw']['path']).read_bytes())['records'];w=s['nativeWindow'];rows=native[w['baseline']['sequence']-1:w['cleanup']['sequence']]
 comparisons.append({'phase':s['phase'],'index':s['index'],'operationUs':s['metrics']['operationUs'],'roundTripUs':s['roundTripUs'],'sdkUs':s['metrics']['sdkUs'],'importUs':s['metrics']['importUs'],'integrityUs':s['metrics']['integrityUs'],'reapUs':s['metrics']['reapUs'],'oldBytes':s['metrics']['oldBytes'],'youngBytes':s['metrics']['youngBytes'],'externalBytes':s['metrics']['externalBytes'],'rssPeak':s['native']['peak']['PeakWorkingSetSize'],'maxCaptureMs':max((int(r['completedNs'])-int(r['captureNs']))/1e6 for r in rows)})
repro=json.loads((O/'focused-reproduction.json').read_bytes());assert len(repro['records'])==12
summaries=[]
for mode in ['with-collector','without-collector']:
 rows=[x for x in repro['records'] if x['mode']==mode];metricsRows=[x['observations'][0]['record'] for x in rows]
 summaries.append({'mode':mode,'count':len(rows),'cold':sum(x['phase']=='cold' for x in rows),'warm':sum(x['phase']=='warm' for x in rows),'allHttp200Exact':all(x['httpStatus']==200 and x['bodyExact'] for x in rows),'operationUs':{'min':min(x['operationUs'] for x in metricsRows),'median':statistics.median(x['operationUs'] for x in metricsRows),'max':max(x['operationUs'] for x in metricsRows)},'roundTripUs':{'min':min(x['roundTripUs'] for x in rows),'median':statistics.median(x['roundTripUs'] for x in rows),'max':max(x['roundTripUs'] for x in rows)}})
traceRows=[]
for run in repro['runs']:
 trace=json.loads((R/run['trace']).read_bytes());ev=trace['events'];starts=[(i,e) for i,e in enumerate(ev) if e['name']=='owner.state' and e['state']=='running'];beats=[int(x['gapNs'])/1e6 for x in ev if x['name']=='parent.heartbeat']
 for ordinal,(i,e) in enumerate(starts):
  following=ev[i:starts[ordinal+1][0] if ordinal+1<len(starts) else len(ev)];get=lambda name:next(x for x in following if x['name']==name);result=next(x for x in following if x['name']=='worker.message' and x['messageType']=='result');pub=next(x for x in following if x['name']=='owner.state' and x['state']=='published')
  start=int(e['startedNs']);construct=get('worker.construct.begin');online=get('worker.online');exit=get('worker.exit');report=get('report');traceRows.append({'mode':run['mode'],'run':run['label'],'index':ordinal,'domain':trace['domain'],'operationStartNs':str(start),'deadlineNs':e['deadlineNs'],'constructToOnlineUs':(int(online['ns'])-int(construct['ns']))//1000,'startToResultReceivedUs':(int(result['ns'])-start)//1000,'resultReceivedToExitUs':(int(exit['ns'])-int(result['ns']))//1000,'exitToPublishedUs':(int(pub['ns'])-int(exit['ns']))//1000,'publishedToReportUs':(int(report['ns'])-int(pub['ns']))//1000,'workerReportedSdkUs':result['metrics']['sdkUs'],'workerReportedImportUs':result['metrics']['importUs'],'workerReportedIntegrityUs':result['metrics']['integrityUs'],'maxParentHeartbeatGapMs':max(beats),'terminationCalls':sum(x['name']=='worker.terminate.request' for x in following),'timersFired':sum(x['name']=='timer.fired' for x in following)})
power=json.loads((O/'power-events-raw.json').read_text(encoding='utf-8-sig'));powers=[]
for row in power:
 xml=E.fromstring(row['xml']);ns={'e':'http://schemas.microsoft.com/win/2004/08/events/event'};data={x.attrib['Name']:x.text for x in xml.findall('e:EventData/e:Data',ns)};powers.append({'recordId':row['RecordId'],'id':row['Id'],'utcDescriptive':row['utc'],'fields':data})
exitSleep=next(x for x in powers if x['recordId']==130893);assert exitSleep['fields']['SleepEntered']=='true' and exitSleep['fields']['SleepDurationInUs']=='55776717' and exitSleep['fields']['BootId']=='83' and exitSleep['fields']['LidOpenState']=='false'
result={'kind':'R6RootCauseDiagnosticAnalysis','classification':'C','classificationName':'HOST TRANSIENT / ENVIRONMENTAL STALL','failureOperandsValidated':True,'failureRoundTripUs':roundtrip,'failureOperationTiming':t,'operationDeadlineNs':str(int(t['startNs'])+60000000000),'publishedAfterDeadlineUs':(int(t['endNs'])-int(t['startNs'])-60000000000)//1000,'failureMetrics':metrics,'nativeCaptureSequence103':r103,'nativeCaptureDurationNs':'56254381600','r6SuccessfulComparison':comparisons,'reproductionSummaries':summaries,'diagnosticParentTraces':traceRows,'powerEvents':powers,'causalConclusion':'Modern Standby externally compromised R6. Independent OS records explicitly report sleep and durations corresponding to both collector stalls. Original per-instruction execution and exact timeout callback firing were not recorded.','unchangedR6State':'FAIL','certification':False}
(O/'analysis.json').write_text(json.dumps(result,sort_keys=True,separators=(',',':')),encoding='utf-8')
print(json.dumps({'failureTiming':t,'deadlineNs':result['operationDeadlineNs'],'publishedAfterDeadlineUs':result['publishedAfterDeadlineUs'],'comparison':comparisons,'reproduction':summaries,'traceRanges':{k:{'min':min(x[k] for x in traceRows),'max':max(x[k] for x in traceRows)} for k in ['constructToOnlineUs','resultReceivedToExitUs','exitToPublishedUs','publishedToReportUs','maxParentHeartbeatGapMs','workerReportedSdkUs']},'classification':'C'},indent=2))