import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,symlinkSync,unlinkSync,rmdirSync} from 'node:fs';import {resolve} from 'node:path';
import {stage,root,credentials,launch,wire,request,response,delay} from './installed.mjs';
const clean={SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,TEMP:process.env.TEMP,TMP:process.env.TMP},configPath=resolve(stage,'private/config.json'),original=readFileSync(configPath),config=JSON.parse(original),records=[];
const openssl='C:/Program Files/Git/usr/bin/openssl.exe',pwsh='C:/Users/melsa/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/powershell/pwsh.exe';
function command(exe,args){const run=spawnSync(exe,args,{env:clean,encoding:'utf8',windowsHide:true});assert.equal(run.status,0,run.stderr);}
async function rejected(id,value){writeFileSync(configPath,JSON.stringify(value));const child=spawn(process.execPath,[resolve(stage,'package/bin/memoryos-rest.mjs'),'--config',configPath],{env:clean,windowsHide:true,stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);try{const exit=await new Promise(r=>child.once('exit',r));assert.equal(exit,2,id);assert.equal(stdout,'');assert.equal(JSON.parse(stderr).code,'MO1305_UNAVAILABLE');records.push({id,state:'PASS',exitCode:2});}finally{writeFileSync(configPath,original);}}
const wrong=resolve(stage,'private/wrong-ip.pem');command(openssl,['req','-new','-x509','-key',config.privateKeyFile,'-out',wrong,'-days','1','-subj','/CN=MO1305 negative','-addext','subjectAltName=IP:127.0.0.2']);await rejected('SEC-TLS-wrong-ip',{...config,certificateFile:wrong});
const noSAN=resolve(stage,'private/no-san.pem');command(openssl,['req','-new','-x509','-key',config.privateKeyFile,'-out',noSAN,'-days','1','-subj','/CN=127.0.0.1']);await rejected('SEC-TLS-no-ip-san',{...config,certificateFile:noSAN});
const expired=resolve(stage,'private/expired.pem');command(openssl,['x509','-in',config.certificateFile,'-signkey',config.privateKeyFile,'-not_before','20200101000000Z','-not_after','20210101000000Z','-out',expired]);await rejected('SEC-TLS-expired',{...config,certificateFile:expired});
const mismatch=resolve(stage,'private/mismatch.pem');command(openssl,['genpkey','-algorithm','EC','-pkeyopt','ec_paramgen_curve:P-256','-out',mismatch]);await rejected('SEC-TLS-key-mismatch',{...config,privateKeyFile:mismatch});
const rsa=resolve(stage,'private/rsa.pem');command(openssl,['genpkey','-algorithm','RSA','-pkeyopt','rsa_keygen_bits:2048','-out',rsa]);await rejected('SEC-TLS-non-P256',{...config,privateKeyFile:rsa});
const chain=resolve(stage,'private/long-chain.pem');writeFileSync(chain,Buffer.concat(Array(5).fill(credentials.ca)));await rejected('SEC-TLS-chain-count',{...config,certificateFile:chain});
const oversized=resolve(stage,'private/oversized.pem');writeFileSync(oversized,Buffer.concat([credentials.ca,Buffer.alloc(16385,32)]));await rejected('SEC-TLS-cert-bytes',{...config,certificateFile:oversized});
const junction=resolve(stage,'private-junction');symlinkSync(resolve(stage,'private'),junction,'junction');try{await rejected('SEC-FS-reparse-ancestor',{...config,tokenFile:resolve(junction,'token')});}finally{rmdirSync(junction);}
const icacls='C:/Windows/System32/icacls.exe';
for(const name of ['token','key.pem','config.json']){
 const file=resolve(stage,'private',name);command(icacls,[file,'/grant','*S-1-1-0:(R)']);
 try{const run=spawnSync(pwsh,['-NoProfile','-NonInteractive','-File',resolve(import.meta.dirname,'validate-launch.ps1'),'-NodePath',process.execPath,'-ConfigPath',configPath],{env:clean,encoding:'utf8',windowsHide:true});assert.equal(run.status,2,run.stderr);assert.match(run.stdout,/MO1305_TRUSTED_LAUNCH_REFUSED:ACL/,run.stderr);records.push({id:'SEC-ACL-foreign-'+name,state:'PASS'});}
 finally{command(icacls,[file,'/remove:g','*S-1-1-0']);}
}
const manifestPath=resolve(stage,'package/distribution-manifest.json'),manifestBytes=readFileSync(manifestPath);const manifest=JSON.parse(manifestBytes);manifest.files.push({...manifest.files[0],path:manifest.files[0].path.toUpperCase()});writeFileSync(manifestPath,JSON.stringify(manifest));try{await rejected('SEC-INTEGRITY-manifest-case-collision',config);}finally{writeFileSync(manifestPath,manifestBytes);}
const state=await launch({measurement:true});const target=resolve(stage,'package/runtime/authoritative/web/js/memoryos-sdk.js'),bytes=readFileSync(target);
try{writeFileSync(target,Buffer.concat([bytes,Buffer.from(' ')]));const result=response(await wire(request('getContractIdentities')));assert.equal(result.status,503);assert.equal(result.body.error.code,'MO1305_RUNTIME_INTEGRITY');assert.equal((await state.exit).code,1);assert.equal(state.stdout,'');records.push({id:'SEC-INTEGRITY-running-mutation-no-success',state:'PASS',status:503,exitCode:1});}finally{writeFileSync(target,bytes);if(state.child.exitCode===null){state.child.stdin.end();await state.exit;}}
const rotation=await launch();const tokenPath=config.tokenFile,oldToken=readFileSync(tokenPath),replacement='1'.repeat(64);try{writeFileSync(tokenPath,replacement);assert.equal(response(await wire(request('getHealth'))).status,200);assert.equal(response(await wire(request('getHealth',null,{headers:{Authorization:'Bearer '+replacement}}))).status,401);}finally{await rotation.stop();}
const rotated=await launch();try{assert.equal(response(await wire(request('getHealth'))).status,401);assert.equal(response(await wire(request('getHealth',null,{headers:{Authorization:'Bearer '+replacement}}))).status,200);records.push({id:'SEC-AUTH-restart-only-rotation',state:'PASS'});}finally{await rotated.stop();writeFileSync(tokenPath,oldToken);}
const invalid=await launch();invalid.child.stdin.write('invalid');assert.equal((await invalid.exit).code,1);records.push({id:'LIFECYCLE-invalid-stdin',state:'PASS',exitCode:1});
writeFileSync(resolve(root,'.cache/mo1305-resource-review/startup-extra.json'),JSON.stringify({kind:'MemoryOSRESTAdditionalSecurityResults',state:'PASS',records}));console.log(JSON.stringify({state:'PASS',cases:records.length}));
