import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {canonical,checkPackage,packageFiles} from '../mo1307-phase1/package.mjs';
const root=fileURLToPath(new URL('../../../../',import.meta.url));
const rel='repositories/cca-conformance/evidence/mo1307/phase3ar2-c3tb';
const toolRel='repositories/cca-conformance/tools/mo1307-phase3ar2-c3tb';
const E=path.join(root,rel),cache=path.join(root,'.cache/phase3ar2-c3tb'),source=path.join(root,'repositories/memoryos-readiness');
const installed=path.join(cache,'install/node_modules/memoryos-readiness');
const C3TB='119e68bdcf0ffc906b4ca03a912aadcb25908346',C3T='65e24b2debdd70ecb8e52fbccbd6c101621f1917';
const integration='PROSPECTIVE_HELPER_BOUND@1.0.0',productionTree='324bf600b6cbfaa8564db27fce2d999711270cb8';
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const record=p=>{const b=fs.readFileSync(p);return {path:path.relative(root,p).replaceAll('\\','/'),byteLength:b.length,sha256:hash(b)};};
const walk=(base,prefix='')=>fs.readdirSync(path.join(base,prefix),{withFileTypes:true}).sort((a,b)=>a.name<b.name?-1:1).flatMap(e=>{const p=prefix?prefix+'/'+e.name:e.name,full=path.join(base,p),s=fs.lstatSync(full);assert.ok(!s.isSymbolicLink(),full);return s.isDirectory()?walk(base,p):[{...record(full),path:p}];});
const put=(name,bytes)=>{const p=path.join(E,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,bytes,{flag:'wx'});return record(p);};
const write=(name,obj)=>put(name,Buffer.from(JSON.stringify(obj,null,2)+'\n'));
const env={SystemRoot:'C:\\Windows',WINDIR:'C:\\Windows'};
function git(...args){const r=spawnSync('C:/Program Files/Git/cmd/git.exe',args,{cwd:root,windowsHide:true,encoding:null,maxBuffer:128*1024*1024});assert.ifError(r.error);assert.equal(r.status,0,r.stderr.toString());return r.stdout;}
assert.equal(path.resolve(root).toLowerCase(),'c:\\users\\melsa\\documents\\codex\\3ar2');
assert.equal(process.platform,'win32');assert.equal(process.arch,'x64');assert.equal(process.version,'v24.21.0');
assert.equal(hash(fs.readFileSync(process.execPath)),'sha256:ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32');
assert.equal(git('rev-parse','HEAD').toString().trim(),C3TB);
assert.equal(git('rev-parse',C3TB+'^{tree}').toString().trim(),'5e0088965d4eac4002165fe0190f275c257985ba');
assert.equal(git('rev-parse',C3TB+':repositories/memoryos-readiness').toString().trim(),productionTree);
assert.equal(git('show','-s','--format=%P',C3TB).toString().trim(),C3T);
assert.equal(git('branch','--show-current').toString().trim(),'codex/mo1307-phase3ar2-c3tb');
assert.equal(git('diff','--name-only','--','repositories/memoryos-readiness').toString(),'');
assert.equal(git('diff','--cached','--name-only').toString(),'');
const statusLines=git('status','--porcelain=v1','--untracked-files=all').toString().trim().split(/\r?\n/).filter(Boolean);
assert.ok(statusLines.every(line=>line.startsWith('?? '+toolRel+'/')||line.startsWith('?? '+rel+'/')),'Unexpected working-tree path before preparation');
assert.equal(fs.existsSync(cache),false,'Fresh explicit installation/cache must not exist');
assert.equal(fs.existsSync(E),false,'Fresh Phase 3AR2 evidence namespace must not exist');
assert.equal(fs.existsSync(path.join(root,'docs/mo1307-phase3ar2-c3tb.md')),false,'Fresh Phase 3AR2 report path must not exist');
const startedAt=new Date().toISOString(),hardStopAt=new Date(Date.now()+180*60000).toISOString();
write('pre-execution-gate.json',{result:'PASS',verifiedAt:startedAt,worktree:path.resolve(root),branch:'codex/mo1307-phase3ar2-c3tb',HEAD:C3TB,rootTree:'5e0088965d4eac4002165fe0190f275c257985ba',productionCommit:C3T,productionTree,initialGateObservedBeforeTooling:{worktree:'C:\\Users\\melsa\\Documents\\Codex\\3ar2',branch:'codex/mo1307-phase3ar2-c3tb',HEAD:C3TB,workingTree:'CLEAN'},currentTrackedDiff:'CLEAN',currentIndex:'CLEAN',currentUntrackedScope:'Only the fresh Phase 3AR2 tool/evidence namespaces created after the initial clean gate',statusLines});
write('campaign-config.json',{generation:'PHASE3AR2_C3TB_FRESH_FULL_INSTALLED_RUNTIME_20261001',startedAt,hardStopAt,engineeringGuardMinutes:180,productDeadlineAuthority:integration,candidate:C3TB,productionCommit:C3T,productionTree,H:'NOT_ESTABLISHED',nodeExecutable:process.execPath,helperSuccess:'elapsedMs < 8000',helperTimeout:'elapsedMs >= 8000',noRetry:true});
put('generation-authorization.txt',fs.readFileSync('C:/Users/melsa/.codex/attachments/880a4641-e859-48d3-b396-94575ffbf20e/Pasted text.txt'));
const production=walk(source);
assert.deepEqual(production.map(x=>x.path),[...packageFiles].sort());
for(const row of production)assert.equal(row.sha256,hash(git('show',C3TB+':repositories/memoryos-readiness/'+row.path)),row.path);
const sourceCheck=checkPackage(source);
const packageIdentity=hash(Buffer.from(canonical(production)+'\n'));
assert.equal(production.length,89);assert.equal(packageIdentity,'sha256:2869cc0745fc555d5338f35634e7738b49cb628f6693dd92c5868f36ec113729');
const candidateAuthority=JSON.parse(fs.readFileSync(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/candidate.json'),'utf8'));
const bindingVerification=JSON.parse(fs.readFileSync(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/binding-verification.json'),'utf8'));
assert.equal(bindingVerification.result,'PASS');assert.equal(bindingVerification.productionTree,productionTree);
assert.equal(candidateAuthority.package.packageIdentity,packageIdentity);assert.equal(candidateAuthority.package.packageMemberCount,89);
assert.equal(candidateAuthority.helper.sha256,'sha256:97ef5ae9ce7ab390548b04a2aefba9f922c3e1c6b9b80581c6c274f0b21f0127');
const historical=[];
const historicalPaths=git('ls-tree','-r','--name-only',C3TB).toString().trim().split(/\r?\n/).filter(p=>p.startsWith('repositories/cca-conformance/evidence/mo1307/')||p.startsWith('repositories/cca-conformance/tools/mo1307-')||p.startsWith('docs/mo1307-'));
for(const relative of historicalPaths){const full=path.join(root,relative);assert.ok(fs.existsSync(full),relative);historical.push({...record(full),absolutePath:full});}
write('historical-before.json',{result:'PRESERVATION_BASELINE',candidate:C3TB,members:historical,promotion:false,readOnly:true,source:'Tracked MO-1307 authority, tooling and evidence at exact C3TB; current fresh namespace excluded because absent at C3TB.'});
write('candidate-before.json',{candidate:C3TB,productionCommit:C3T,productionTree,integrationAuthority:integration,parent:git('show','-s','--format=%P','HEAD').toString().trim(),tree:git('rev-parse','HEAD^{tree}').toString().trim(),members:production,packageIdentity,check:sourceCheck,initialStatus:git('status','--porcelain=v1','--untracked-files=all').toString(),productionGitDiff:git('diff','--name-only',C3TB,'--','repositories/memoryos-readiness').toString(),bindingVerification:record(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/binding-verification.json'))});
fs.mkdirSync(cache,{recursive:true});
function command(id,exe,args,cwd=root,extra={}){const start=performance.now();const r=spawnSync(exe,args,{cwd,env:{...env,...extra},windowsHide:true,shell:false,encoding:null,timeout:120000,maxBuffer:16*1024*1024});write(id+'.json',{executable:exe,args,cwd,exit:r.status,error:r.error?.code??null,elapsedMs:performance.now()-start,stdout:put(id+'.stdout.data',r.stdout??Buffer.alloc(0)),stderr:put(id+'.stderr.data',r.stderr??Buffer.alloc(0))});assert.ifError(r.error);assert.equal(r.status,0,r.stderr.toString());return r.stdout;}
const ps='C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe';
const script="$os=Get-CimInstance Win32_OperatingSystem; $cs=Get-CimInstance Win32_ComputerSystem; [ordered]@{osCaption=$os.Caption;version=$os.Version;build=$os.BuildNumber;architecture=$os.OSArchitecture;manufacturer=$cs.Manufacturer;model=$cs.Model;powerShellPath=(Get-Process -Id $PID).Path;powerShellVersion=$PSVersionTable.PSVersion.ToString();policy=@(Get-ExecutionPolicy -List | ForEach-Object {[ordered]@{scope=$_.Scope.ToString();policy=$_.ExecutionPolicy.ToString()}})} | ConvertTo-Json -Depth 5 -Compress";
const system=JSON.parse(command('environment-capture',ps,['-NoLogo','-NoProfile','-NonInteractive','-Command',script]));
assert.match(system.powerShellVersion,/^5\.1\./);assert.match(system.osCaption,/Windows 11/);assert.match(system.architecture,/64/);
assert.equal(hash(fs.readFileSync(ps)),'sha256:8bb6fa8c283b4d92120b1ef249a9b311b0f804d4cabbe9981159976c8be76a5e');
const npm=path.join(path.dirname(process.execPath),'node_modules/npm/bin/npm-cli.js');
assert.equal(command('npm-version',process.execPath,[npm,'--version']).toString().trim(),'11.19.0');
assert.equal(hash(fs.readFileSync(npm)),'sha256:3ce7cba6f5128dd5f54c98b6a5036b0f850496878cc2e21044b675fe3c594e3e');
write('runtime.json',{result:'PASS',node:{executable:process.execPath,version:process.version,arch:process.arch,platform:process.platform,...record(process.execPath)},powershell:{...system,identity:record(ps)},npm:{path:npm,version:'11.19.0',identity:record(npm),engineeringOnly:true},launchEnvironment:env,networkRequired:false,persistentPolicyMutation:false});
for(const n of ['npm-cache','install','cwd'])fs.mkdirSync(path.join(cache,n));
for(const n of ['user.npmrc','global.npmrc'])fs.writeFileSync(path.join(cache,n),'',{flag:'wx'});
const npmArgs=['--offline','--ignore-scripts','--no-audit','--no-fund','--cache',path.join(cache,'npm-cache'),'--userconfig',path.join(cache,'user.npmrc'),'--globalconfig',path.join(cache,'global.npmrc')];
const extra={PATH:path.dirname(process.execPath),TEMP:cache,TMP:cache};
const packed=JSON.parse(command('package-pack',process.execPath,[npm,'pack','--json','--pack-destination',cache,...npmArgs],source,extra));
assert.equal(packed.length,1);assert.deepEqual(packed[0].files.map(r=>r.path).sort(),[...packageFiles]);
const archive=path.join(cache,packed[0].filename),archiveBinding=put('package/memoryos-readiness-0.1.0.tgz',fs.readFileSync(archive));
fs.writeFileSync(path.join(cache,'install/package.json'),JSON.stringify({name:'mo1307-phase3ar2-c3tb-offline',version:'1.0.0',private:true})+'\n',{flag:'wx'});
command('offline-install',process.execPath,[npm,'install',archive,...npmArgs],path.join(cache,'install'),extra);
const members=walk(installed);assert.equal(members.length,89);assert.deepEqual(members,production);const installedCheck=checkPackage(installed);
assert.equal(hash(Buffer.from(canonical(members)+'\n')),packageIdentity);
write('installed-before.json',{result:'PASS',members,packageRoot:installed,sourceAndC3TBEqual:true,packageIdentity,check:installedCheck,noScripts:true,offline:true,networkFallback:false});
write('candidate-identity.json',{result:'PASS',C3TB,C3T,productionTree,authority:integration,packageRoot:installed,packageName:'memoryos-readiness',version:'0.1.0',members:89,packageIdentity,helperSha256:'sha256:97ef5ae9ce7ab390548b04a2aefba9f922c3e1c6b9b80581c6c274f0b21f0127',archive:archiveBinding,npmPack:packed[0],repositoryAuthority:record(path.join(root,'repositories/cca-conformance/tools/mo1307-phase1/package.mjs')),candidateAuthority:record(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/candidate.json')),duplicate3B:false});
write('baseline.json',{result:'PASS',startedAt,hardStopAt,HEAD:C3TB,productionCommit:C3T,productionTree,authority:integration,branch:'codex/mo1307-phase3ar2-c3tb',installed:members,source:production,candidate:{name:'memoryos-readiness',version:'0.1.0',members:89,packageIdentity,archive:archiveBinding},runtime:record(process.execPath),productionChanges:0});
const names=['mo1306-qualified','ready','not-ready','could-not-evaluate','rest-qualified','qualified','post-tag-ready','pre-tag-present','post-tag-absent','post-tag-lightweight','post-tag-wrong-target'];
const vectors=names.map((name,index)=>{const src=path.join(root,'repositories/cca-conformance/fixtures/mo1307/bundles',name),base=path.join(cache,'v'+index),inputRoot=path.join(base,'i'),parent=path.join(base,'p');fs.mkdirSync(parent,{recursive:true});fs.cpSync(src,inputRoot,{recursive:true});fs.writeFileSync(path.join(parent,'owned-parent.txt'),'Private stable parent for fresh C3TB certification.\n',{flag:'wx'});return {name,index,inputRoot,parent,source:walk(src),input:walk(inputRoot),expected:record(path.join(src,'expected-result.json'))};});
write('vectors-prepared.json',{vectors});
const {loadBundle,envelopeFor,repin}=await import('../mo1307-phase2b/test-support.mjs');
const bundle=loadBundle('post-tag-ready');envelopeFor(bundle,'TAG_OBSERVATION').claim.detail.name='memoryos-1.3-wrong-tag';const input=repin(bundle);
const inputRoot=path.join(cache,'wrong-name-input');fs.mkdirSync(inputRoot);
for(const [name,b]of [['configuration.json',input.configurationBytes],['candidate.json',input.candidateBytes],['authority.json',input.authorityBytes],['manifest.json',input.manifestBytes]])fs.writeFileSync(path.join(inputRoot,name),b,{flag:'wx'});
for(const entry of bundle.manifest.entries){const file=path.join(inputRoot,entry.path);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bundle.files.get(entry.id),{flag:'wx'});}
const {assessInWorker}=await import(pathToFileURL(path.join(installed,'src/integration.mjs')).href);
const expected=Buffer.from(assessInWorker(input,false).resultBytes),result=JSON.parse(expected);
assert.equal(result.assessment.readiness,'NOT_READY');assert.ok(result.assessment.blockers.some(x=>x.gateId==='tag'&&x.checkCode==='TAG_NAME'));
const expectedPath=path.join(E,'prepared-wrong-name/expected-result.json');put('prepared-wrong-name/expected-result.json',expected);
write('wrong-name-prepared.json',{inputRoot,expectedPath,pins:{expectedCandidateDigest:input.expectedCandidateDigest,trustedAuthorityDigest:input.trustedAuthorityDigest},result,input:walk(inputRoot),derivation:'Frozen Phase2D D11 wrong-name mutation. One pure installed semantic oracle before sealing, not a CLI/API/helper/worker execution or certification observation.',oracle:record(path.join(installed,'src/integration.mjs')),authority:record(path.join(root,'repositories/cca-conformance/tests/mo1307_phase2d_semantic_test.mjs'))});
console.log(JSON.stringify({result:'PASS',phase:'PREPARATION_ONLY',archive:archiveBinding,installed:members.length,historical:historical.length,runtime:system.powerShellVersion,certificationCasesExecuted:0}));
