#pragma once
#include <cca/process/process.hpp>
#include <cca/representation/representation.hpp>
#include <cstddef>
#include <memory>
#include <string>
#include <string_view>
#include <vector>
namespace cca::persistence {
enum class PersistenceFormat { Canonical };
class PersistenceMetadata { public: PersistenceMetadata() noexcept; PersistenceMetadata(std::string,std::string); ~PersistenceMetadata(); PersistenceMetadata(const PersistenceMetadata&); PersistenceMetadata& operator=(const PersistenceMetadata&); PersistenceMetadata(PersistenceMetadata&&) noexcept; PersistenceMetadata& operator=(PersistenceMetadata&&) noexcept; const std::string& workspaceName() const noexcept; const std::string& description() const noexcept; private: std::string workspace_name_,description_; };
class ExecutionContextSnapshot { public: ExecutionContextSnapshot(std::size_t,cca::process::ExecutionState,std::vector<cca::representation::RepresentationId>); ~ExecutionContextSnapshot(); ExecutionContextSnapshot(const ExecutionContextSnapshot&); ExecutionContextSnapshot& operator=(const ExecutionContextSnapshot&); ExecutionContextSnapshot(ExecutionContextSnapshot&&) noexcept; ExecutionContextSnapshot& operator=(ExecutionContextSnapshot&&) noexcept; std::size_t processDefinitionIndex() const noexcept; cca::process::ExecutionState state() const noexcept; const std::vector<cca::representation::RepresentationId>& trace() const noexcept; private: std::size_t index_; cca::process::ExecutionState state_; std::vector<cca::representation::RepresentationId> trace_; };
class PersistencePackage { public: PersistencePackage(const cca::representation::RepresentationDocument&,const PersistenceMetadata&,std::vector<std::string> = {},std::vector<cca::process::ProcessDefinition> = {},std::vector<ExecutionContextSnapshot> = {},PersistenceFormat = PersistenceFormat::Canonical); ~PersistencePackage(); PersistencePackage(const PersistencePackage&); PersistencePackage& operator=(const PersistencePackage&); PersistencePackage(PersistencePackage&&) noexcept; PersistencePackage& operator=(PersistencePackage&&) noexcept; const cca::representation::RepresentationDocument& workspace() const noexcept; const PersistenceMetadata& metadata() const noexcept; const std::vector<std::string>& policies() const noexcept; const std::vector<cca::process::ProcessDefinition>& processDefinitions() const noexcept; PersistenceFormat format() const noexcept; const std::vector<ExecutionContextSnapshot>& executionContexts() const noexcept; private: class Impl; std::unique_ptr<Impl> impl_; };
class PersistenceResult { public: PersistenceResult(PersistenceResult&&) noexcept; PersistenceResult& operator=(PersistenceResult&&) noexcept; PersistenceResult(const PersistenceResult&)=delete; PersistenceResult& operator=(const PersistenceResult&)=delete; ~PersistenceResult(); bool succeeded() const noexcept; const std::string& code() const noexcept; const std::string& message() const noexcept; const PersistencePackage* package() const noexcept; private: PersistenceResult(); friend class PersistenceEngine; class Impl; std::unique_ptr<Impl> impl_; };
class PersistenceEngine { public: PersistenceEngine() noexcept = default; PersistenceResult save(const cca::representation::RepresentationDocument&,const PersistenceMetadata&,const std::vector<std::string>& = {},const std::vector<cca::process::ProcessDefinition>& = {},const std::vector<ExecutionContextSnapshot>& = {},PersistenceFormat = PersistenceFormat::Canonical) const; PersistenceResult load(const PersistencePackage&) const; PersistenceResult validate(const PersistencePackage&) const; };
}
