import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const [sourceWorkspace,workspace]=process.argv.slice(2);
assert(sourceWorkspace&&workspace&&!fs.existsSync(workspace));
const hash=p=>'sha256:'+createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const sourceHome=path.join(sourceWorkspace,'_memoryos/tool/repositories/memoryos-ci'),home=path.join(workspace,'_memoryos/tool/repositories/memoryos-ci');
const runId=fs.readFileSync(path.join(sourceWorkspace,'outputs.txt'),'utf8').split('\n')[2].slice(7);
assert.match(runId,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
fs.mkdirSync(path.dirname(home),{recursive:true});fs.cpSync(sourceHome,home,{recursive:true});
const runtime=path.join(workspace,'_memoryos/runtime');fs.mkdirSync(runtime);fs.copyFileSync(path.join(sourceWorkspace,'_memoryos/runtime/node.exe'),path.join(runtime,'node.exe'));
const config=path.join(workspace,'_memoryos/tool/config.json');fs.copyFileSync(path.join(sourceWorkspace,'_memoryos/tool/config.json'),config);
const out=path.join(workspace,'_memoryos/data/.memoryos-ci/out');fs.mkdirSync(out,{recursive:true});
const saved=path.join(out,'saved-'+runId);fs.cpSync(path.join(sourceWorkspace,'_memoryos/data/.memoryos-ci/out',runId),saved,{recursive:true});
const substituted=path.join(out,runId);fs.symlinkSync(saved,substituted,'junction');
assert.equal(fs.lstatSync(substituted).isSymbolicLink(),true);
const env={SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,PATHEXT:'.COM;.EXE;.BAT;.CMD',MEMORYOS_CI_HOME:home,MEMORYOS_CI_CONFIG:config,GITHUB_REPOSITORY:'memoryos/offline-test',GITHUB_SHA:'e1c990bf65d0c7925a68eea8222cd304f8ce6db6',GITHUB_RUN_ID:'1001',GITHUB_RUN_ATTEMPT:'1',GITHUB_JOB:'memoryos_ci',GITHUB_EVENT_NAME:'workflow_dispatch',COMPLETE:'true',EXIT_CODE:'0',RUN_ID:runId,EVALUATE_OUTCOME:'success',UPLOAD_OUTCOME:'success'};
const command=[path.join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe'),'-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(home,'scripts/Invoke-GitHubCI.ps1'),'-Mode','Gate','-WorkspaceRoot',workspace,'-ConfigurationDigest',hash(config),'-DistributionDigest',hash(path.join(home,'distribution-manifest.json'))];
const result=spawnSync(command[0],command.slice(1),{env,cwd:workspace,encoding:'utf8',timeout:90000,maxBuffer:65536,windowsHide:true});
const report={kind:'MemoryOSCICDGitHubReparseReceipt',version:'1.0.0',status:result.status===15?'PASS':'FAIL',passed:result.status===15?1:0,productionDigest:hash(path.join(home,'distribution-manifest.json')),harnessSha256:hash(fileURLToPath(import.meta.url)),cases:[{id:'run-directory-junction-substitution',expectedExitCode:15,actualExitCode:result.status,status:result.status===15?'PASS':'FAIL'}],command,stdout:result.stdout,stderr:result.stderr,networkExecuted:false,hostedExecuted:false};
fs.writeFileSync(path.join(workspace,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify(report)+'\n');
assert.equal(result.status,15);
