// Existing evidence only. No current internet census, risk acceptance or governance decision.
import assert from 'node:assert/strict';
import {root,E,S,C3TB,C3T,HISTORICAL_3B,hash,json,rec,write,gitBytes} from './common.mjs';

const historicalEvidence='repositories/cca-conformance/evidence/mo1307/phase3b-c3rb-cert';
function input(commit,path){const bytes=gitBytes(commit,path);return {identity:{commit,path,byteLength:bytes.length,sha256:hash(bytes)},value:JSON.parse(bytes)};}
const carried=input(HISTORICAL_3B,historicalEvidence+'/advisory-handoff.json');
const snapshot=input('4a1de6f00788e3c52a647d6f25aa1dbd2d5d5d97','repositories/cca-conformance/evidence/mo1305-phase3br/advisory-snapshot.json');
assert.equal(carried.value.result,'OPEN_ADVISORY_HANDOFF');assert.equal(carried.value.historical3BRFinding.status,'OPEN_PHASE3D_DISPOSITION_REQUIRED');assert.equal(carried.value.riskAccepted,false);
const rows=snapshot.value.advisories.filter(r=>r.component==='node'&&r.source.endsWith('/july-2026-security-releases'));assert.equal(rows.length,11);
const closure=json(E+'/runtime-closure.json'),definitions=json(S+'/contracts/definitions.json'),supply=json(E+'/supply.json');assert.equal(definitions.topology.network,false);assert.equal(definitions.runtime.externalProductionDependencies,0);assert.ok(!closure.builtins.some(s=>/^node:(http|http2|https|dns|net|tls|dgram)(\/|$)/u.test(s)));
const phase3DHandoff='Integrate the immutable Phase 3BR2 receipt and refresh commit for exact C3TB 119e68bdcf0ffc906b4ca03a912aadcb25908346 with independently accepted exact-C3TB Phase 3AR2 and Phase 3CR2 receipts. Bind the fresh 89-member archive by exact byte length and SHA-256, C3T 65e24b2debdd70ecb8e52fbccbd6c101621f1917, production tree 324bf600b6cbfaa8564db27fce2d999711270cb8, and PROSPECTIVE_HELPER_BOUND@1.0.0. Preserve historical Phase 3B 702c1b6381f6112a50ac844831d195275dac3350 unchanged as C3RB-only history, H = NOT_ESTABLISHED, the open Node HTTP/2 advisory, licensing and provider/platform qualifications, and the separation of human risk acceptance and release authorization. No Phase 3D action was performed here.';
write(E+'/advisory-handoff.json',{kind:'MO1307Phase3BR2AdvisoryHandoff',version:'1.0.0',createdUtc:new Date().toISOString(),candidateBinding:C3TB,productionCandidate:C3T,archive:rec(E+'/memoryos-readiness-0.1.0.tgz'),result:'OPEN_ADVISORY_HANDOFF',handling:'PASS',reviewScope:'Authorized existing repository evidence and exact current runtime boundary only. No new upstream retrieval or current vulnerability census. Historical review is not a fresh same-date scan.',sources:[carried.identity,snapshot.identity],historical3BFinding:carried.value.historical3BRFinding,earlierMO1305Snapshot:{date:snapshot.value.snapshotDateUtc,sourceRetrieval:snapshot.value.sources.find(r=>r.url.endsWith('/july-2026-security-releases')),records:rows,scope:'Historical attributed claims only; they do not identify the HTTP/2 subset or resolve the MO-1307 handoff.'},exactHttp2CveIdentity:'NOT ESTABLISHED',finalApplicability:'NOT ESTABLISHED',currentAdvisoryCensus:'NOT ESTABLISHED',H:'NOT_ESTABLISHED',riskAccepted:false,zeroVulnerabilityClaim:false,exactRuntime:supply.node,packageBoundary:{candidateBinding:C3TB,productionCandidate:C3T,topologyNetwork:false,externalProductionDependencies:0,builtins:closure.builtins,closure:rec(E+'/runtime-closure.json'),definitions:rec(S+'/contracts/definitions.json'),limitation:'Static package closure does not establish runtime exploitability, not-affected status or risk acceptance.'},phase3DHandoff,qualifications:['First-party licensing remains UNLICENSED/NOASSERTION; no product license or publication grant.','Bounded existing-evidence advisory review; exact HTTP/2 identification and final applicability remain open.','Provider accounts, hosted execution and non-Windows platforms remain outside this Phase 3BR2 scope.'],notApplicable:['Provider accounts and hosted execution are outside the frozen Phase 3BR2 scope.','Non-Windows platform certification is outside this Windows package/toolchain refresh.'],humanRiskAcceptance:false,finalReleaseAuthorization:false});
console.log(JSON.stringify({handling:'PASS',advisory:'OPEN_ADVISORY_HANDOFF',historicalNodeCves:rows.length,exactHttp2Subset:'NOT ESTABLISHED',riskAccepted:false}));
