// One-shot fresh Phase 3BR2 campaign for exact C3TB. First mandatory failure stops.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {packageFiles,checkPackage,canonical,root,E,S,T,C3TB,C3T,C3T_PARENT,C3RB,HISTORICAL_3B,PRODUCTION_TREE,PACKAGE_IDENTITY,HELPER_SHA256,DISTRIBUTION_SHA256,SBOM_SHA256,BRANCH,limits,node,npm,python,cache,hash,read,json,rec,write,git,gitBytes,walk,inventory,packageIdentity,controlledEnv,command,tarMembers,archiveIdentity,runtimeClosure,verifyRecord,artifactTamperControls,closureTamperControls} from './common.mjs';

const candidateEvidence='repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate';
const historicalEvidence='repositories/cca-conformance/evidence/mo1307/phase3b-c3rb-cert';
const historicalTools='repositories/cca-conformance/tools/mo1307-phase3b-c3rb-cert';
const historicalReport='docs/mo1307-phase3b-c3rb-cert.md';
const started=new Date().toISOString(),results=[];
const protocol=json(T+'/protocol.json');
function lines(value){return value.split(/\r?\n/u).filter(Boolean).sort();}
if(fs.existsSync(path.join(root,E,'campaign-start.json')))throw new Error('NO_RERUN: campaign already started');
assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['branch','--show-current']),BRANCH);assert.equal(git(['rev-parse','HEAD^']),C3T);
assert.equal(git(['diff','--name-only']),'');assert.equal(git(['diff','--cached','--name-only']),'');
const setup=json(E+'/setup.json');assert.equal(setup.candidateBinding,C3TB);assert.equal(setup.branch,BRANCH);assert.equal(setup.cleanBeforeTooling,true);
const expectedPreflight=[...walk(path.join(root,T)).map(p=>T+'/'+p),E+'/setup.json'].sort();
assert.deepEqual(lines(git(['ls-files','--others','--exclude-standard'])),expectedPreflight,'Unexpected pre-campaign paths');
write(E+'/campaign-start.json',{startedUtc:started,candidateBinding:C3TB,productionCandidate:C3T,protocol:rec(T+'/protocol.json'),tooling:walk(path.join(root,T)).map(p=>rec(T+'/'+p)),attempt:1,noRetry:true});
let stage='initialization',sourceRows,prospectiveCandidate,prospectiveAuthority;
function step(name,fn){stage=name;write(E+'/progress.json',{startedUtc:started,active:name,completed:results});const value=fn();results.push({name,result:'PASS',finishedUtc:new Date().toISOString()});write(E+'/progress.json',{startedUtc:started,active:null,completed:results});return value;}
function historicalInventory(){
  const names=[historicalReport,...lines(git(['ls-tree','-r','--name-only',HISTORICAL_3B,'--',historicalEvidence,historicalTools]))];
  const files=names.map(p=>{const b=gitBytes(HISTORICAL_3B,p);return {commit:HISTORICAL_3B,...rec(p,b),gitBlob:git(['rev-parse',HISTORICAL_3B+':'+p])};});
  return {commit:HISTORICAL_3B,commitType:git(['cat-file','-t',HISTORICAL_3B]),tree:git(['rev-parse',HISTORICAL_3B+'^{tree}']),scope:'Historical accepted C3RB Phase 3B report, evidence and tooling; read only from immutable Git objects.',files};
}
function assertCandidateBytes(relative){const current=read(relative);assert.ok(current.equals(gitBytes(C3T,relative)),relative+' differs from C3T');assert.ok(current.equals(gitBytes(C3TB,relative)),relative+' differs from C3TB');return current;}
try{
step('candidate-toolchain-preflight',()=>{
  assert.equal(process.version,'v24.21.0');assert.equal(process.platform,'win32');assert.equal(process.arch,'x64');
  assert.equal(path.resolve(process.execPath),path.resolve(node));assert.equal(hash(fs.readFileSync(process.execPath)),'ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32');assert.equal(fs.statSync(process.execPath).size,93580104);
  assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['branch','--show-current']),BRANCH);assert.equal(git(['rev-parse','HEAD^']),C3T);
  assert.equal(git(['show','-s','--format=%s',C3TB]),'conformance(memoryos-1.3): bind prospective MO-1307 helper-bound candidate');
  assert.equal(git(['show','-s','--format=%s',C3T]),'fix(memoryos-1.3): adopt prospective MO-1307 helper bound');
  assert.deepEqual(lines(git(['diff-tree','--no-commit-id','--name-only','-r',C3TB])),[
    candidateEvidence+'/binding-verification.json',candidateEvidence+'/binding.json',
  ].sort());
  assert.equal(git(['rev-parse',C3T+':'+S]),PRODUCTION_TREE);assert.equal(git(['rev-parse',C3TB+':'+S]),PRODUCTION_TREE);
  prospectiveCandidate=json(candidateEvidence+'/candidate.json');assertCandidateBytes(candidateEvidence+'/candidate.json');assert.equal(prospectiveCandidate.candidateRole,'C3T');assert.equal(prospectiveCandidate.result,'READY_FOR_BINDING');
  verifyRecord(prospectiveCandidate.prospectiveAuthority);assertCandidateBytes(prospectiveCandidate.prospectiveAuthority.path);prospectiveAuthority=json(prospectiveCandidate.prospectiveAuthority.path);
  assert.equal(prospectiveAuthority.kind,'MO1307ProspectiveHelperBoundAuthority');assert.equal(prospectiveAuthority.version,'1.0.0');assert.equal(prospectiveAuthority.identity,'PROSPECTIVE_HELPER_BOUND@1.0.0');assert.equal(prospectiveAuthority.status,'ADOPTED_PROSPECTIVELY');assert.equal(prospectiveAuthority.appliesFromCandidate,'C3T');assert.equal(prospectiveAuthority.certification,false);assert.equal(prospectiveAuthority.retroactive,false);assert.equal(prospectiveAuthority.statisticalH,false);assert.equal(prospectiveAuthority.humanReleaseAuthorization,false);assert.equal(prospectiveAuthority.valueMs,8000);
  const authorityLimits={aggregateHelperActiveMs:20000,apiMs:10000,cleanupMs:2000,cliAdmissionMs:30000,helperMs:8000,workerMs:10000};assert.deepEqual(prospectiveAuthority.limits,authorityLimits);assert.deepEqual(prospectiveCandidate.limits,authorityLimits);assert.deepEqual(prospectiveAuthority.relation,{equality:'TIMEOUT',success:'elapsedMs < 8000',timeout:'elapsedMs >= 8000'});assert.deepEqual(prospectiveAuthority.cleanup,{beginsAfterTerminalHelperOutcome:true,separateAllowanceMs:2000,successGrace:false});assert.equal(prospectiveAuthority.historical.H,'NOT_ESTABLISHED');assert.equal(prospectiveCandidate.historicalAuthorities.H,'NOT_ESTABLISHED');assert.equal(prospectiveCandidate.humanReleaseAuthorization,false);
  assert.equal(git(['diff','--name-only']),'');assert.equal(git(['diff','--cached','--name-only']),'');
  const allowed=[T+'/',E+'/','docs/mo1307-phase3br2-c3tb.md'];for(const p of lines(git(['ls-files','--others','--exclude-standard'])))assert.ok(allowed.some(a=>a.endsWith('/')?p.startsWith(a):p===a),p);
  assert.equal(git(['cat-file','-t',HISTORICAL_3B]),'commit');const historical=historicalInventory();assert.ok(historical.files.length>=90);write(E+'/historical-before.json',historical);
  const priorReceipt=JSON.parse(gitBytes(HISTORICAL_3B,historicalEvidence+'/certification-receipt.json'));const priorFinal=JSON.parse(gitBytes(HISTORICAL_3B,historicalEvidence+'/final-validation.json'));
  assert.equal(priorReceipt.result,'PHASE3B_ACCEPTED_WITH_QUALIFICATIONS');assert.equal(priorFinal.result,'PASS');assert.equal(priorFinal.source,C3RB);
  const ps='C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe';const os=JSON.parse(command('platform',ps,['-NoLogo','-NoProfile','-NonInteractive','-Command',"$v=Get-ItemProperty -LiteralPath 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion'; [pscustomobject]@{caption=$v.ProductName;displayVersion=$v.DisplayVersion;version=[Environment]::OSVersion.Version.ToString();build=$v.CurrentBuildNumber;architecture=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();powershell=$PSVersionTable.PSVersion.ToString()} | ConvertTo-Json -Compress"]).output);
  assert.match(os.caption,/^Windows /u);assert.match(os.version,/^10\.0\./u);assert.ok(Number(os.build)>=22000);assert.match(os.architecture,/^X64$/u);assert.match(os.powershell,/^5\.1\./u);
  write(E+'/baseline.json',{result:'PASS',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,rootTree:git(['rev-parse',C3TB+'^{tree}']),authority:'PROSPECTIVE_HELPER_BOUND@1.0.0',authorityRecord:{declared:prospectiveCandidate.prospectiveAuthority,observed:rec(prospectiveCandidate.prospectiveAuthority.path)},H:'NOT_ESTABLISHED',historicalAcceptedPhase3B:HISTORICAL_3B,worktree:root,branch:BRANCH,initialCleanObservation:json(E+'/setup.json').cleanBeforeTooling,platform:os,node:{...rec(node),version:process.version,components:process.versions},git:{...rec('C:/Program Files/Git/cmd/git.exe'),version:git(['--version'])},packageChecker:rec('repositories/cca-conformance/tools/mo1307-phase1/package.mjs'),workspaceChecker:rec('tools/verify_workspace.py'),startedUtc:started,productionChanges:0});
});
step('candidate-package-deadline-binding',()=>{
  const check=checkPackage(path.join(root,S));sourceRows=inventory(path.join(root,S));assert.deepEqual(sourceRows.map(r=>r.path),packageFiles);assert.equal(sourceRows.length,89);assert.equal(packageIdentity(sourceRows),PACKAGE_IDENTITY);
  const gitRows=git(['ls-tree','-r',C3T,'--',S]).split(/\r?\n/u).filter(Boolean).map(l=>{const [meta,p]=l.split('\t');return {path:p,blob:meta.split(' ')[2]};});assert.equal(gitRows.length,89);
  for(const r of gitRows){const b=assertCandidateBytes(r.path);assert.equal(hash(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b]),'sha1'),r.blob,r.path);}
  assert.equal(hash(read(S+'/helpers/windows-inspect.ps1')),HELPER_SHA256);assert.equal(hash(read(S+'/distribution-manifest.json')),DISTRIBUTION_SHA256);assert.equal(hash(read(S+'/sbom.spdx.json')),SBOM_SHA256);
  const candidate=prospectiveCandidate,binding=json(candidateEvidence+'/binding.json'),bindingVerification=json(candidateEvidence+'/binding-verification.json'),refreshMap=json(candidateEvidence+'/phase3b-refresh-map.json');
  assert.equal(candidate.result,'READY_FOR_BINDING');assert.equal(candidate.candidateRole,'C3T');assert.equal(candidate.package.packageIdentity,'sha256:'+PACKAGE_IDENTITY);assert.equal(candidate.package.packageMemberCount,89);
  assert.equal(binding.implementation.commit,C3T);assert.equal(binding.implementation.productionTree,PRODUCTION_TREE);assert.equal(binding.binding.soleParent,C3T);assert.equal(binding.bindingRole,'C3TB');
  assert.equal(bindingVerification.result,'PASS');assert.equal(bindingVerification.candidateCommit,C3T);assert.equal(bindingVerification.productionTree,PRODUCTION_TREE);assert.equal(refreshMap.status,'PENDING_SEPARATE_EXECUTION');assert.deepEqual(refreshMap.freshTamperControls,artifactTamperControls);assert.deepEqual(refreshMap.reuseOnlyAfterExactDependencyProof,[...closureTamperControls,'UNCHANGED_PROVIDER_CONCLUSIONS','UNCHANGED_ADVISORY_CONCLUSIONS','UNCHANGED_LICENSING_CONCLUSIONS']);
  const expectedParentChanges=['README.md','contracts/contract.json','contracts/definitions.json','distribution-manifest.json','helpers/README.md','sbom.spdx.json','src/constants.mjs'].map(p=>S+'/'+p).sort();
  const parentChanges=lines(git(['diff','--name-only',C3T_PARENT,C3T,'--',S]));assert.deepEqual(parentChanges,expectedParentChanges);
  const expectedHistoricalChanges=[...expectedParentChanges,S+'/helpers/windows-inspect.ps1',S+'/src/helper-transport.mjs'].sort();const historicalChanges=lines(git(['diff','--name-only',C3RB,C3T,'--',S]));assert.deepEqual(historicalChanges,expectedHistoricalChanges);
  const definitions=json(S+'/contracts/definitions.json'),oldDefinitions=JSON.parse(gitBytes(C3RB,S+'/contracts/definitions.json'));const currentLimits=definitions.limits,oldLimits=oldDefinitions.limits;
  assert.deepEqual(Object.keys(currentLimits).sort(),Object.keys(oldLimits).sort());const limitChanges=Object.keys(currentLimits).filter(k=>canonical(currentLimits[k])!==canonical(oldLimits[k])).sort();assert.deepEqual(limitChanges,['helperDeadlineMs']);assert.equal(oldLimits.helperDeadlineMs,5000);
  for(const [key,value] of Object.entries({helperDeadlineMs:8000,helperAggregateDeadlineMs:20000,cliDeadlineMs:30000,apiDeadlineMs:10000,cleanupAllowanceMs:2000}))assert.equal(currentLimits[key],value,key);
  assert.equal(definitions.topology.network,false);assert.equal(definitions.runtime.externalProductionDependencies,0);
  const runtime=read(S+'/src/runtime.mjs').toString('utf8');assert.ok(read(S+'/src/runtime.mjs').equals(gitBytes(C3T_PARENT,S+'/src/runtime.mjs')),'Runtime changed from authority parent');
  assert.match(runtime,/current >= Math\.min\(deadline, limit\)/u);assert.match(runtime,/launch \+ L\.helperDeadlineMs/u);assert.match(runtime,/launch \+ L\.helperAggregateDeadlineMs/u);assert.match(runtime,/kind === 'api' \? L\.apiDeadlineMs : L\.cliDeadlineMs/u);assert.match(runtime,/terminalAt \+ L\.cleanupAllowanceMs/u);
  const closure=runtimeClosure(path.join(root,S));assert.equal(closure.externalProductionDependencies,0);assert.ok(!closure.builtins.some(s=>/^node:(http|https|http2|net|tls|dns|dgram)(\/|$)/u.test(s)));
  write(E+'/source-inventory.json',{result:'PASS',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,check,canonicalInventorySha256:PACKAGE_IDENTITY,gitBlobs:gitRows,members:sourceRows});
  const distribution=json(S+'/distribution-manifest.json'),contract=json(S+'/contracts/contract.json'),sbom=json(S+'/sbom.spdx.json');assert.equal(distribution.files.length,88);assert.equal(contract.files.length,53);assert.equal(sbom.files.length,87);assert.equal(sbom.packages.length,1);assert.equal(sbom.relationships.length,88);
  write(E+'/distribution.json',{result:'PASS',identity:rec(S+'/distribution-manifest.json'),expectedSha256:DISTRIBUTION_SHA256,rows:88,manifest:distribution,canonical:true});
  write(E+'/contract.json',{result:'PASS',identity:rec(S+'/contracts/contract.json'),rows:53,schemas:52,generatedRuntimeTablesMatch:true});
  write(E+'/sbom.json',{result:'PASS',semanticCheck:'Exact C3T generated SPDX document recomputed by checkPackage',identity:rec(S+'/sbom.spdx.json'),expectedSha256:SBOM_SHA256,packages:1,files:87,relationships:88,verificationCode:sbom.packages[0].packageVerificationCode,fullSchemaValidation:'document-validation.json'});
  write(E+'/runtime-closure.json',closure);
  const authorityRecord={declared:candidate.prospectiveAuthority,observed:rec(candidate.prospectiveAuthority.path)};
  write(E+'/candidate-binding.json',{result:'PASS',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,rootTree:git(['rev-parse',C3TB+'^{tree}']),bindingOnlyPaths:lines(git(['diff-tree','--no-commit-id','--name-only','-r',C3TB])),candidate:rec(candidateEvidence+'/candidate.json'),prospectiveAuthority:authorityRecord,binding:rec(candidateEvidence+'/binding.json'),bindingVerification:rec(candidateEvidence+'/binding-verification.json'),refreshMap:rec(candidateEvidence+'/phase3b-refresh-map.json'),packageIdentity:'sha256:'+PACKAGE_IDENTITY,helper:rec(S+'/helpers/windows-inspect.ps1'),distribution:rec(S+'/distribution-manifest.json'),sbom:rec(S+'/sbom.spdx.json')});
  write(E+'/deadline-binding.json',{result:'PASS',authority:'PROSPECTIVE_HELPER_BOUND@1.0.0',authorityRecord,authorityStatus:prospectiveAuthority.status,authorityAppliesFromCandidate:prospectiveAuthority.appliesFromCandidate,H:'NOT_ESTABLISHED',success:'elapsed < 8000 ms',timeout:'elapsed >= 8000 ms',candidateBinding:C3TB,productionCandidate:C3T,current:{helperMs:currentLimits.helperDeadlineMs,aggregateHelperActiveMs:currentLimits.helperAggregateDeadlineMs,cliAdmissionMs:currentLimits.cliDeadlineMs,apiMs:currentLimits.apiDeadlineMs,workerMs:currentLimits.apiDeadlineMs,cleanupMs:currentLimits.cleanupAllowanceMs},historicalC3RB:{helperMs:oldLimits.helperDeadlineMs},entireLimitsObjectCompared:true,changedLimitKeys:limitChanges,noOtherResourceValueChanged:true,strictEqualityFailsClosed:true,cleanupStartsAfterTerminal:true,retry:false,deadlineGrace:false,lateSuccessRecovery:false,workerUsesApiDeadline:true,generatedDefinitions:rec(S+'/contracts/definitions.json'),generatedConstants:rec(S+'/src/constants.mjs'),runtime:rec(S+'/src/runtime.mjs'),helperTransport:rec(S+'/src/helper-transport.mjs'),helper:rec(S+'/helpers/windows-inspect.ps1')});
  const unchangedHistorical=sourceRows.filter(r=>!expectedHistoricalChanges.includes(S+'/'+r.path));assert.equal(unchangedHistorical.length,80);
  write(E+'/reuse-analysis.json',{result:'PASS',historicalAcceptedPhase3B:HISTORICAL_3B,historicalCandidate:C3RB,currentCandidateBinding:C3TB,currentProduction:C3T,packageComparison:{changedMembers:expectedHistoricalChanges.map(p=>p.slice(S.length+1)),changedCount:9,unchangedCount:80,wholePackageResultNotReused:true},freshRequiredArtifactControls:[...artifactTamperControls],dependencyProofOnlyControls:[...closureTamperControls],dependencyProof:{packageChecker:{current:rec('repositories/cca-conformance/tools/mo1307-phase1/package.mjs'),historical:{commit:HISTORICAL_3B,...rec('repositories/cca-conformance/tools/mo1307-phase1/package.mjs',gitBytes(HISTORICAL_3B,'repositories/cca-conformance/tools/mo1307-phase1/package.mjs'))},byteEqual:read('repositories/cca-conformance/tools/mo1307-phase1/package.mjs').equals(gitBytes(HISTORICAL_3B,'repositories/cca-conformance/tools/mo1307-phase1/package.mjs'))},schemasUnchanged:git(['diff','--quiet',C3RB,C3T,'--',S+'/schemas'])==='',schemaDataUnchanged:read(S+'/src/schema-data.mjs').equals(gitBytes(C3RB,S+'/src/schema-data.mjs')),packageMetadataUnchanged:read(S+'/package.json').equals(gitBytes(C3RB,S+'/package.json')),importTargetUnchanged:read(S+'/src/index.mjs').equals(gitBytes(C3RB,S+'/src/index.mjs')),nodeExact:true,positiveCurrentPackageCheck:'PASS'},historicalFixtureResults:{reused:false,reason:'Generated definitions/constants changed; complete fixture-result dependency closure is not identical and fixtures are outside the selected artifact refresh.'},providerScope:{retained:true,reason:'Provider accounts and hosted execution remain outside Phase 3BR2; no provider conclusion promoted.'},advisory:{retainedOpenOnly:true,reason:'Exact Node bytes, zero network imports/topology and zero production dependencies remain bound; applicability remains NOT_ESTABLISHED.'},licensing:{retained:true,reason:'LICENSE-NOTICE.md, NOTICES.md and package.json are byte-identical to C3RB; UNLICENSED/NOASSERTION remains.'}});
});
step('fresh-generated-definitions-and-package',()=>{
  const generation=path.join(cache,'generation');assert.ok(!fs.existsSync(generation),'Fresh generation root required');const product=path.join(generation,S),tools=path.join(generation,'repositories/cca-conformance/tools/mo1307-phase1');fs.mkdirSync(path.dirname(product),{recursive:true});fs.cpSync(path.join(root,S),product,{recursive:true});fs.mkdirSync(tools,{recursive:true});
  for(const name of ['generate-contracts.mjs','generate-runtime-data.mjs','package.mjs'])fs.copyFileSync(path.join(root,'repositories/cca-conformance/tools/mo1307-phase1',name),path.join(tools,name));
  command('generation-contracts',node,[path.join(tools,'generate-contracts.mjs')],{cwd:generation,env:controlledEnv(path.join(generation,'home-contracts'))});
  command('generation-runtime-data',node,[path.join(tools,'generate-runtime-data.mjs')],{cwd:generation,env:controlledEnv(path.join(generation,'home-runtime'))});
  command('generation-package-build',node,[path.join(tools,'package.mjs'),'build'],{cwd:generation,env:controlledEnv(path.join(generation,'home-package'))});
  const generatedRows=inventory(product);assert.deepEqual(generatedRows,sourceRows);checkPackage(product);
  const selected=['contracts/definitions.json','contracts/contract.json','src/constants.mjs','src/schema-data.mjs','sbom.spdx.json','distribution-manifest.json',...packageFiles.filter(p=>p.startsWith('schemas/'))].sort();
  write(E+'/generated-definitions.json',{result:'PASS',freshRoot:generation,sourceRoot:product,generators:['generate-contracts.mjs','generate-runtime-data.mjs','package.mjs'].map(n=>rec('repositories/cca-conformance/tools/mo1307-phase1/'+n)),commands:['generation-contracts','generation-runtime-data','generation-package-build'].map(n=>rec(E+'/commands/'+n+'.json')),selectedMembers:selected.map(p=>rec(p,fs.readFileSync(path.join(product,p)))),selectedCount:selected.length,all89MembersEqual:true,canonicalInventorySha256:packageIdentity(generatedRows),limits:json(E+'/deadline-binding.json').current});
});
step('toolchain-schema-licenses',()=>{command('supply',node,[path.join(root,T,'supply.mjs')],{timeout:240000});});
step('full-pinned-document-validation',()=>{const r=command('documents',python,['-I','-S','-B',path.join(root,T,'validate-documents.py')],{timeout:180000});const v=JSON.parse(r.output);assert.equal(v.result,'PASS');write(E+'/document-validation.json',v);});
step('independent-assemblies',()=>{
  const npmVersion=command('npm-version',node,[npm,'--version']).output.trim();assert.equal(npmVersion,'11.19.0');const assemblies=[];
  for(const id of ['a','b']){const base=path.join(cache,'assembly-'+id);assert.ok(!fs.existsSync(base),'Fresh assembly required');const pkg=path.join(base,'package'),out=path.join(base,'out'),npmCache=path.join(base,'npm-cache');for(const p of [pkg,out,npmCache])fs.mkdirSync(p,{recursive:true});for(const member of packageFiles){const dest=path.join(pkg,member);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,read(S+'/'+member));}assert.deepEqual(inventory(pkg),sourceRows);checkPackage(pkg);assert.deepEqual(walk(npmCache),[]);for(const p of ['user.npmrc','global.npmrc'])fs.writeFileSync(path.join(base,p),'');const args=[npm,'pack','--offline','--ignore-scripts','--json','--no-audit','--no-fund','--cache',npmCache,'--userconfig',path.join(base,'user.npmrc'),'--globalconfig',path.join(base,'global.npmrc'),'--pack-destination',out];const run=command('assembly-'+id,node,args,{cwd:pkg,env:controlledEnv(path.join(base,'home'))});const metadata=JSON.parse(run.output);assert.equal(metadata.length,1);assert.equal(metadata[0].filename,'memoryos-readiness-0.1.0.tgz');const archive=path.join(out,metadata[0].filename),b=fs.readFileSync(archive),members=tarMembers(b);for(const m of members)assert.ok(m.data.equals(read(S+'/'+m.path.slice(8))),m.path);assert.deepEqual(inventory(pkg),sourceRows);assemblies.push({id,root:base,archive:rec(archive,b),sourceMembers:sourceRows,command:rec(E+'/commands/assembly-'+id+'.json'),npmMetadata:metadata[0],initialCacheEmpty:true,userConfig:rec(path.join(base,'user.npmrc')),globalConfig:rec(path.join(base,'global.npmrc'))});write(E+'/assemblies-progress.json',{assemblies});}
  const a=fs.readFileSync(assemblies[0].archive.path),b=fs.readFileSync(assemblies[1].archive.path);assert.ok(a.equals(b),'Independent archive bytes differ');const selected=E+'/memoryos-readiness-0.1.0.tgz';write(selected,a);const identity=archiveIdentity(selected);for(const r of assemblies)assert.equal(r.npmMetadata.integrity,identity.integrity);
  const priorPath=historicalEvidence+'/memoryos-readiness-0.1.0.tgz',prior=gitBytes(HISTORICAL_3B,priorPath);assert.ok(!a.equals(prior),'C3TB archive unexpectedly equals historical C3RB archive');
  write(E+'/candidate.json',{result:'PASS',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,package:'memoryos-readiness@0.1.0',contract:'memoryos.readiness@1.0.0',memberCount:89,canonicalInventorySha256:PACKAGE_IDENTITY,...identity});
  write(E+'/assemblies.json',{result:'PASS',assemblies,independentFreshRoots:true,archiveBytesEqual:true,selected:identity,historicalC3RBComparison:{commit:HISTORICAL_3B,...rec(priorPath,prior),equal:false,archiveReused:false,comparisonOnly:true}});
  write(E+'/archive-inventory.json',{result:'PASS',archive:identity,members:tarMembers(a).map(({data,...r})=>r),missing:[],unexpected:[],unsafe:[],nonregular:[],sourceBytesEqual:true,canonicalInventorySha256:PACKAGE_IDENTITY});
});
step('fresh-offline-install',()=>{
  const install=path.join(cache,'installed'),installCache=path.join(cache,'install-cache');assert.ok(!fs.existsSync(install));assert.ok(!fs.existsSync(installCache));fs.mkdirSync(install,{recursive:true});fs.mkdirSync(installCache,{recursive:true});fs.writeFileSync(path.join(install,'package.json'),JSON.stringify({private:true,name:'mo1307-phase3br2-c3tb-install',version:'1.0.0'})+'\n');for(const n of ['user.npmrc','global.npmrc'])fs.writeFileSync(path.join(install,n),'');assert.deepEqual(walk(installCache),[]);const args=[npm,'install',path.join(root,E,'memoryos-readiness-0.1.0.tgz'),'--offline','--ignore-scripts','--no-audit','--no-fund','--package-lock=false','--cache',installCache,'--userconfig',path.join(install,'user.npmrc'),'--globalconfig',path.join(install,'global.npmrc')];command('offline-install',node,args,{cwd:install,env:controlledEnv(path.join(cache,'install-home'))});const pkg=path.join(install,'node_modules/memoryos-readiness');assert.deepEqual(inventory(pkg),sourceRows);checkPackage(pkg);assert.deepEqual(fs.readdirSync(path.join(install,'node_modules')).filter(n=>!n.startsWith('.')),['memoryos-readiness']);const installedLimits=JSON.parse(fs.readFileSync(path.join(pkg,'contracts/definitions.json'))).limits;for(const [key,value] of Object.entries({helperDeadlineMs:8000,helperAggregateDeadlineMs:20000,cliDeadlineMs:30000,apiDeadlineMs:10000,cleanupAllowanceMs:2000}))assert.equal(installedLimits[key],value,key);write(E+'/offline-install.json',{result:'PASS',archive:json(E+'/candidate.json'),command:rec(E+'/commands/offline-install.json'),packageDirectory:pkg,root:install,emptyCache:true,offline:true,scripts:false,audit:false,fund:false,networkFallback:false,productionDependencies:0,limits:{helperMs:installedLimits.helperDeadlineMs,aggregateMs:installedLimits.helperAggregateDeadlineMs,cliMs:installedLimits.cliDeadlineMs,apiMs:installedLimits.apiDeadlineMs,workerMs:installedLimits.apiDeadlineMs,cleanupMs:installedLimits.cleanupAllowanceMs}});write(E+'/installed-inventory-before.json',{result:'PASS',root:pkg,members:inventory(pkg),archiveAndSourceParity:true});
});
step('installed-package-smoke-and-persistence',()=>{command('installed-smoke-driver',node,[path.join(root,T,'smoke.mjs')],{timeout:90000});});
step('artifact-and-closure-tamper-controls',()=>{command('tamper',node,[path.join(root,T,'tamper.mjs')],{timeout:90000});const t=json(E+'/tamper-controls.json');assert.equal(t.result,'PASS');assert.equal(t.productionMutated,false);assert.equal(t.freshArtifactBoundCount,16);assert.deepEqual(t.requiredFreshMap,artifactTamperControls);assert.deepEqual(t.freshArtifactBoundControls.map(r=>r.name),artifactTamperControls);assert.ok(t.freshArtifactBoundControls.every(r=>r.result==='PASS'));assert.equal(t.reusedClosureCount,6);assert.deepEqual(t.reusedClosureControls.map(r=>r.name),closureTamperControls);assert.ok(t.reusedClosureControls.every(r=>r.result==='PASS'&&r.classification==='REUSED_AFTER_EXACT_DEPENDENCY_PROOF'));});
step('bounded-advisory-handoff',()=>{command('advisory',node,[path.join(root,T,'advisory.mjs')]);});
step('workspace-and-historical-preservation',()=>{
  command('workspace-verification',python,['-I','-B',path.join(root,'tools/verify_workspace.py'),'--root',root],{timeout:180000});assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['diff','--name-only']),'');assert.equal(git(['diff','--cached','--name-only']),'');
  const historical=json(E+'/historical-before.json');assert.equal(git(['cat-file','-t',historical.commit]),'commit');assert.equal(git(['rev-parse',historical.commit+'^{tree}']),historical.tree);for(const r of historical.files){const b=gitBytes(historical.commit,r.path);assert.equal(b.length,r.byteLength,r.path);assert.equal(hash(b),r.sha256,r.path);assert.equal(git(['rev-parse',historical.commit+':'+r.path]),r.gitBlob,r.path);}
  const frozenTooling=json(E+'/campaign-start.json').tooling;assert.deepEqual(walk(path.join(root,T)).map(p=>T+'/'+p).sort(),frozenTooling.map(r=>r.path).sort(),'Campaign tool path set changed');for(const r of frozenTooling)assert.deepEqual(rec(r.path),r,'Campaign tool changed');
  write(E+'/historical-preservation.json',{result:'PASS',commit:HISTORICAL_3B,tree:historical.tree,before:rec(E+'/historical-before.json'),filesRehashed:historical.files.length,immutableGitObjects:true,historicalEvidenceRewritten:false,appliesOnlyTo:C3RB});
});
assert.deepEqual(results.map(r=>r.name),protocol.executionStages);write(E+'/execution.json',{result:'PASS',startedUtc:started,finishedUtc:new Date().toISOString(),candidateBinding:C3TB,productionCandidate:C3T,stages:results,mandatoryExecutionComplete:true,acceptancePendingReviewAndSeal:true,attempt:1});console.log(JSON.stringify({result:'PASS',candidate:json(E+'/candidate.json'),stages:results.length,pending:'Independent evidence review and immutable seal'}));
}catch(error){const failure={result:'PHASE3BR2_FAILED_INCOMPLETE',candidateBinding:C3TB,productionCandidate:C3T,stage,startedUtc:started,stoppedUtc:new Date().toISOString(),error:{name:error.name,message:error.message,stack:error.stack,actual:error.actual,expected:error.expected},completed:results,notExecuted:protocol.executionStages.filter(p=>!results.some(r=>r.name===p)&&p!==stage),attempt:1,retry:false,productionRepaired:false,acceptedHandoff:false};write(E+'/failure.json',failure);console.error(JSON.stringify(failure,null,2));process.exitCode=1;}
