// Independent read-only review of the completed one-shot campaign, followed by one review record.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {root,E,S,T,D,C3TB,C3T,HISTORICAL_3B,PACKAGE_IDENTITY,artifactTamperControls,closureTamperControls,hash,read,json,rec,write,git,gitBytes,walk,inventory,tarMembers,checkPackage,runtimeClosure,verifyRecord} from './common.mjs';

if(fs.existsSync(path.join(root,E,'independent-review.json'))||fs.existsSync(path.join(root,E,'review-failure.json')))throw new Error('NO_REVIEW_RERUN');
try{
  assert.ok(!fs.existsSync(path.join(root,E,'failure.json')));const execution=json(E+'/execution.json');assert.equal(execution.result,'PASS');assert.equal(execution.mandatoryExecutionComplete,true);assert.equal(execution.candidateBinding,C3TB);assert.equal(execution.productionCandidate,C3T);
  const protocol=json(T+'/protocol.json');assert.deepEqual(execution.stages.map(r=>r.name),protocol.executionStages);assert.ok(execution.stages.every(r=>r.result==='PASS'));
  assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['diff','--name-only']),'');assert.equal(git(['diff','--cached','--name-only']),'');
  const source=json(E+'/source-inventory.json'),candidate=json(E+'/candidate.json'),archive=read(candidate.path);assert.equal(hash(archive),candidate.sha256);assert.equal(candidate.canonicalInventorySha256,PACKAGE_IDENTITY);const members=tarMembers(archive);assert.equal(members.length,89);for(const member of members)assert.ok(member.data.equals(read(S+'/'+member.path.slice(8))),member.path);
  assert.deepEqual(inventory(path.join(root,S)),source.members);checkPackage(path.join(root,S));assert.deepEqual(runtimeClosure(path.join(root,S)),json(E+'/runtime-closure.json'));
  const assemblies=json(E+'/assemblies.json');assert.equal(assemblies.assemblies.length,2);assert.equal(assemblies.archiveBytesEqual,true);for(const row of assemblies.assemblies){assert.equal(hash(fs.readFileSync(row.archive.path)),candidate.sha256);assert.deepEqual(inventory(path.join(row.root,'package')),source.members);}
  const offline=json(E+'/offline-install.json');assert.deepEqual(inventory(offline.packageDirectory),source.members);assert.deepEqual(json(E+'/installed-inventory-before.json').members,source.members);assert.deepEqual(json(E+'/installed-inventory-after.json').members,source.members);
  const deadline=json(E+'/deadline-binding.json');assert.equal(deadline.result,'PASS');assert.equal(deadline.authority,'PROSPECTIVE_HELPER_BOUND@1.0.0');assert.equal(deadline.authorityStatus,'ADOPTED_PROSPECTIVELY');assert.equal(deadline.authorityAppliesFromCandidate,'C3T');verifyRecord(deadline.authorityRecord.declared);assert.deepEqual(rec(deadline.authorityRecord.declared.path),deadline.authorityRecord.observed);const authority=json(deadline.authorityRecord.declared.path);assert.equal(authority.historical.H,'NOT_ESTABLISHED');assert.equal(authority.valueMs,8000);assert.deepEqual(authority.relation,{equality:'TIMEOUT',success:'elapsedMs < 8000',timeout:'elapsedMs >= 8000'});assert.deepEqual(authority.limits,{aggregateHelperActiveMs:20000,apiMs:10000,cleanupMs:2000,cliAdmissionMs:30000,helperMs:8000,workerMs:10000});assert.deepEqual(deadline.current,{helperMs:8000,aggregateHelperActiveMs:20000,cliAdmissionMs:30000,apiMs:10000,workerMs:10000,cleanupMs:2000});assert.equal(deadline.strictEqualityFailsClosed,true);assert.equal(deadline.noOtherResourceValueChanged,true);
  for(const p of ['generated-definitions','distribution','contract','sbom','runtime-closure','supply','document-validation','offline-install','installed-smoke','installed-persistence','source-independence','historical-preservation'])assert.equal(json(E+'/'+p+'.json').result,'PASS',p);
  const tamper=json(E+'/tamper-controls.json');assert.equal(tamper.result,'PASS');assert.equal(tamper.productionMutated,false);assert.equal(tamper.freshArtifactBoundCount,16);assert.deepEqual(tamper.requiredFreshMap,artifactTamperControls);assert.deepEqual(tamper.freshArtifactBoundControls.map(r=>r.name),artifactTamperControls);assert.ok(tamper.freshArtifactBoundControls.every(r=>r.result==='PASS'));assert.equal(tamper.reusedClosureCount,6);assert.deepEqual(tamper.reusedClosureControls.map(r=>r.name),closureTamperControls);assert.ok(tamper.reusedClosureControls.every(r=>r.result==='PASS'&&r.classification==='REUSED_AFTER_EXACT_DEPENDENCY_PROOF'));
  const advisory=json(E+'/advisory-handoff.json');assert.equal(advisory.handling,'PASS');assert.equal(advisory.result,'OPEN_ADVISORY_HANDOFF');assert.equal(advisory.riskAccepted,false);assert.equal(advisory.finalReleaseAuthorization,false);
  const historical=json(E+'/historical-preservation.json');assert.equal(historical.commit,HISTORICAL_3B);assert.equal(historical.historicalEvidenceRewritten,false);assert.equal(git(['cat-file','-t',HISTORICAL_3B]),'commit');assert.equal(gitBytes(HISTORICAL_3B,'repositories/cca-conformance/evidence/mo1307/phase3b-c3rb-cert/final-validation.json').length>0,true);
  const frozenTooling=json(E+'/campaign-start.json').tooling;assert.deepEqual(walk(path.join(root,T)).map(p=>T+'/'+p).sort(),frozenTooling.map(r=>r.path).sort(),'Frozen campaign tool path set changed');for(const row of frozenTooling)assert.deepEqual(rec(row.path),row,'Frozen campaign tool changed');
  const changed=[...git(['diff','--name-only',C3TB]).split(/\r?\n/u),...git(['ls-files','--others','--exclude-standard']).split(/\r?\n/u)].filter(Boolean);for(const p of changed)assert.ok(p.startsWith(E+'/')||p.startsWith(T+'/')||p===D,p);
  git(['diff','--check']);git(['diff','--cached','--check']);
  const reviewedEvidence=walk(path.join(root,E)).map(p=>rec(E+'/'+p));
  write(E+'/independent-review.json',{kind:'MO1307Phase3BR2IndependentEvidenceReview',version:'1.0.0',candidateBinding:C3TB,productionCandidate:C3T,reviewedUtc:new Date().toISOString(),result:'PASS',execution:rec(E+'/execution.json'),candidate:rec(E+'/candidate.json'),archiveMembers:89,sourceAndInstalledInventoryMembers:89,deterministicAssemblies:2,freshArtifactBoundControls:16,reusedClosureControls:6,deadlineBinding:rec(E+'/deadline-binding.json'),reviewedEvidence,reportedMismatches:0,blockingFindings:[],advisory:'OPEN_ADVISORY_HANDOFF',riskAccepted:false,productionChanges:0,sealDisposition:'Acceptance pending single seal execution'});
  console.log(JSON.stringify({result:'PASS',candidateBinding:C3TB,archiveSha256:candidate.sha256,members:89,blockingFindings:0,pending:'single seal execution'}));
}catch(error){write(E+'/review-failure.json',{result:'PHASE3BR2_FAILED_INCOMPLETE',candidateBinding:C3TB,stage:'independent-review',stoppedUtc:new Date().toISOString(),error:{name:error.name,message:error.message,stack:error.stack},retry:false,acceptedHandoff:false});console.error(error.stack);process.exitCode=1;}
