// Final read-only checks followed by a single acyclic immutable Phase 3BR2 evidence closure.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {root,E,S,T,D,C3TB,C3T,C3RB,HISTORICAL_3B,PRODUCTION_TREE,PACKAGE_IDENTITY,BRANCH,hash,read,json,rec,write,git,gitBytes,walk,inventory,tarMembers,checkPackage,artifactTamperControls,closureTamperControls} from './common.mjs';

function verify(row){const bytes=read(row.path);assert.equal(bytes.length,row.byteLength,row.path);assert.equal(hash(bytes),row.sha256.replace(/^sha256:/u,''),row.path);}
if(fs.existsSync(path.join(root,E,'failure.json'))||fs.existsSync(path.join(root,E,'review-failure.json'))||fs.existsSync(path.join(root,E,'failure-final.json'))||fs.existsSync(path.join(root,E,'seal-start.json')))throw new Error('NO_SEAL_AFTER_FAILURE_OR_RETRY');
fs.writeFileSync(path.join(root,E,'seal-start.json'),JSON.stringify({startedUtc:new Date().toISOString(),attempt:1})+'\n',{flag:'wx'});
try{
  assert.ok(!fs.existsSync(path.join(root,E,'certification-receipt.json')));
  assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['branch','--show-current']),BRANCH);assert.equal(git(['rev-parse','HEAD^']),C3T);assert.equal(git(['rev-parse',C3T+':'+S]),PRODUCTION_TREE);assert.equal(git(['diff','--name-only']),'');assert.equal(git(['diff','--cached','--name-only']),'');assert.equal(git(['diff',C3TB,'--',S]),'');
  const execution=json(E+'/execution.json'),review=json(E+'/independent-review.json'),protocol=json(T+'/protocol.json');assert.equal(execution.result,'PASS');assert.equal(execution.mandatoryExecutionComplete,true);assert.equal(review.result,'PASS');assert.deepEqual(execution.stages.map(r=>r.name),protocol.executionStages);assert.ok(execution.stages.every(r=>r.result==='PASS'));
  verify(review.execution);verify(review.candidate);verify(review.deadlineBinding);for(const row of review.reviewedEvidence)verify(row);assert.deepEqual(walk(path.join(root,E)).map(p=>E+'/'+p).sort(),[...review.reviewedEvidence.map(r=>r.path),E+'/independent-review.json',E+'/seal-start.json'].sort(),'Reviewed evidence path set changed');
  const preChanged=git(['ls-files','--others','--exclude-standard']).split(/\r?\n/u).filter(Boolean);for(const p of preChanged)assert.ok(p.startsWith(E+'/')||p.startsWith(T+'/')||p===D,p);
  assert.equal(git(['rev-parse','HEAD']),C3TB);assert.equal(git(['branch','--show-current']),BRANCH);assert.equal(git(['rev-parse','HEAD^']),C3T);assert.equal(git(['rev-parse',C3T+':'+S]),PRODUCTION_TREE);assert.equal(git(['diff',C3TB,'--',S]),'');assert.ok((Date.now()-Date.parse(execution.startedUtc))/60000<90,'Frozen campaign budget exceeded');
  const frozenTooling=json(E+'/campaign-start.json').tooling;assert.deepEqual(walk(path.join(root,T)).map(p=>T+'/'+p).sort(),frozenTooling.map(r=>r.path).sort(),'Frozen campaign tool path set changed');for(const row of frozenTooling)verify(row);
  const candidate=json(E+'/candidate.json'),source=json(E+'/source-inventory.json');verify(candidate);assert.equal(candidate.candidateBinding,C3TB);assert.equal(candidate.productionCandidate,C3T);assert.equal(candidate.productionTree,PRODUCTION_TREE);assert.equal(candidate.canonicalInventorySha256,PACKAGE_IDENTITY);assert.deepEqual(inventory(path.join(root,S)),source.members);checkPackage(path.join(root,S));
  const archive=read(candidate.path),members=tarMembers(archive);assert.equal(members.length,89);for(const member of members)assert.ok(member.data.equals(read(S+'/'+member.path.slice(8))),member.path);
  for(const row of json(E+'/assemblies.json').assemblies){verify(row.archive);assert.ok(read(row.archive.path).equals(archive));assert.deepEqual(inventory(path.join(row.root,'package')),source.members);}
  assert.deepEqual(inventory(json(E+'/offline-install.json').packageDirectory),source.members);
  const historical=json(E+'/historical-before.json');assert.equal(git(['cat-file','-t',HISTORICAL_3B]),'commit');assert.equal(git(['rev-parse',HISTORICAL_3B+'^{tree}']),historical.tree);for(const row of historical.files){const bytes=gitBytes(HISTORICAL_3B,row.path);assert.equal(bytes.length,row.byteLength);assert.equal(hash(bytes),row.sha256,row.path);assert.equal(git(['rev-parse',HISTORICAL_3B+':'+row.path]),row.gitBlob,row.path);}
  for(const p of ['candidate-binding','source-inventory','generated-definitions','deadline-binding','supply','document-validation','distribution','contract','sbom','runtime-closure','assemblies','offline-install','installed-smoke','installed-persistence','source-independence','tamper-controls','historical-preservation','independent-review'])assert.equal(json(E+'/'+p+'.json').result,'PASS',p);
  const tamper=json(E+'/tamper-controls.json');assert.equal(tamper.result,'PASS');assert.equal(tamper.productionMutated,false);assert.equal(tamper.freshArtifactBoundCount,16);assert.deepEqual(tamper.requiredFreshMap,artifactTamperControls);assert.deepEqual(tamper.freshArtifactBoundControls.map(r=>r.name),artifactTamperControls);assert.ok(tamper.freshArtifactBoundControls.every(r=>r.result==='PASS'));assert.equal(tamper.reusedClosureCount,6);assert.deepEqual(tamper.reusedClosureControls.map(r=>r.name),closureTamperControls);assert.ok(tamper.reusedClosureControls.every(r=>r.result==='PASS'&&r.classification==='REUSED_AFTER_EXACT_DEPENDENCY_PROOF'));
  const advisory=json(E+'/advisory-handoff.json');assert.equal(advisory.handling,'PASS');assert.equal(advisory.result,'OPEN_ADVISORY_HANDOFF');assert.equal(advisory.riskAccepted,false);assert.equal(advisory.humanRiskAcceptance,false);assert.equal(advisory.finalReleaseAuthorization,false);
  const changed=[...git(['diff','--name-only',C3TB]).split(/\r?\n/u),...git(['ls-files','--others','--exclude-standard']).split(/\r?\n/u)].filter(Boolean);for(const p of changed)assert.ok(p.startsWith(E+'/')||p.startsWith(T+'/')||p===D,p);git(['diff','--check']);git(['diff','--cached','--check']);
  const handoffText=advisory.phase3DHandoff;
  write(E+'/phase3d-handoff.json',{kind:'MO1307Phase3BR2Phase3DHandoff',version:'1.0.0',result:'READY_FOR_SEPARATE_PHASE3D_INTEGRATION',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,authority:'PROSPECTIVE_HELPER_BOUND@1.0.0',H:'NOT_ESTABLISHED',archive:candidate,receiptPath:E+'/certification-receipt.json',refreshCommit:null,refreshCommitRule:'The certification commit is a direct child whose sole parent is C3TB, with subject conformance(memoryos-1.3): certify fresh MO-1307 C3TB Phase 3BR2 artifacts; its future hash is supplied externally after creation.',requiresIndependentExactC3TBReceipts:['PHASE3AR2','PHASE3CR2'],historicalPhase3B:{commit:HISTORICAL_3B,candidate:C3RB,preserved:true,promoted:false},qualifications:advisory.qualifications,openAdvisory:'Node July 2026 HTTP/2 identity/applicability remains NOT ESTABLISHED',humanRiskAcceptance:false,releaseAuthorization:false,phase3DPerformed:false,noPush:true,noTag:true,instruction:handoffText});
  const report=[
    '# MO-1307 Phase 3BR2 C3TB package, artifact and supply refresh','',
    '**PHASE3BR2_ACCEPTED only when `final-validation.json` is PASS and no failure record exists.** This receipt certifies the scoped package/artifact/supply refresh; it does not authorize release or perform Phase 3D.','',
    '| Item | Result |','|---|---|',
    `| Candidate binding | C3TB ${C3TB} |`,`| Production | C3T ${C3T}; tree ${PRODUCTION_TREE} |`,
    '| Authority | PROSPECTIVE_HELPER_BOUND@1.0.0; H = NOT_ESTABLISHED |',
    `| Worktree / branch | ${root.replaceAll('\\','/')} / ${BRANCH} |`,
    '| Package / contract | memoryos-readiness@0.1.0 / memoryos.readiness@1.0.0 |',
    `| Archive | ${candidate.byteLength} bytes; SHA-256 ${candidate.sha256}; SHA-512 ${candidate.sha512} |`,
    '| Inventory | PASS: 89 regular members, exact C3T/C3TB source/archive bytes; no missing, extra, unsafe or nonregular members |',
    '| Reproducibility | PASS: two fresh roots and empty npm caches produced byte-identical complete archives; historical C3RB archive was comparison-only and differs |',
    '| Offline installation | PASS: fresh explicit root/cache; npm --offline --ignore-scripts --no-audit --no-fund; no fallback |',
    '| Installed equality | PASS: all 89 files equal archive/source before and after smoke; isolated helper mutation restored and all files rechecked |',
    '| Runtime closure | PASS: installed/package-local modules, fixed worker/helper, permitted Node built-ins, zero external production dependencies/hooks |',
    '| Generated definitions | PASS: fresh shadow generation of definitions, 52 schemas, runtime constants/schema tables, contract, SBOM and manifest equals all 89 candidate bytes |',
    '| Deadline binding | PASS: helper 8000 (< succeeds, >= times out); aggregate 20000; CLI 30000; API/worker 10000; post-terminal cleanup 2000; no other limit changed |',
    `| Distribution manifest | PASS: 88 rows; SHA-256 ${json(E+'/distribution.json').identity.sha256} |`,
    `| SPDX SBOM | PASS: 1 package, 87 files, 88 relationships; SHA-256 ${json(E+'/sbom.json').identity.sha256}; full pinned SPDX 2.3 validation |`,
    '| Tamper controls | PASS: exactly 16 fresh artifact-bound controls; six separate closure controls reused only after exact dependency proof |',
    '| Provenance | PASS: exact C3TB/C3T/tree/source/archive/tooling/evidence bindings; future commit self-reference omitted |',
    '| Licenses / notices | QUALIFICATION: first-party UNLICENSED/NOASSERTION; CC0-1.0 is SPDX metadata only; no product/publication grant |',
    '| Node advisory | OPEN ADVISORY HANDOFF; exact HTTP/2 CVE identity, current census and final applicability NOT ESTABLISHED; no risk acceptance |',
    '| Provider/platform scope | Provider accounts/hosted execution and non-Windows certification are outside Phase 3BR2; no conclusion is inferred |',
    `| Historical Phase 3B | Preserved unchanged at ${HISTORICAL_3B}; C3RB-only and not promoted |`,
    '| Human authority | No human risk acceptance and no release authorization |',
    '| Repository action | Only Phase 3BR2 evidence, tooling and this report; no production changes, push, tag, Phase 3A, Phase 3C or Phase 3D |','',
    'The selected refresh did not reuse any package, archive, assembly, installation, generated-definition, runtime-closure, or required artifact-tamper result. Historical schema fixture outcomes were not promoted because definitions/constants changed. Provider boundary, licensing, and the still-open advisory disposition were retained only after the recorded dependency checks.','',
    `Receipt: [certification-receipt.json](../${E}/certification-receipt.json). Provenance: [provenance.json](../${E}/provenance.json). Seal: [evidence-seal.json](../${E}/evidence-seal.json). Final validation: [final-validation.json](../${E}/final-validation.json).`,'',
    '## Exact Phase 3D handoff','',handoffText,''
  ];write(D,report.join('\n'));
  const evidence=walk(path.join(root,E)).map(p=>rec(E+'/'+p));
  write(E+'/provenance.json',{kind:'MO1307Phase3BR2Provenance',version:'1.0.0',result:'PASS',createdUtc:new Date().toISOString(),candidateBinding:C3TB,candidateBindingTree:git(['rev-parse',C3TB+'^{tree}']),productionCandidate:C3T,productionRootTree:git(['rev-parse',C3T+'^{tree}']),productionTree:PRODUCTION_TREE,authority:{identity:'PROSPECTIVE_HELPER_BOUND@1.0.0',H:'NOT_ESTABLISHED',record:rec('repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/authority.json'),refreshMap:rec('repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-candidate/phase3b-refresh-map.json')},historicalPhase3B:{commit:HISTORICAL_3B,candidate:C3RB,preserved:true,finalValidation:{commit:HISTORICAL_3B,...rec('repositories/cca-conformance/evidence/mo1307/phase3b-c3rb-cert/final-validation.json',gitBytes(HISTORICAL_3B,'repositories/cca-conformance/evidence/mo1307/phase3b-c3rb-cert/final-validation.json'))}},archive:candidate,sourceInventory:rec(E+'/source-inventory.json'),generatedDefinitions:rec(E+'/generated-definitions.json'),deadlineBinding:rec(E+'/deadline-binding.json'),distribution:rec(S+'/distribution-manifest.json'),sbom:rec(S+'/sbom.spdx.json'),helper:rec(S+'/helpers/windows-inspect.ps1'),tamper:rec(E+'/tamper-controls.json'),report:rec(D),phase3DHandoff:rec(E+'/phase3d-handoff.json'),tooling:walk(path.join(root,T)).map(p=>rec(T+'/'+p)),evidence,noFutureCommitSelfReference:true,cyclePolicy:'Provenance binds prior evidence/report/handoff; receipt binds provenance; seal binds both; final validation binds seal. None binds itself or a future commit.'});
  const checks=Object.fromEntries(protocol.mandatoryInventory.map(name=>[name,'PASS']));
  write(E+'/certification-receipt.json',{kind:'MO1307Phase3BR2CertificationReceipt',version:'1.0.0',createdUtc:new Date().toISOString(),result:'PHASE3BR2_ACCEPTED',acceptanceRequires:'final-validation.json PASS with unchanged evidence seal',candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,authority:'PROSPECTIVE_HELPER_BOUND@1.0.0',H:'NOT_ESTABLISHED',worktree:root,branch:BRANCH,candidate,checks,qualification:advisory.qualifications,openAdvisoryHandoff:rec(E+'/advisory-handoff.json'),notApplicable:advisory.notApplicable,notEstablished:['H replacement characterization','Exact Node July 2026 HTTP/2 CVE subset','Final MO-1307 advisory applicability','Current internet-wide advisory census','Release authorization'],riskAccepted:false,humanRiskAcceptance:false,historicalPhase3B:{commit:HISTORICAL_3B,candidate:C3RB,preserved:true,promoted:false},productionChanges:0,provenance:rec(E+'/provenance.json'),phase3DHandoff:rec(E+'/phase3d-handoff.json'),phase3DPerformed:false,phase3AR2Performed:false,phase3CR2Performed:false,noPush:true,noTag:true,noFutureCommitSelfReference:true,certificationCommit:null,certificationCommitRule:'Exactly one parent, C3TB; future hash intentionally external.'});
  const provenance=read(E+'/provenance.json'),bad=Buffer.from(provenance);bad[Math.floor(bad.length/2)]^=1;assert.throws(()=>assert.equal(hash(bad),hash(provenance)));assert.throws(()=>verify({...candidate,sha256:'0'.repeat(64)}));
  verify(review.execution);verify(review.candidate);verify(review.deadlineBinding);for(const row of review.reviewedEvidence)verify(row);assert.deepEqual(walk(path.join(root,T)).map(p=>T+'/'+p).sort(),frozenTooling.map(r=>r.path).sort(),'Frozen campaign tool path set changed before seal');for(const row of frozenTooling)verify(row);
  const sealed=[...walk(path.join(root,E)).map(p=>rec(E+'/'+p)),...walk(path.join(root,T)).map(p=>rec(T+'/'+p)),rec(D)];write(E+'/evidence-seal.json',{kind:'MO1307Phase3BR2EvidenceSeal',version:'1.0.0',candidateBinding:C3TB,productionCandidate:C3T,members:sealed});for(const row of sealed)verify(row);
  write(E+'/final-validation.json',{result:'PASS',status:'PHASE3BR2_ACCEPTED',checkedUtc:new Date().toISOString(),candidateBinding:C3TB,productionCandidate:C3T,productionTree:PRODUCTION_TREE,archive:candidate,seal:rec(E+'/evidence-seal.json'),receipt:rec(E+'/certification-receipt.json'),provenance:rec(E+'/provenance.json'),phase3DHandoff:rec(E+'/phase3d-handoff.json'),sealedFiles:sealed.length,finalProvenanceByteTamperDetected:true,finalArchiveBindingTamperDetected:true,mandatoryInventoryComplete:true,productionChanges:0,historicalPreservation:'PASS',firstMandatoryFailure:null,campaignAttempts:1,qualification:advisory.qualifications,advisory:'OPEN_ADVISORY_HANDOFF',riskAccepted:false,releaseAuthorized:false,phase3DPerformed:false,commitParentCountMustBe:1,commitParentMustBe:C3TB,commitSubjectMustBe:'conformance(memoryos-1.3): certify fresh MO-1307 C3TB Phase 3BR2 artifacts',futureCommitHashExternal:true});
  console.log(JSON.stringify({result:'PHASE3BR2_ACCEPTED',candidateBinding:C3TB,productionCandidate:C3T,archive:candidate,receipt:rec(E+'/certification-receipt.json'),finalValidation:rec(E+'/final-validation.json'),sealedFiles:sealed.length}));
}catch(error){write(E+'/failure-final.json',{result:'PHASE3BR2_FAILED_INCOMPLETE',candidateBinding:C3TB,productionCandidate:C3T,stage:'final-seal',stoppedUtc:new Date().toISOString(),message:error.message,stack:error.stack,retry:false,acceptedHandoff:false});console.error(error.stack);process.exitCode=1;}
