import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {gunzipSync,gzipSync} from 'node:zlib';
import {packageFiles,checkPackage,canonical} from '../mo1307-phase1/package.mjs';
import {root,E,S,C3TB,C3T,cache,hash,read,json,rec,write,inventory,tarMembers,validateTarRows,artifactTamperControls,closureTamperControls} from './common.mjs';
const controls=[];function rejects(name,fn,expected){let error;try{fn();}catch(e){error=e;}assert.ok(error,'Control did not reject: '+name);if(expected)assert.match(error.message,expected);controls.push({name,result:'PASS',observedError:error.message.slice(0,450),expectedRejection:expected?.source??'Mismatch required'});write(E+'/tamper-progress.json',{controls});}
const candidate=json(E+'/candidate.json'),bytes=read(candidate.path);const members=tarMembers(bytes);assert.equal(hash(bytes),candidate.sha256);
let changed=Buffer.from(bytes);changed[Math.floor(changed.length/2)]^=1;rejects('archive-byte-tamper',()=>assert.equal(hash(changed),candidate.sha256));
const baseRows=members.map(({data,...r})=>({...r}));rejects('missing-member',()=>validateTarRows(baseRows.slice(1)),/MEMBER_COUNT/);rejects('unexpected-member',()=>validateTarRows([...baseRows,{...baseRows[0],path:'package/extra.txt'}]),/MEMBER_COUNT/);rejects('unsafe-tar-path',()=>validateTarRows(baseRows.map((r,i)=>i? r:{...r,path:'package/../escape'})),/UNSAFE_PATH/);rejects('nonregular-tar-member',()=>validateTarRows(baseRows.map((r,i)=>i?r:{...r,type:'2'})),/NONREGULAR/);rejects('duplicate-member',()=>validateTarRows(baseRows.map((r,i)=>i===1?{...r,path:baseRows[0].path}:r)),/DUPLICATE/);
const tar=gunzipSync(bytes);let off=0;while(!tar.subarray(off,off+512).every(x=>x===0)){const h=tar.subarray(off,off+512),size=parseInt(h.subarray(124,136).toString().split('\0')[0].trim(),8);off+=512+Math.ceil(size/512)*512;}rejects('missing-tar-terminator',()=>tarMembers(gzipSync(tar.subarray(0,off))),/TAR_TERMINATOR/);rejects('trailing-tar-data',()=>tarMembers(gzipSync(Buffer.concat([tar,Buffer.from([1])]))));
function copyCase(name){const p=path.join(cache,'tamper',name);assert.ok(!fs.existsSync(p));fs.mkdirSync(p,{recursive:true});for(const member of packageFiles){const dest=path.join(p,member);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,read(S+'/'+member));}return p;}
function mutate(name,member,edit,expected){const p=copyCase(name),target=path.join(p,member),prior=fs.readFileSync(target);fs.writeFileSync(target,edit(prior));rejects(name,()=>checkPackage(p),expected);controls.at(-1).target=member;controls.at(-1).before=rec(member,prior);controls.at(-1).after=rec(member,fs.readFileSync(target));}
const editJSON=fn=>b=>{const o=JSON.parse(b);fn(o);return canonical(o)+'\n';};
mutate('helper-tamper','helpers/windows-inspect.ps1',b=>Buffer.concat([b,Buffer.from('\n# engineered mutation\n')]),/SBOM_BINDING/);
mutate('distribution-hash-tamper','distribution-manifest.json',editJSON(o=>o.files[0].sha256='sha256:'+'0'.repeat(64)),/DISTRIBUTION_BINDING/);
mutate('distribution-length-tamper','distribution-manifest.json',editJSON(o=>o.files[0].byteLength++),/DISTRIBUTION_BINDING/);
mutate('sbom-checksum-tamper','sbom.spdx.json',editJSON(o=>o.files[0].checksums[0].checksumValue='0'.repeat(40)),/SBOM_BINDING/);
const extra=copyCase('extra-package-file');fs.writeFileSync(path.join(extra,'extra.txt'),'x');rejects('extra-package-file',()=>checkPackage(extra),/UNEXPECTED_MEMBER/);
const absent=copyCase('missing-package-file');fs.unlinkSync(path.join(absent,'helpers/windows-inspect.ps1'));rejects('missing-package-file',()=>checkPackage(absent),/MISSING_MEMBER/);
const provenanceInput={candidateBinding:C3TB,productionCandidate:C3T,archive:rec(candidate.path),distribution:rec(S+'/distribution-manifest.json'),sbom:rec(S+'/sbom.spdx.json'),helper:rec(S+'/helpers/windows-inspect.ps1')};write(E+'/provenance-input.json',provenanceInput);const provenanceBytes=read(E+'/provenance-input.json'),anchor=hash(provenanceBytes),mutated=Buffer.from(provenanceBytes),index=mutated.indexOf('119e68bd');assert.ok(index>=0);mutated[index]^=1;rejects('provenance-byte-tamper',()=>assert.equal(hash(mutated),anchor));
const installed=json(E+'/offline-install.json').packageDirectory,helper=path.join(installed,'helpers/windows-inspect.ps1'),original=fs.readFileSync(helper),before=inventory(installed);let mutatedIdentity;
try{fs.writeFileSync(helper,Buffer.concat([original,Buffer.from('\n# installed negative control\n')]));mutatedIdentity=rec('helpers/windows-inspect.ps1',fs.readFileSync(helper));rejects('installed-helper-mutation',()=>assert.deepEqual(inventory(installed),before));}finally{fs.writeFileSync(helper,original);}
assert.deepEqual(inventory(installed),before);assert.deepEqual(inventory(installed),json(E+'/installed-inventory-after.json').members);checkPackage(installed);controls.at(-1).mutation=mutatedIdentity;controls.at(-1).restored=rec('helpers/windows-inspect.ps1',fs.readFileSync(helper));controls.at(-1).all89MembersRestored=true;
assert.deepEqual(controls.map(r=>r.name),artifactTamperControls);const reusedClosureControls=json(E+'/supply.json').closureNegativeControls.controls;assert.equal(reusedClosureControls.length,6);assert.deepEqual(reusedClosureControls.map(r=>r.name),closureTamperControls);assert.ok(reusedClosureControls.every(r=>r.result==='PASS'&&r.classification==='REUSED_AFTER_EXACT_DEPENDENCY_PROOF'));
write(E+'/tamper-controls.json',{result:'PASS',freshArtifactBoundCount:controls.length,freshArtifactBoundControls:controls,reusedClosureCount:reusedClosureControls.length,reusedClosureControls,requiredFreshMap:artifactTamperControls,productionMutated:false,installedNegativeAfterPersistence:'Explicit isolated mutation restored; full inventory rechecked.',provenanceInput:rec(E+'/provenance-input.json'),finalProvenanceTamper:'Final seal additionally checks tamper against actual final provenance bytes.'});
for(const a of json(E+'/assemblies.json').assemblies)tarMembers(fs.readFileSync(a.archive.path));console.log(JSON.stringify({result:'PASS',freshArtifactBoundControls:controls.length,reusedClosureControls:reusedClosureControls.length}));
