// Direct consumer-side protocol controls bound to fresh unmodified native output.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {canonicalBytes} from '../../../memoryos-readiness/src/canonical.mjs';
import {decodeHelperRequest,decodeHelperResponse,createHelperSequence} from '../../../memoryos-readiness/src/helper-protocol.mjs';
const ev='repositories/cca-conformance/evidence/mo1307/phase3cr2-c3tb',base=ev+'/equivalence/attempt1/ordinary';
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex'),pin=p=>{const b=fs.readFileSync(p);return{path:p,byteLength:b.length,sha256:hash(b)}};
const raw=fs.readFileSync(base+'/candidate.stdout.bin'),q=decodeHelperRequest(fs.readFileSync(base+'/request.bin')),body=JSON.parse(raw.subarray(4));
const frame=v=>{const b=canonicalBytes(v),h=Buffer.alloc(4);h.writeUInt32BE(b.length);return Buffer.concat([h,b])};const rows=[];
const caseIds=['response-wrong-version','response-wrong-session','response-wrong-sequence','response-wrong-operation','response-unknown-field','response-malformed-base64','response-noncanonical-base64','response-truncated-frame','response-extra-frame','response-trailing-bytes','cross-session-response-replay','sequence-entry-bypass','native-frame-control'];
const caseAccounting=caseIds.map((id,index)=>({ordinal:index+1,id,status:'NOT_RUN'}));
fs.writeFileSync(ev+'/protocol-case-plan.json',JSON.stringify({kind:'MO1307Phase3CR2ProtocolCasePlan',candidate:'119e68bdcf0ffc906b4ca03a912aadcb25908346',cases:structuredClone(caseAccounting)},null,2)+'\n',{flag:'wx'});
const ordinal=()=>String(rows.length+1).padStart(2,'0');
const safeName=id=>id.replaceAll(/[^A-Za-z0-9._-]/g,'_');
const progress=()=>fs.writeFileSync(ev+`/protocol-progress-${String(rows.length).padStart(2,'0')}-${safeName(rows.at(-1).id)}.json`,JSON.stringify({status:'INCOMPLETE',rows,caseAccounting},null,2)+'\n',{flag:'wx'});
const active=(id,expected)=>{const accounting=caseAccounting.find(row=>row.id===id);assert.ok(accounting);assert.equal(accounting.status,'NOT_RUN');accounting.status='RUNNING';fs.writeFileSync(ev+`/protocol-active-${ordinal()}-${safeName(id)}.json`,JSON.stringify({id,expected})+'\n',{flag:'wx'});return accounting;};
function reject(name,fn){const accounting=active(name,{code:'MO1307_INPUT'});let caught;try{fn()}catch(e){caught=e}fs.writeFileSync(ev+`/protocol-observation-${ordinal()}-${safeName(name)}.json`,JSON.stringify({id:name,expected:'MO1307_INPUT',actual:caught?.code??null})+'\n',{flag:'wx'});try{assert.ok(caught,name+' must reject');assert.equal(caught.code,'MO1307_INPUT',name);}catch(error){rows.push({id:name,negative:true,expected:{code:'MO1307_INPUT'},actual:{code:caught?.code??null},result:'FAIL',error:{message:error.message,stack:error.stack}});accounting.status='FAIL';progress();throw error;}rows.push({id:name,scope:'CURRENT_JS_CONSUMER_OF_FRESH_NATIVE_FRAME',negative:true,code:caught.code,result:'PASS'});accounting.status='PASS';progress();}
let failure=null;
try{
for(const [name,mutate] of [
 ['response-wrong-version',b=>b.version='1.0.0'],['response-wrong-session',b=>b.session='c'.repeat(64)],['response-wrong-sequence',b=>b.sequence=2],['response-wrong-operation',b=>b.operation='CHECK_OUTPUT'],['response-unknown-field',b=>b.script='C3R_SECRET_SENTINEL'],['response-malformed-base64',b=>b.files[0].bytes=['%%%']],['response-noncanonical-base64',b=>b.files[0].bytes=[b.files[0].bytes.join('').replace(/=$/,'')]]]){const b=structuredClone(body);mutate(b);reject(name,()=>decodeHelperResponse(frame(b),q));}
for(const [name,b] of [['response-truncated-frame',raw.subarray(0,raw.length-1)],['response-extra-frame',Buffer.concat([raw,raw])],['response-trailing-bytes',Buffer.concat([raw,Buffer.from('x')])]])reject(name,()=>decodeHelperResponse(b,q));
const other=JSON.parse(JSON.stringify(q));other.session='d'.repeat(64);reject('cross-session-response-replay',()=>decodeHelperResponse(raw,other));
reject('sequence-entry-bypass',()=>createHelperSequence('evaluate',{session:q.session}).begin(q));
const nativeAccounting=active('native-frame-control',{status:'OK'});let original;try{original=decodeHelperResponse(raw,q);assert.equal(original.status,'OK');}catch(error){rows.push({id:'native-frame-control',negative:false,expected:{status:'OK'},actual:{status:original?.status??null,code:error.code??null},result:'FAIL',error:{message:error.message,stack:error.stack}});nativeAccounting.status='FAIL';progress();throw error;}rows.push({id:'native-frame-control',scope:'CURRENT_JS_CONSUMER_OF_FRESH_NATIVE_FRAME',negative:false,result:'PASS'});nativeAccounting.status='PASS';progress();
}catch(error){failure={code:error.code??null,message:error.message,stack:error.stack};const running=caseAccounting.find(row=>row.status==='RUNNING');if(running)running.status='FAIL';}
fs.writeFileSync(ev+'/protocol-subset.json',JSON.stringify({kind:'MO1307Phase3CR2RefreshConsumerProtocol',candidate:'119e68bdcf0ffc906b4ca03a912aadcb25908346',result:failure?'FAIL':'PASS',failure,sources:[pin('repositories/cca-conformance/tools/mo1307-phase3cr2-c3tb/protocol.mjs'),pin('repositories/memoryos-readiness/src/helper-protocol.mjs'),pin('repositories/memoryos-readiness/src/canonical.mjs'),pin(base+'/request.bin'),pin(base+'/candidate.stdout.bin')],rows,caseAccounting,count:rows.length,negativeCount:rows.filter(r=>r.negative).length,scope:'Native malformed requests are separately exercised in the equivalence campaign. Cross-session ownership is enforced by the JS consumer/sequence; each one-shot helper echoes a syntactically valid session and does not own cross-process session history.'},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({result:failure?'FAIL':'PASS',count:rows.length}));process.exitCode=failure?1:0;
