"""Render the requested bounded-task report from actual local evidence."""
from pathlib import Path
import argparse,ctypes,json,subprocess
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'.cache/mo1305-bounded-r6';CONF=ROOT/'repositories/cca-conformance';V='75cee55784c590bab52feaf8f2214e4d1b9e657f';C='c2e3835b852fd966046ac9e984538fdcaf8b26bf'
def read(p,default=None):return json.loads(p.read_bytes()) if p.exists() else default
parser=argparse.ArgumentParser();parser.add_argument('--state',choices=['COMPLETE','BLOCKED','DECOMPOSITION_REQUIRED','RESOURCE_CORRECTION_REQUIRES_AUTHORIZATION'],required=True);args=parser.parse_args()
def git(*a):return subprocess.check_output([r'C:/Program Files/Git/cmd/git.exe',*a],cwd=ROOT,text=True).strip()
inv=read(CONF/'mo1305-conformance-inventory.json',{});limits=read(ROOT/'repositories/memoryos-rest/contracts/limits.json');resource=read(OUT/'resource-validation.json',{});stress=read(OUT/'stress-validation.json',{});final=read(ROOT/'.cache/mo1305-resource-review/final-validation/results.json',{});post=read(ROOT/'.cache/mo1305-resource-review/post-b1-r6/results.json',{})
start=read(OUT/'task-start.json');counter=ctypes.c_longlong();ctypes.windll.kernel32.QueryPerformanceCounter(ctypes.byref(counter));elapsed=start['startupAllowanceSeconds']+(counter.value-start['timestamp'])/start['frequency']
status=git('status','--porcelain=v1','--untracked-files=all');(OUT/'final-git-status.txt').write_text(status+'\n' if status else '',encoding='utf-8');I1=inv.get('implementations',{}).get('I1');B1=git('rev-parse','HEAD') if git('log','-1','--format=%s')=='conformance(memoryos-1.3): bind MO-1305 phase 1 foundation' else None
if args.state=='COMPLETE':assert post.get('state')=='PASS' and not status and I1 and B1 and git('rev-parse',I1+'^')==V and git('rev-parse',B1+'^')==I1 and elapsed<=5400
selection=read(CONF/'fixtures/mo1305-phase1/bounded/resource-selection.json');progress=read(CONF/'evidence/mo1305-phase1-r6/resource/progress.json',{});functional=read(CONF/'evidence/mo1305-phase1-r6/functional/progress.json',{});adverse=read(CONF/'evidence/mo1305-phase1-r6/adverse-functional/index.json',{});confirmation=read(CONF/'evidence/mo1305-phase1-r6/stress-confirmation/index.json',{})
diagnostic=read(OUT/'retained-r6-diagnostic.json',{});maxima=read(CONF/'evidence/mo1305-phase1-aux/maxima.json',resource.get('maxima',diagnostic.get('maxima',{})))
def metric(name):return str(maxima.get(name,'NOT_FINAL'))+(' (diagnostic only; incomplete R6)' if not resource and name in maxima else '')
def step(name):return next((r['state'] for r in final.get('records',[]) if r['id']==name),'NOT_EXECUTED')
labels=['Baseline','Historical attempt preservation','Old verification methodology','Why it was excessive','New verification methodology','Task runtime policy','Deadline correction','Correction commit V','V parent','Functional case count','Functional result','Resource vector count','Resource vector identities','Resource selection rationale','Cold samples per vector','Warm samples per vector','Any extended vector and reason','Total repeated resource samples','Maximum semantic duration','Final semantic deadline','Maximum young generation','Maximum old generation','Maximum external','Maximum parent attributable','Final memory budgets','Final wire limits','Boundary test result','Adverse functional result','Stress vector count','Stress durations','Stress result','Real HTTP/TLS','Node fetch','curl','raw TLS','Semantic parity','PASS','FAIL','COULD_NOT_EVALUATE','Offline install','OpenAPI','SBOM/notices','Supply-chain review','Required regressions','Workspace verification','Phase 1 inventory','Phase 1 receipts','I1 hash','I1 parent','B1 hash','B1 parent','Post-B1 result','Total task wall-clock duration','Confirmation task stayed within 90-minute budget','Final Git status','No push confirmation','No tag confirmation','Ubuntu/Linux state','VM state','Cross-platform parity state','Phase 2 state','Phase 3 state','Exact next task']
values=[
f'Workspace {ROOT}; baseline main at {C}, docs(memoryos-1.3): correct MO-1305 platform policy.',
'R1 FAIL, R4 FAIL, R5 FAIL / RESOURCE_GATE unchanged (157 artifact hashes verified). R6 FAIL preserved separately: 299 output files, 20,884,954 bytes; 329 repository inputs and eight external identities reverified. No reused IDs or historical samples used for final derivation.',
'105 x (30 cold + 100 warm) = 13,650 ordinary samples; 20 x 3 x at least 60 seconds adverse.',
'Universal repetition duplicated deterministic coverage and made iteration expensive; coverage and resource pressure have distinct purposes.',
'Layer A complete functional; B selected resource characterization; C exact boundaries; D adverse functional plus selected sustained stress.',
'Conservative monotonic elapsed accounting including 120-second startup allowance; target 60 minutes, hard limit 90 minutes.',
'Preliminary absolute semantic ceiling 30,000 -> 60,000 ms; R5 witness 9,281,479 us -> 37,200 ms. Final formula remains ceil100ms(max(1000ms,4*maximum selected valid operationMs)).',V,C,
'105 catalog cases; '+str(len(functional.get('completed',[])))+'/105 final-candidate executions',functional.get('state','NOT_EXECUTED'),str(selection['count']),', '.join(v['id'] for v in selection['vectors']),
'Historical peaks plus closed-schema/semantic structure; exact sizes, dimensions, omission rationale and supporting observations frozen before repetitions in resource-selection.json.',
'10 default','20 default',json.dumps(resource.get('variance',[]),separators=(',',':')) if resource.get('extensionRequired') else 'None triggered in completed validation.' if resource else 'None executed. Campaign failed before the full variance assessment; no observations were discarded.',
str(resource.get('samples',diagnostic.get('totalSuccessfulObservations','INCOMPLETE')))+(' successful retained observations plus one failed HTTP observation; target 450 successful. 11/15 vectors complete, one partial, three unstarted; R6 FAIL.' if not resource else ''),metric('operationUs')+' us',str(limits['measured']['operationMs'])+' ms FINAL' if limits['state']=='FINAL' else 'NOT_DERIVED; ceiling is preliminary.',
metric('workerYoungBytes')+' bytes',metric('workerOldBytes')+' bytes',metric('workerExternalBytes')+' bytes',f"Absolute heap {metric('parentHeapBytes')}; external {metric('parentExternalBytes')}; RSS {metric('processRssBytes')} bytes. Attributable deltas: heap {metric('parentHeapDeltaBytes')}; external {metric('parentExternalDeltaBytes')} bytes.",
json.dumps({k:v for k,v in limits['measured'].items() if k.endswith('MiB')}) if limits['state']=='FINAL' else 'NOT_DERIVED',json.dumps(limits['measured']['operations']) if limits['state']=='FINAL' else 'NOT_DERIVED',
f"Installed {step('final-boundaries')}; component matrix {step('boundary-matrix')}",adverse.get('state','NOT_EXECUTED')+'; '+str(len(adverse.get('completed',[])))+'/20',str(stress.get('scenarios',9))+' selected; '+('executed' if stress else 'not executed'),'2 x 10 seconds per selected vector; no default 60-second soak.',
f"Measured {stress.get('state','NOT_EXECUTED')}; final confirmation {confirmation.get('state','NOT_EXECUTED')}",step('integration') if final else 'Final gate NOT_EXECUTED; R6 used real TCP/TLS/HTTP for all 342 retained successful observations and the failed request.',step('clients'),step('clients'),step('adversarial'),step('integration'),step('integration'),step('integration'),step('integration'),step('install') if final else 'Preliminary R6 archive isolated offline install PASS; final derived candidate not created.',step('units') if final else 'Preliminary projection built; final consistency gate NOT_EXECUTED.', 'Final identity bound' if inv else 'Preliminary SBOM/notices retained; final candidate binding pending', '2026-09-24 scoped primary-source recheck retained; no exhaustive vulnerability-free claim.',step('regressions'),step('workspace') if final else 'PASS at blocked checkpoint; final-candidate gate not reached.',inv.get('state','NOT_CREATED'),str(sum(len(r) for r in inv.get('receipts',{}).values()))+' separate receipts' if inv else 'NOT_CREATED',I1 or 'ABSENT',V if I1 else 'N/A',B1 or 'ABSENT',I1 if B1 else 'N/A',post.get('state','NOT_EXECUTED'),f'{elapsed:.1f} seconds ({elapsed/60:.1f} minutes), conservative including startup allowance.',str(elapsed<=5400),('DIRTY: '+str(len(status.splitlines()))+' paths preserved; full output in .cache/mo1305-bounded-r6/final-git-status.txt. No reset or clean performed.') if status else 'CLEAN','No push performed.','No tag created; memoryos-1.3-mo1305 absent.' if not git('tag','--list','memoryos-1.3-mo1305') else 'UNEXPECTED_TAG','NOT_REQUIRED','NOT_REQUIRED','NOT_REQUIRED','PENDING','PENDING','MEMORYOS 1.3 MO-1305 REST GATEWAY PHASE 2 IMPLEMENTATION'+('' if args.state=='COMPLETE' else ' (gated; Phase 1 incomplete)')]
assert len(labels)==len(values)==63
state='MO-1305 PHASE 1 COMPLETE\nREADY FOR PHASE 2' if args.state=='COMPLETE' else 'MO-1305 RESOURCE CORRECTION REQUIRES AUTHORIZATION' if args.state=='RESOURCE_CORRECTION_REQUIRES_AUTHORIZATION' else 'MO-1305 PHASE 1 '+args.state.replace('_',' ')
text='# MO-1305 bounded Phase 1 report\n\n'+state+'\n\n'+('Coverage results below refer to the final derived candidate unless explicitly identified as preliminary or diagnostic. No final derived candidate was produced.\n\n' if args.state!='COMPLETE' and limits['state']!='FINAL' else '')+'\n'.join(f'{i}. **{name}:** {value}' for i,(name,value) in enumerate(zip(labels,values),1))+'\n'
if args.state=='BLOCKED' and diagnostic:
 text+='\nR6 stopped at maximum-permitted-headers, warm index 2: HTTP 504 instead of 200. Failed operation duration 60,443,611 us; round trip 60,496,188 us. A separate native capture took 56.2543816 seconds. Cause remains undetermined; the bounded System-event query returned no entries. The largest retained successful duration, 14,008,944 us, would require 56,100 ms, within the 60,000 ms ceiling, but is diagnostic only. The failed HTTP observation cannot authorize a ceiling correction.\n\nRemaining: resolve the HTTP timeout/host-stall cause; plan a new bounded, separately identified campaign without discarding R6; complete selected characterization, derive limits, final 105-case coverage, 20 adverse cases, selected stress, boundaries, clients/security/parity, final install/package gates, required regressions, receipts/inventory, I1/B1 and post-B1 checks. No finalization tooling is represented as validated by the incomplete run. Phase 2 remains gated.\n'
(OUT/'final-report.md').write_text(text,encoding='utf-8',newline='\n');(OUT/'final-report.json').write_text(json.dumps({'state':state,'elapsedSecondsConservative':elapsed,'items':[{'number':i,'label':name,'value':value} for i,(name,value) in enumerate(zip(labels,values),1)]},sort_keys=True,separators=(',',':')),encoding='utf-8')
print(json.dumps({'state':state,'report':str(OUT/'final-report.md'),'elapsedMinutesConservative':round(elapsed/60,2),'head':git('rev-parse','HEAD')}))
