/** Run once after the completed I1 commit; creates only B1 inventory/evidence. */
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {resolve} from 'node:path';
import {root,git,revisions,readCanonical,reference,artifact,sha,validateInventory} from './mo1305-evidence.mjs';import {J} from '../../memoryos-rest/src/serialization.mjs';
assert.equal(git('status','--porcelain'),'','I1_MUST_BE_CLEAN');const I1=git('rev-parse','HEAD');assert.equal(git('show','-s','--format=%s',I1),'feat(memoryos-1.3): implement MO-1305 REST Gateway foundation');assert.equal(git('rev-parse',I1+'^'),revisions.V);
const inventoryPath='repositories/cca-conformance/mo1305-conformance-inventory.json',inventory=readCanonical(resolve(root,inventoryPath));validateInventory(inventory);
function committed(path){return execFileSync('C:/Program Files/Git/cmd/git.exe',['show',I1+':'+path],{cwd:root,windowsHide:true,maxBuffer:67108864,env:{...process.env,GIT_OPTIONAL_LOCKS:'0'}});}
const treePath='repositories/cca-conformance/evidence/mo1305-phase1-aux/final-source-tree.json',tree=readCanonical(resolve(root,treePath));assert.equal(tree.sha256,inventory.package.sourceTreeSha256);
for(const row of tree.files){artifact(row);const bytes=committed(row.path);assert.equal(bytes.length,row.byteLength);assert.equal(sha(bytes),row.sha256,'I1_EXECUTED_BYTE_MISMATCH '+row.path);}
const references=[...Object.values(inventory.receipts).flat(),...Object.values(inventory.contracts),inventory.runtime.closure,inventory.package.distributionManifest,...['lockfile','manifest','sbom','notices','review'].map(k=>inventory.dependencies[k])];
for(const row of references){artifact(row);assert.equal(sha(committed(row.path)),row.sha256,'I1_ARTIFACT_MISMATCH '+row.path);}
const harnessRows=new Map();for(const row of Object.values(inventory.receipts).flat()){const receipt=readCanonical(resolve(root,row.path));assert.equal(sha(committed(receipt.harness.path)),receipt.harness.sha256);const harness=readCanonical(resolve(root,receipt.harness.path));for(const file of harness.files)harnessRows.set(file.path,file);}for(const row of harnessRows.values()){artifact(row);assert.equal(sha(committed(row.path)),row.sha256,'I1_HARNESS_MISMATCH '+row.path);}
 const directory=resolve(root,'repositories/cca-conformance/evidence/mo1305-phase1-binding');mkdirSync(directory);
const previous=committed(inventoryPath);assert.equal(previous.toString('utf8'),J(inventory));writeFileSync(resolve(directory,'i1-inventory.json'),previous);
const binding={kind:'MemoryOSRESTPhase1Binding',version:'1.0.0',state:'PASS',authorityRevision:revisions.A,contractFreezeRevision:revisions.F,platformCorrectionRevision:revisions.C,verificationCorrectionRevision:revisions.V,implementationRevision:I1,implementationParent:revisions.V,implementationInventory:reference('repositories/cca-conformance/evidence/mo1305-phase1-binding/i1-inventory.json'),sourceTree:reference(treePath),sourceFilesVerified:tree.files.length,harnessFilesVerified:harnessRows.size,archive:inventory.package.archive,distributionManifest:inventory.package.distributionManifest,receipts:Object.values(inventory.receipts).flat().sort((a,b)=>a.path<b.path?-1:1),phase2:'PENDING',phase3:'PENDING',windowsCertification:'PENDING',ubuntu:'NOT_REQUIRED',linux:'NOT_REQUIRED',vm:'NOT_REQUIRED',crossPlatformParity:'NOT_REQUIRED',finalBinding:'PENDING',releaseTag:'ABSENT'};
writeFileSync(resolve(directory,'binding.json'),J(binding));inventory.state='PHASE1_BOUND';inventory.implementations.I1=I1;writeFileSync(resolve(root,inventoryPath),J(inventory));
console.log(JSON.stringify({state:'B1_DATA_PREPARED',implementationRevision:I1,filesVerified:tree.files.length,ownBindingHash:null}));
