"""Create review records; never edits preserved evidence or product bytes."""
from audit import *
from rule import *
e=Evidence();mechanical=e.run();save(OUT/'mechanical-review.json',mechanical)
authority_paths=['docs/mo1306-contract-freeze-1.md','docs/mo1306-provider-neutral-cicd.md','docs/mo1306-contract-freeze-1-process-correction.md','docs/mo1306-phase3-cli-dispatch-correction.md','docs/mo1306-phase3-helper-deadline-correction.md','docs/mo1305-contract-freeze-1-verification-methodology-correction.md','docs/mo1305-host-interruption-validity.md','repositories/cca-conformance/mo1306-phase3-correction-binding.json','repositories/cca-conformance/mo1306-phase3-helper-correction-binding.json','repositories/cca-conformance/mo1306-phase3-helper-correction-inventory.json','repositories/memoryos-ci/src/publication.mjs','repositories/memoryos-ci/src/verification.mjs','repositories/memoryos-ci/src/filesystem.mjs','repositories/memoryos-ci/distribution-manifest.json']
authority_refs=[ref(ROOT/p) for p in authority_paths]
for r in authority_refs:need(check_ref(r)==git('show',BASE+':'+r['path']),'AUTHORITY_CHANGED')
review={'decision':'A','justified':True,'alternatives':{'B':'Existing freeze does not expressly permit unresolved-history/current-candidate distinction; criterion 10 remains historically NOT_ESTABLISHED.','C':'A blanket waiver would weaken certification; this closed candidate-specific rule excludes semantic, security, integrity, deterministic defect and recurrent-final failures.','D':'No missing eligibility fact found after complete original validator and independent raw-byte review; final certification evidence is explicitly still pending.'},'basis':'Freeze sections 9/11/22/23, roadmap section 13 and bounded methodology principles support prospective preservation plus fresh candidate certification without retroactive causal classification.','absenceOfDefectClaim':'No deterministic current product/harness defect established in reviewed evidence; not a proof of universal absence.','historicalNonrecoverability':'Available evidence cannot reconstruct telemetry not captured by that execution. Further successful executions cannot supply the old raw error. Future new evidence is not ruled out.','permission':'PROSPECTIVE_FROM_M3_ONLY','historicalCriterion10':'NOT_ESTABLISHED','currentCertification':'PENDING_FINAL_WITNESS','productionChanges':False,'authorities':authority_refs,'evidence':ref(OUT/'mechanical-review.json')}
save(OUT/'authority-review.json',review)
failure=e.local(HIST+'failure-review.json');mr=ref(OUT/'mechanical-review.json');ar=ref(OUT/'authority-review.json');dr=ref(DOC);pres=ref(OUT/'preservation.json')
bases=[
 ('All five original indexes and 758 members retained byte-for-byte; original blocked classifications unchanged.',[pres]),
 ('Historical manifest and marker absent; two-file bundle independently rejected; publication NONE/17.',[failure,mr]),
 ('Partial result is INPUT_ERROR/11, semantic null; no fabricated semantic or completion success.',[failure,mr]),
 ('Source/retained investigation establishes no deterministic current defect. Earlier known helper defect was separately corrected by C3C; no waiver.',[ar,mr]),
 ('Faithfulness, original harness and observer audits establish no deterministic defect affecting current certification; no claim of universal absence.',[e.local('phase3a-publication-diagnostic/harness-audit.json'),mr]),
 ('Exact graph, archive identity, 94 installed members and runtime pinned to C3CB.',[ar,mr]),
 ('All three prebounded faithful runs complete with expected operational error, identical candidate and no omitted failure.',[mr,e.local('phase3a-publication-diagnostic/reproduction-summary.json')]),
 ('Enhanced run binds raw I/O, helper/process/directory observations; succeeds without artificial injection.',[mr,e.local('phase3a-environment-capture/capture-summary.json')]),
 ('Four bundles valid; 94 installed members unchanged; no remaining owned process or descriptor.',[mr]),
 ('All current diagnostics reviewed; no later contrary current observation. Named original unresolved observation stays visible and is the only exception subject.',[mr,ar]),
 ('Missing-input acquisition is expected operational INPUT_ERROR; failure localized to publication before manifest completion; no normative result.',[failure,ar]),
 ('Permission limited to exact C3CB current candidate; no historical PASS, global reliability or release certification.',[dr,ar]),
 ('Eligibility disclosure records unresolved history; later actual final sidecar is mandatory and remains pending.',[dr,ar]),
 ('Historical underlying error remains UNRESOLVED; no Windows, Defender, harness or product causal attribution.',[failure,ar]),
 ('Any final failure stops; publication recurrence invalidates exception; no retry or campaign reset.',[dr]),
 ('Existing finite diagnostic protocol/all attempts checked; no further diagnostics required. Exactly one final witness prospectively authorized.',[e.local('phase3a-publication-diagnostic/recurrence-decision.json'),e.local('phase3a-environment-capture/observation-plan.json'),dr]),
 ('Independent raw bundle/event checks and required mutation controls reject unsafe acceptance; production never executed by M3.',[mr,dr]),
 ('Eight accepted groups and entire retained dependency evidence bound; same 94-member closure. Reuse requires unchanged dependency/environment scope at final acceptance.',[e.local('phase3a-final/native-summary.json'),mr,dr])]
candidate={'productionAuthority':BASE,'distributionSha256':DIST,'identityVerified':True}
matrix=[{'id':i,'status':'PASS','basis':b,'evidence':refs} for i,(b,refs) in zip(CONDITIONS,bases)]
case={'kind':'MemoryOSUnresolvedObservationEligibility','version':'1.0.0','candidate':candidate,'history':HISTORY,'matrix':matrix,'ineligible':dict.fromkeys(FORBIDDEN,False),'evidenceClasses':dict.fromkeys(['structural','faithful','enhanced','identity','negativeControls','failClosed'],'ESTABLISHED'),'plan':{'faithfulIds':FAITHFUL,'enhancedId':ENHANCED,'finalWitnessLimit':1,'finalAttemptsConsumed':0,'finalCampaign':'C3CB-missing-input-final-under-M3','predeclaredBoundedDiagnosticsVerified':True,'allDiagnosticAttemptsRetained':True,'retryUntilPass':False},'claims':{'scope':'CURRENT_CANDIDATE_ONLY','currentCandidateCertified':False,'historicalCauseEstablished':False,'reliabilityProbability':None,'disposition':'ELIGIBLE_FOR_ONE_FINAL_WITNESS','finalGate':'PENDING','hostedCertified':False},'disclosure':{'history':HISTORY,'candidate':candidate,'faithfulWitnessIds':FAITHFUL,'enhancedObservationId':ENHANCED,'failClosedEvidence':matrix[1]['evidence'],'methodologyRevision':'REQUIRED_ACTUAL_M3_COMMIT_IN_LATER_FINAL_RECEIPT','recurrenceRule':RECURRENCE,'receiptState':'ELIGIBILITY_ONLY_FINAL_RECEIPT_REQUIRED'},'reuse':{'groups':GROUPS,'exactDependenciesRequired':True,'rerunUnaffectedGroups':False,'retainedEvidenceBound':True}}
eligible(case);save(OUT/'eligibility.json',case)
save(AUTHORITY,{'kind':'MemoryOSUnresolvedObservationMethodology','version':'1.0.0','correction':'B','commitRole':'M3','expectedParent':BASE,'productionGraph':GRAPH,'decision':'A','permissionTiming':'PROSPECTIVE_AFTER_M3_POST_VALIDATION','conditions':CONDITIONS,'ineligible':FORBIDDEN,'evidenceClasses':list(case['evidenceClasses']),'caseThreshold':{'faithful':3,'enhanced':1,'final':1,'universalRepetitionCount':False,'rationale':'Faithful attempts address bounded reproducibility; enhanced capture addresses observability; final witness supplies still-missing accepted certification evidence. No statistical claim.'},'recurrenceRule':RECURRENCE,'authorities':authority_refs,'historicalPreservation':ref(OUT/'preservation.json'),'authorityReview':ref(OUT/'authority-review.json'),'mechanicalReview':ref(OUT/'mechanical-review.json'),'eligibility':ref(OUT/'eligibility.json'),'documentation':dr,'productExecutions':0,'productionChanges':False,'nativeCertified':False,'hostedCertified':False,'selfReference':False})
print(json.dumps({'decision':'A','eligible':True,'matrix':{'PASS':18,'FAIL':0,'NOT_ESTABLISHED':0}}))
