#pragma once

#include <compare>
#include <cstdint>
#include <string>

namespace cca::core {

/// A value representation of a semantic version used across CCA components.
struct SemanticVersion final {
    std::uint32_t major;
    std::uint32_t minor;
    std::uint32_t patch;
    std::string prerelease;
    std::string build_metadata;

    [[nodiscard]] std::string to_string() const;

    auto operator<=>(const SemanticVersion&) const = default;
};

/// Returns the version generated by the workspace build configuration.
[[nodiscard]] SemanticVersion current_version();

} // namespace cca::core
