import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {canonical,checkPackage,packageFiles} from '../mo1307-phase1/package.mjs';
const root=fileURLToPath(new URL('../../../../',import.meta.url));
const rel='repositories/cca-conformance/evidence/mo1307/phase3ar2-final';
const toolRel='repositories/cca-conformance/tools/mo1307-phase3ar2-final';
const E=path.join(root,rel),cache=path.join(root,'.cache/phase3ar2-final'),source=path.join(root,'repositories/memoryos-readiness');
const installed=path.join(cache,'install/node_modules/memoryos-readiness');
const C3VB='17fa84efe46d30e6f4be85fd2427485677a222a3',C3V='98b766f9218b209f52251147213839b9775f6da3',BASE='4208ea48fa8f6acb8f39b21010aac9d29a8086d6';
const integration='PROSPECTIVE_HELPER_AGGREGATE_BOUND@2.0.0',helperAuthority='PROSPECTIVE_HELPER_BOUND@2.0.0',productionTree='b9dabf54572e06c96bb5e48c4e20671f2cc24053';
const prospectiveRel='repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate';
const failedBGateRel='repositories/cca-conformance/evidence/mo1307/phase3ar2-final-b-gate';
const failedBGateToolRel='repositories/cca-conformance/tools/mo1307-phase3ar2-final-b-gate';
const correctionRel='repositories/cca-conformance/evidence/mo1307/phase3ar2-final-topology-observer-correction';
const correctionToolRel='repositories/cca-conformance/tools/mo1307-phase3ar2-final-topology-observer-correction';
const bGateRel='repositories/cca-conformance/evidence/mo1307/phase3ar2-final-corrected-b-gate';
const bGateToolRel='repositories/cca-conformance/tools/mo1307-phase3ar2-final-corrected-b-gate';
const authorizationPath='C:/Users/melsa/.codex/attachments/68250150-4313-40fa-84f8-a172c13d7516/Pasted text.txt';
const authorizationSha256='sha256:7604a8ea29a2423fd99a49a34724158e2ae9121531ea8e256f85bf44610f71a6';
const fixedLimits={helperWholeLifecycleMs:9000,helperSuccess:'elapsedMs < 9000',helperTimeout:'elapsedMs >= 9000',aggregateHelperActiveMs:28000,aggregateSuccess:'helperActiveMs < 28000',aggregateTimeout:'helperActiveMs >= 28000',cliMs:30000,apiWorkerMs:10000,cleanupMs:2000};
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const record=p=>{const b=fs.readFileSync(p);return {path:path.relative(root,p).replaceAll('\\','/'),byteLength:b.length,sha256:hash(b)};};
const walk=(base,prefix='')=>fs.readdirSync(path.join(base,prefix),{withFileTypes:true}).sort((a,b)=>a.name<b.name?-1:1).flatMap(e=>{const p=prefix?prefix+'/'+e.name:e.name,full=path.join(base,p),s=fs.lstatSync(full);assert.ok(!s.isSymbolicLink(),full);return s.isDirectory()?walk(base,p):[{...record(full),path:p}];});
const put=(name,bytes)=>{const p=path.join(E,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,bytes,{flag:'wx'});return record(p);};
const write=(name,obj)=>put(name,Buffer.from(JSON.stringify(obj,null,2)+'\n'));
const env={SystemRoot:'C:\\Windows',WINDIR:'C:\\Windows'};
function git(...args){const r=spawnSync('C:/Program Files/Git/cmd/git.exe',['-c','safe.directory=C:/Users/melsa/Documents/Codex/3ar2',...args],{cwd:root,windowsHide:true,encoding:null,maxBuffer:128*1024*1024});assert.ifError(r.error);assert.equal(r.status,0,r.stderr.toString());return r.stdout;}
assert.equal(path.resolve(root).toLowerCase(),'c:\\users\\melsa\\documents\\codex\\3ar2');
assert.equal(process.platform,'win32');assert.equal(process.arch,'x64');assert.equal(process.version,'v24.21.0');
assert.equal(hash(fs.readFileSync(process.execPath)),'sha256:ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32');
assert.equal(git('rev-parse','HEAD').toString().trim(),C3VB);
assert.equal(git('rev-parse',C3VB+'^{tree}').toString().trim(),'68e5c57dce89cb0819b1a94ae18d4e6b9b54713d');
assert.equal(git('rev-parse',C3VB+':repositories/memoryos-readiness').toString().trim(),productionTree);
assert.equal(git('show','-s','--format=%P',C3VB).toString().trim(),C3V);
assert.equal(git('show','-s','--format=%s',C3VB).toString().trim(),'conformance(memoryos-1.3): bind final aggregate-budget candidate');
assert.equal(git('show','-s','--format=%P',C3V).toString().trim(),BASE);
assert.equal(git('show','-s','--format=%s',C3V).toString().trim(),'fix(memoryos-1.3): adopt final 28000-ms prospective helper aggregate bound');
assert.equal(git('rev-parse',C3V+'^{tree}').toString().trim(),'7635bd204fce185253e06d10e9cca625618c1921');
assert.equal(git('rev-parse',C3V+':repositories/memoryos-readiness').toString().trim(),productionTree);
assert.equal(git('branch','--show-current').toString().trim(),'codex/mo1307-phase3ar2-c3ub');
assert.equal(git('diff','--name-only','--','repositories/memoryos-readiness').toString(),'');
assert.equal(git('diff','--cached','--name-only').toString(),'');
const statusLines=git('status','--porcelain=v1','--untracked-files=all').toString().trim().split(/\r?\n/).filter(Boolean);
const allowedUntracked=[toolRel,rel,failedBGateToolRel,failedBGateRel,correctionToolRel,correctionRel,bGateToolRel,bGateRel];
assert.ok(statusLines.every(line=>allowedUntracked.some(prefix=>line.startsWith('?? '+prefix+'/'))),'Unexpected working-tree path before preparation');
assert.equal(fs.existsSync(cache),false,'Fresh explicit installation/cache must not exist');
assert.equal(fs.existsSync(E),false,'Fresh Phase 3AR2 evidence namespace must not exist');
assert.equal(fs.existsSync(path.join(root,'docs/mo1307-phase3ar2-final.md')),false,'Fresh Phase 3AR2 report path must not exist');
const authorizationBytes=fs.readFileSync(authorizationPath);assert.equal(authorizationBytes.length,5967);assert.equal(hash(authorizationBytes),authorizationSha256);
const failedBGatePath=path.join(root,failedBGateRel,'gate-receipt.json'),failedBGate=JSON.parse(fs.readFileSync(failedBGatePath,'utf8'));
assert.deepEqual(record(failedBGatePath),{path:failedBGateRel+'/gate-receipt.json',byteLength:7140,sha256:'sha256:6236c0976bb13bc6a8705962b2729f1dbb581917f2556c85dc372ff0d42d34b5'});
assert.equal(failedBGate.result,'FAIL');assert.equal(failedBGate.outcome,'PHASE3AR2_CONCRETE_BLOCKER');assert.equal(failedBGate.semanticInvocations,1);assert.equal(failedBGate.noRetry,true);assert.equal(failedBGate.fullCertificationStarted,false);
const correctionRoot=path.join(root,correctionRel),correctionReceiptPath=path.join(correctionRoot,'receipt.json'),correctionReceipt=JSON.parse(fs.readFileSync(correctionReceiptPath,'utf8'));
assert.deepEqual(fs.readdirSync(correctionRoot).sort(),['authorization.txt','case-results.json','cases.json','receipt.json','source-bindings.json','zero-execution-proof.json']);
assert.equal(correctionReceipt.kind,'MO1307Phase3AR2TopologyObserverSyntheticValidationReceipt');assert.equal(correctionReceipt.version,'1.0.0');assert.equal(correctionReceipt.result,'PASS');assert.equal(correctionReceipt.candidate,C3VB);assert.equal(correctionReceipt.productionCommit,C3V);assert.equal(correctionReceipt.productionTree,productionTree);assert.equal(correctionReceipt.policy,'MO1307_TOPOLOGY_IDENTITY_POLICY@1.0.0');
assert.deepEqual(fs.readFileSync(path.join(correctionRoot,'authorization.txt')),authorizationBytes);assert.deepEqual(correctionReceipt.bindings.authorization,record(path.join(correctionRoot,'authorization.txt')));
assert.deepEqual(correctionReceipt.cases.required,['A','B','C','D','E','F','G']);assert.equal(correctionReceipt.cases.passed,7);assert.equal(correctionReceipt.cases.allRequiredCasesPassed,true);assert.deepEqual(correctionReceipt.cases.acceptedExactly,['B','F']);assert.deepEqual(correctionReceipt.cases.failedClosedExactly,['A','C','D','E','G']);
assert.deepEqual({semanticProductInvocations:correctionReceipt.execution.semanticProductInvocations,productRuns:correctionReceipt.execution.productRuns,helperRuns:correctionReceipt.execution.helperRuns,nativeObserverRuns:correctionReceipt.execution.nativeObserverRuns},{semanticProductInvocations:0,productRuns:0,helperRuns:0,nativeObserverRuns:0});
const zeroProof=JSON.parse(fs.readFileSync(path.join(correctionRoot,'zero-execution-proof.json'),'utf8'));assert.deepEqual(zeroProof.forbiddenAuditEvents,[]);assert.equal(zeroProof.semanticProductInvocations,0);assert.equal(zeroProof.productRuns,0);assert.equal(zeroProof.helperRuns,0);assert.equal(zeroProof.nativeObserverRuns,0);
const correctionSourcesPath=path.join(correctionRoot,'source-bindings.json'),correctionSources=JSON.parse(fs.readFileSync(correctionSourcesPath,'utf8'));
assert.deepEqual(correctionReceipt.bindings.sources,record(correctionSourcesPath));assert.deepEqual(correctionSources.correctedObserver,record(path.join(root,correctionToolRel,'runtime-controls-observer.py')));assert.deepEqual(correctionSources.policy,record(path.join(root,correctionToolRel,'topology_identity_policy.py')));
assert.deepEqual(correctionSources.historicalFailedGate,record(failedBGatePath));assert.deepEqual(correctionSources.historicalFailedTopology,record(path.join(root,failedBGateRel,'topology/receipt.json')));
for(const [name,binding] of [['runtime-controls-observer.py',correctionSources.correctedObserver],['topology_identity_policy.py',correctionSources.policy]])for(const namespace of [toolRel,bGateToolRel]){const actual=record(path.join(root,namespace,name));assert.equal(actual.byteLength,binding.byteLength);assert.equal(actual.sha256,binding.sha256);}
const bGatePath=path.join(root,bGateRel,'gate-receipt.json'),bGate=JSON.parse(fs.readFileSync(bGatePath,'utf8'));
assert.equal(bGate.kind,'MO1307Phase3AR2FinalCorrectedPreCertificationBGateReceipt');assert.equal(bGate.result,'PASS');assert.equal(bGate.outcome,'PRE_CERTIFICATION_B_GATE_PASS');assert.equal(bGate.candidate,C3VB);assert.equal(bGate.productionCommit,C3V);assert.equal(bGate.productionTree,productionTree);assert.deepEqual(bGate.authorities,[helperAuthority,integration]);assert.equal(bGate.certification,false);assert.equal(bGate.noRetry,true);assert.equal(bGate.semanticInvocations,1);assert.equal(bGate.fullCertificationStarted,false);assert.deepEqual(bGate.limits,fixedLimits);
assert.equal(bGate.priorFailedGatePreserved,true);assert.equal(bGate.syntheticCorrectionValidated,true);assert.equal(bGate.replacementExecutions,0);assert.equal(bGate.diagnosticsRun,0);assert.deepEqual(bGate.requirements,{expectedReadiness:'READY',noHelperTimeout:true,allHelpersAccepted:true,scheduledTopologyRssWitness:'PASS',zeroUnresolvedTopologyIdentities:true,correctedObserverPolicy:true,cleanupSettlement:'PASS'});
assert.ok(bGate.details.helperUsedMs<28000);assert.ok(bGate.details.productLifecycleElapsedMs<30000);assert.equal(bGate.details.cleanupConfirmed,true);assert.equal(bGate.details.publication.phase,'COMMITTED');
const bGateTopology=JSON.parse(fs.readFileSync(path.resolve(root,bGate.bindings.topology.path),'utf8'));assert.equal(bGateTopology.result,'PASS');assert.equal(bGateTopology.driverExit,0);assert.equal(bGateTopology.observerExit,0);assert.equal(bGateTopology.expectedHelpers,9);assert.equal(bGateTopology.helperPairs.length,9);assert.equal(bGateTopology.allKnownObjectsSignaled,true);assert.equal(bGateTopology.identityPolicy,'MO1307_TOPOLOGY_IDENTITY_POLICY@1.0.0');assert.equal(bGateTopology.identityOrSnapshotFailures,0);assert.equal(bGateTopology.unresolvedIdentityFailures,0);assert.equal(bGateTopology.acceptedIdentityProofsConsistent,true);assert.deepEqual(bGateTopology.observationErrors,[]);assert.ok(bGateTopology.maximumProductRoles<=3);assert.ok(bGateTopology.maximumHelpers<=1);assert.ok(bGateTopology.maximumHelperConsoles<=1);assert.ok(bGateTopology.peakSampledProductWorkingSetBytes<=536870912);
const bindingRecords=[];(function collect(value){if(Array.isArray(value))for(const item of value)collect(item);else if(value&&typeof value==='object'){if(typeof value.path==='string'&&typeof value.sha256==='string'&&Number.isInteger(value.byteLength))bindingRecords.push(value);for(const item of Object.values(value))collect(item);}})(bGate.bindings);
assert.ok(bindingRecords.some(value=>value.path===correctionRel+'/receipt.json'&&value.sha256===record(correctionReceiptPath).sha256),'Corrected B receipt must bind synthetic correction receipt');assert.ok(bindingRecords.some(value=>value.path===failedBGateRel+'/gate-receipt.json'&&value.sha256===record(failedBGatePath).sha256),'Corrected B receipt must preserve failed B receipt');
const startedAt=new Date().toISOString(),hardStopAt=new Date(Date.now()+180*60000).toISOString();
write('pre-execution-gate.json',{result:'PASS',verifiedAt:startedAt,worktree:path.resolve(root),branch:'codex/mo1307-phase3ar2-c3ub',HEAD:C3VB,rootTree:'68e5c57dce89cb0819b1a94ae18d4e6b9b54713d',productionCommit:C3V,productionTree,initialGateObservedBeforeTooling:{worktree:'C:\\Users\\melsa\\Documents\\Codex\\3ar2',branch:'codex/mo1307-phase3ar2-c3ub',HEAD:C3VB,workingTree:'TRACKED_CLEAN_WITH_PRESERVED_FAILED_B_CORRECTION_EVIDENCE_CORRECTED_B_PASS_AND_FRESH_UNTRACKED_AO_HARNESS'},currentTrackedDiff:'CLEAN',currentIndex:'CLEAN',currentUntrackedScope:'Preserved failed B, topology correction, corrected one-shot B, and fresh final A-O tool/evidence namespaces only',statusLines,observerCorrection:record(correctionReceiptPath),preCertificationBGate:record(bGatePath),preservedFailedBGate:record(failedBGatePath)});
write('campaign-config.json',{generation:'PHASE3AR2_C3VB_FINAL_FRESH_FULL_INSTALLED_RUNTIME_20261001',startedAt,hardStopAt,engineeringGuardMinutes:180,productDeadlineAuthorities:[helperAuthority,integration],candidate:C3VB,productionCommit:C3V,productionTree,H:'NOT_ESTABLISHED',nodeExecutable:process.execPath,helperSuccess:'elapsedMs < 9000',helperTimeout:'elapsedMs >= 9000',aggregateAccepted:'helperActiveMs < 28000',aggregateTimeout:'helperActiveMs >= 28000',observerIdentityPolicy:'MO1307_TOPOLOGY_IDENTITY_POLICY@1.0.0',observerCorrection:record(correctionReceiptPath),preCertificationBGate:record(bGatePath),preservedFailedPreCertificationBGate:record(failedBGatePath),noRetry:true});
put('generation-authorization.txt',authorizationBytes);
const production=walk(source);
assert.deepEqual(production.map(x=>x.path),[...packageFiles].sort());
for(const row of production)assert.equal(row.sha256,hash(git('show',C3VB+':repositories/memoryos-readiness/'+row.path)),row.path);
const sourceCheck=checkPackage(source);
const packageIdentity=hash(Buffer.from(canonical(production)+'\n'));
assert.equal(production.length,89);assert.equal(packageIdentity,'sha256:0890ca4893ef76118eefbb2b5676ad084c60c70408d9e489f92aa33b74ba45b7');
const candidateAuthority=JSON.parse(fs.readFileSync(path.join(root,prospectiveRel,'candidate.json'),'utf8'));
const binding=JSON.parse(fs.readFileSync(path.join(root,prospectiveRel,'binding.json'),'utf8'));
const bindingVerification=JSON.parse(fs.readFileSync(path.join(root,prospectiveRel,'binding-verification.json'),'utf8'));
assert.equal(candidateAuthority.result,'READY_FOR_BINDING');assert.equal(candidateAuthority.candidateRole,'C3V');assert.equal(candidateAuthority.parentAuthority,BASE);assert.equal(candidateAuthority.limits.aggregateHelperActiveMs,28000);
assert.equal(binding.candidateRole,'C3V');assert.equal(binding.bindingRole,'C3VB');assert.equal(binding.binding.soleParent,C3V);assert.equal(binding.binding.productionChanges,false);
assert.equal(bindingVerification.result,'PASS');assert.equal(bindingVerification.candidateCommit,C3V);assert.equal(bindingVerification.candidateRootTree,'7635bd204fce185253e06d10e9cca625618c1921');assert.equal(bindingVerification.productionTree,productionTree);
assert.equal(candidateAuthority.package.packageIdentity,packageIdentity);assert.equal(candidateAuthority.package.packageMemberCount,89);
assert.equal(candidateAuthority.helper.sha256,'sha256:97ef5ae9ce7ab390548b04a2aefba9f922c3e1c6b9b80581c6c274f0b21f0127');
const historical=[];
const historicalPaths=git('ls-tree','-r','--name-only',C3VB).toString().trim().split(/\r?\n/).filter(p=>p.startsWith('repositories/cca-conformance/evidence/mo1307/')||p.startsWith('repositories/cca-conformance/tools/mo1307-')||p.startsWith('docs/mo1307-'));
for(const relative of historicalPaths){const full=path.join(root,relative);assert.ok(fs.existsSync(full),relative);historical.push({...record(full),absolutePath:full});}
write('historical-before.json',{result:'PRESERVATION_BASELINE',candidate:C3VB,members:historical,promotion:false,readOnly:true,source:'Tracked MO-1307 authority, tooling and evidence at exact C3VB; current fresh namespace excluded because absent at C3VB.'});
write('candidate-before.json',{candidate:C3VB,productionCommit:C3V,productionTree,authorities:[helperAuthority,integration],parent:git('show','-s','--format=%P','HEAD').toString().trim(),tree:git('rev-parse','HEAD^{tree}').toString().trim(),members:production,packageIdentity,check:sourceCheck,initialStatus:git('status','--porcelain=v1','--untracked-files=all').toString(),productionGitDiff:git('diff','--name-only',C3VB,'--','repositories/memoryos-readiness').toString(),binding:record(path.join(root,prospectiveRel,'binding.json')),bindingVerification:record(path.join(root,prospectiveRel,'binding-verification.json')),observerCorrection:record(correctionReceiptPath),preCertificationBGate:record(bGatePath),preservedFailedBGate:record(failedBGatePath)});
fs.mkdirSync(cache,{recursive:true});
function command(id,exe,args,cwd=root,extra={}){const start=performance.now();const r=spawnSync(exe,args,{cwd,env:{...env,...extra},windowsHide:true,shell:false,encoding:null,timeout:120000,maxBuffer:16*1024*1024});write(id+'.json',{executable:exe,args,cwd,exit:r.status,error:r.error?.code??null,elapsedMs:performance.now()-start,stdout:put(id+'.stdout.data',r.stdout??Buffer.alloc(0)),stderr:put(id+'.stderr.data',r.stderr??Buffer.alloc(0))});assert.ifError(r.error);assert.equal(r.status,0,r.stderr.toString());return r.stdout;}
const ps='C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe';
const script="$os=Get-CimInstance Win32_OperatingSystem; $cs=Get-CimInstance Win32_ComputerSystem; [ordered]@{osCaption=$os.Caption;version=$os.Version;build=$os.BuildNumber;architecture=$os.OSArchitecture;manufacturer=$cs.Manufacturer;model=$cs.Model;powerShellPath=(Get-Process -Id $PID).Path;powerShellVersion=$PSVersionTable.PSVersion.ToString();policy=@(Get-ExecutionPolicy -List | ForEach-Object {[ordered]@{scope=$_.Scope.ToString();policy=$_.ExecutionPolicy.ToString()}})} | ConvertTo-Json -Depth 5 -Compress";
const system=JSON.parse(command('environment-capture',ps,['-NoLogo','-NoProfile','-NonInteractive','-Command',script]));
assert.match(system.powerShellVersion,/^5\.1\./);assert.match(system.osCaption,/Windows 11/);assert.match(system.architecture,/64/);
assert.equal(hash(fs.readFileSync(ps)),'sha256:8bb6fa8c283b4d92120b1ef249a9b311b0f804d4cabbe9981159976c8be76a5e');
const npm=path.join(path.dirname(process.execPath),'node_modules/npm/bin/npm-cli.js');
assert.equal(command('npm-version',process.execPath,[npm,'--version']).toString().trim(),'11.19.0');
assert.equal(hash(fs.readFileSync(npm)),'sha256:3ce7cba6f5128dd5f54c98b6a5036b0f850496878cc2e21044b675fe3c594e3e');
const python='C:/Users/melsa/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';assert.equal(hash(fs.readFileSync(python)),'sha256:4278cf2a296f31737cae77cafeeb3dc71683094cf3b8fd6f3f02c968687e771c');
write('runtime.json',{result:'PASS',node:{executable:process.execPath,version:process.version,arch:process.arch,platform:process.platform,...record(process.execPath)},powershell:{...system,identity:record(ps)},npm:{path:npm,version:'11.19.0',identity:record(npm),engineeringOnly:true},python:{path:python,identity:record(python),engineeringObserverOnly:true},launchEnvironment:env,networkRequired:false,persistentPolicyMutation:false});
for(const n of ['npm-cache','install','cwd'])fs.mkdirSync(path.join(cache,n));
for(const n of ['user.npmrc','global.npmrc'])fs.writeFileSync(path.join(cache,n),'',{flag:'wx'});
const npmArgs=['--offline','--ignore-scripts','--no-audit','--no-fund','--cache',path.join(cache,'npm-cache'),'--userconfig',path.join(cache,'user.npmrc'),'--globalconfig',path.join(cache,'global.npmrc')];
const extra={PATH:path.dirname(process.execPath),TEMP:cache,TMP:cache};
const packed=JSON.parse(command('package-pack',process.execPath,[npm,'pack','--json','--pack-destination',cache,...npmArgs],source,extra));
assert.equal(packed.length,1);assert.deepEqual(packed[0].files.map(r=>r.path).sort(),[...packageFiles]);
const archive=path.join(cache,packed[0].filename),archiveBinding=put('package/memoryos-readiness-0.1.0.tgz',fs.readFileSync(archive));
fs.writeFileSync(path.join(cache,'install/package.json'),JSON.stringify({name:'mo1307-phase3ar2-final-offline',version:'1.0.0',private:true})+'\n',{flag:'wx'});
command('offline-install',process.execPath,[npm,'install',archive,...npmArgs],path.join(cache,'install'),extra);
const members=walk(installed);assert.equal(members.length,89);assert.deepEqual(members,production);const installedCheck=checkPackage(installed);assert.equal(sourceCheck.members,89);assert.equal(sourceCheck.externalProductionDependencies,0);assert.equal(installedCheck.members,89);assert.equal(installedCheck.externalProductionDependencies,0);
assert.equal(hash(Buffer.from(canonical(members)+'\n')),packageIdentity);
write('installed-before.json',{result:'PASS',members,packageRoot:installed,sourceAndC3VBEqual:true,packageIdentity,check:installedCheck,noScripts:true,offline:true,networkFallback:false});
write('candidate-identity.json',{result:'PASS',C3VB,C3V,productionTree,authorities:[helperAuthority,integration],packageRoot:installed,packageName:'memoryos-readiness',version:'0.1.0',members:89,externalProductionDependencies:0,packageIdentity,helperSha256:'sha256:97ef5ae9ce7ab390548b04a2aefba9f922c3e1c6b9b80581c6c274f0b21f0127',archive:archiveBinding,npmPack:packed[0],repositoryAuthority:record(path.join(root,'repositories/cca-conformance/tools/mo1307-phase1/package.mjs')),candidateAuthority:record(path.join(root,prospectiveRel,'candidate.json')),candidateBinding:record(path.join(root,prospectiveRel,'binding.json')),bindingVerification:record(path.join(root,prospectiveRel,'binding-verification.json')),observerCorrection:record(correctionReceiptPath),preCertificationBGate:record(bGatePath),preservedFailedBGate:record(failedBGatePath),duplicate3B:false});
write('baseline.json',{result:'PASS',startedAt,hardStopAt,HEAD:C3VB,productionCommit:C3V,productionTree,authorities:[helperAuthority,integration],branch:'codex/mo1307-phase3ar2-c3ub',installed:members,source:production,candidate:{name:'memoryos-readiness',version:'0.1.0',members:89,externalProductionDependencies:0,packageIdentity,archive:archiveBinding},runtime:record(process.execPath),productionChanges:0,observerCorrection:record(correctionReceiptPath),preCertificationBGate:record(bGatePath),preservedFailedBGate:record(failedBGatePath)});
const names=['mo1306-qualified','ready','not-ready','could-not-evaluate','rest-qualified','qualified','post-tag-ready','pre-tag-present','post-tag-absent','post-tag-lightweight','post-tag-wrong-target'];
const vectors=names.map((name,index)=>{const src=path.join(root,'repositories/cca-conformance/fixtures/mo1307/bundles',name),base=path.join(cache,'v'+index),inputRoot=path.join(base,'i'),parent=path.join(base,'p');fs.mkdirSync(parent,{recursive:true});fs.cpSync(src,inputRoot,{recursive:true});fs.writeFileSync(path.join(parent,'owned-parent.txt'),'Private stable parent for fresh C3VB certification.\n',{flag:'wx'});return {name,index,inputRoot,parent,source:walk(src),input:walk(inputRoot),expected:record(path.join(src,'expected-result.json'))};});
write('vectors-prepared.json',{vectors});
const {loadBundle,envelopeFor,repin}=await import('../mo1307-phase2b/test-support.mjs');
const bundle=loadBundle('post-tag-ready');envelopeFor(bundle,'TAG_OBSERVATION').claim.detail.name='memoryos-1.3-wrong-tag';const input=repin(bundle);
const inputRoot=path.join(cache,'wrong-name-input');fs.mkdirSync(inputRoot);
for(const [name,b]of [['configuration.json',input.configurationBytes],['candidate.json',input.candidateBytes],['authority.json',input.authorityBytes],['manifest.json',input.manifestBytes]])fs.writeFileSync(path.join(inputRoot,name),b,{flag:'wx'});
for(const entry of bundle.manifest.entries){const file=path.join(inputRoot,entry.path);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bundle.files.get(entry.id),{flag:'wx'});}
const definitionPath=path.join(root,'repositories/cca-conformance/evidence/mo1307/phase3ar2-c3ub/wrong-name-prepared.json'),definitionExpectedPath=path.join(root,'repositories/cca-conformance/evidence/mo1307/phase3ar2-c3ub/prepared-wrong-name/expected-result.json');
const definition=JSON.parse(fs.readFileSync(definitionPath,'utf8')),expected=fs.readFileSync(definitionExpectedPath),result=JSON.parse(expected);
assert.deepEqual(walk(inputRoot),definition.input);assert.equal(input.expectedCandidateDigest,definition.pins.expectedCandidateDigest);assert.equal(input.trustedAuthorityDigest,definition.pins.trustedAuthorityDigest);assert.deepEqual(record(definitionExpectedPath),{path:'repositories/cca-conformance/evidence/mo1307/phase3ar2-c3ub/prepared-wrong-name/expected-result.json',byteLength:60508,sha256:'sha256:3a3f0b5b468ada374d07c1e40ea360422887e766d90638979f6c768a6f16f510'});assert.equal(record(path.join(installed,'src/integration.mjs')).sha256,'sha256:c73e278db2b2cdd5b38e3e9a6046ba529aafe92af5abfee4e0ced8b0ec02c64e');
assert.equal(result.assessment.readiness,'NOT_READY');assert.ok(result.assessment.blockers.some(x=>x.gateId==='tag'&&x.checkCode==='TAG_NAME'));
const expectedPath=path.join(E,'prepared-wrong-name/expected-result.json');put('prepared-wrong-name/expected-result.json',expected);
write('wrong-name-prepared.json',{inputRoot,expectedPath,pins:{expectedCandidateDigest:input.expectedCandidateDigest,trustedAuthorityDigest:input.trustedAuthorityDigest},result,input:walk(inputRoot),derivation:'Definition-only mechanical copy of the tracked Phase 3AR2 C3UB D11 wrong-name expected bytes after exact input-record and pin equality; no installed semantic oracle was invoked.',definition:{metadata:record(definitionPath),expectedResult:record(definitionExpectedPath)},currentOracleSource:record(path.join(installed,'src/integration.mjs')),semanticOracleExecutions:0,historicalPassPromoted:false,authority:record(path.join(root,'repositories/cca-conformance/tests/mo1307_phase2d_semantic_test.mjs'))});
console.log(JSON.stringify({result:'PASS',phase:'PREPARATION_ONLY',archive:archiveBinding,installed:members.length,historical:historical.length,runtime:system.powerShellVersion,certificationCasesExecuted:0}));
