import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {root,E,T,cache,relativeE as rel,packageRoot,HEAD,authority,helperAuthority,env,json,record,walk,write,put,identity,git,hash,startedAt,hardStopAt} from './common.mjs';
const mode=process.argv[2];assert.ok(['seal','run','close'].includes(mode));
if(mode!=='close')identity();else{assert.equal(path.resolve(root).toLowerCase(),'c:\\users\\melsa\\documents\\codex\\3ar2');assert.equal(process.platform,'win32');assert.equal(process.version,'v24.21.0');assert.equal(process.arch,'x64');assert.equal(hash(fs.readFileSync(process.execPath)),'sha256:ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32');assert.equal(git('rev-parse','HEAD').toString().trim(),HEAD);assert.equal(git('branch','--show-current').toString().trim(),'codex/mo1307-phase3ar2-c3ub');}
const steps='ABCDEFGHIJKLMNO'.split('');
const exists=name=>fs.existsSync(path.join(E,name));
const check=b=>assert.deepEqual(record(path.resolve(root,b.path)),b);
const inventoryPath=path.join(E,'recovered-inventory.json');
const toolNames=['.gitattributes','prepare.mjs','recover-inventory.mjs','record-harness-review.mjs','common.mjs','campaign.mjs','core.mjs','stage.mjs','decisions-tags.mjs','method.mjs','observer-entry.mjs','runtime-observer.mjs','transport-observer.mjs','errors-observer.mjs','observe-command.py','runtime-controls.mjs','runtime-controls-worker.mjs','runtime-controls-run.py','runtime-controls-observer.py','topology_identity_policy.py','cleanup-topology.mjs','finalization.mjs','finalization-lock.ps1','security.mjs','security-worker.mjs','determinism.mjs'];
const dependencyPaths=['repositories/cca-conformance/tools/mo1307-phase2b/test-support.mjs','repositories/cca-conformance/tools/mo1307-phase1/package.mjs','repositories/cca-conformance/tests/mo1307_phase2d_semantic_test.mjs','docs/mo1307-contract-freeze-1.md','docs/mo1307-phase2c-publication-inspection-correction.md','docs/mo1307-phase2c-finalization-boundary-correction.md','docs/mo1307-prospective-helper-bound-v2-candidate.md','docs/mo1307-prospective-helper-aggregate-bound-v2-candidate.md','docs/mo1307-final-headless-correction-addendum.md','docs/mo1307-phase3ar2-final.md','docs/mo1307-phase3ar2-final-h-corrected.md','docs/mo1307-phase3ar2-final-h2-corrected.md','repositories/cca-conformance/evidence/mo1307/final-headless/authorization.txt','repositories/cca-conformance/evidence/mo1307/prospective-helper-bound-v2-candidate/authority.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/authority.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/phase3a-handoff.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/phase3br2-binding-delta.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/phase3cr2-aggregate-delta.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/changed-file-inventory.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/binding.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/binding-verification.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/candidate.json','repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/consistency-validation.json'];
const prerequisiteNamespaces={
  historicalFailedBGateTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-b-gate',
  historicalFailedBGateEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-b-gate',
  topologyObserverCorrectionTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-topology-observer-correction',
  topologyObserverCorrectionEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-topology-observer-correction',
  correctedBGateTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-corrected-b-gate',
  correctedBGateEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-corrected-b-gate',
  preservedFailedFullTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final',
  preservedFailedFullEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final',
  hHarnessCorrectionTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-h-harness-correction',
  hHarnessCorrectionEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-h-harness-correction',
  preservedFailedHCorrectedTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-h-corrected',
  preservedFailedHCorrectedEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-h-corrected',
  h2HarnessCorrectionTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-h2-harness-correction',
  h2HarnessCorrectionEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-h2-harness-correction',
  preservedBlockedH2Tools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-h2-corrected',
  preservedBlockedH2Evidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-h2-corrected',
  h3RebindingTools:'repositories/cca-conformance/tools/mo1307-phase3ar2-final-h3-rebinding',
  h3RebindingEvidence:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final-h3-rebinding'
};
const prerequisiteMemberCounts={historicalFailedBGateTools:7,historicalFailedBGateEvidence:28,topologyObserverCorrectionTools:3,topologyObserverCorrectionEvidence:6,correctedBGateTools:8,correctedBGateEvidence:28,preservedFailedFullTools:26,preservedFailedFullEvidence:374,hHarnessCorrectionTools:1,hHarnessCorrectionEvidence:6,preservedFailedHCorrectedTools:26,preservedFailedHCorrectedEvidence:407,h2HarnessCorrectionTools:5,h2HarnessCorrectionEvidence:9,preservedBlockedH2Tools:26,preservedBlockedH2Evidence:9,h3RebindingTools:2,h3RebindingEvidence:6};
const h2FixtureRoots=['repositories/cca-conformance/fixtures/mo1307/phase3ar2-final-h2-corrected','repositories/cca-conformance/fixtures/mo1307/phase3ar2-final-h2-corrected-input'];
const h2FailureClassifications=['H_AGGREGATE_FIXTURE_INPUT_ISOLATION_DEFECT','H_OBSERVER_EVENT_ORDERING_DEFECT'];
const aggregateHelperEngineeringEnvelope={artificialEofDelayMs:5700,engineeringMinMs:28000,engineeringMaxMs:31000,maxHelperSlots:5,publicationStateMutations:0,expectedError:'MO1307_TIMEOUT',productAggregateDeadlineMs:28000};
const historicalFailedBGateReceiptPath=path.join(root,prerequisiteNamespaces.historicalFailedBGateEvidence,'gate-receipt.json');
const historicalFailedTopologyReceiptPath=path.join(root,prerequisiteNamespaces.historicalFailedBGateEvidence,'topology/receipt.json');
const topologyObserverCorrectionReceiptPath=path.join(root,prerequisiteNamespaces.topologyObserverCorrectionEvidence,'receipt.json');
const topologyObserverCorrectionSourcesPath=path.join(root,prerequisiteNamespaces.topologyObserverCorrectionEvidence,'source-bindings.json');
const topologyObserverCorrectionZeroExecutionPath=path.join(root,prerequisiteNamespaces.topologyObserverCorrectionEvidence,'zero-execution-proof.json');
const canonicalCorrectionToolRoot=path.join(root,prerequisiteNamespaces.topologyObserverCorrectionTools);
const canonicalObserverPath=path.join(canonicalCorrectionToolRoot,'runtime-controls-observer.py'),canonicalPolicyPath=path.join(canonicalCorrectionToolRoot,'topology_identity_policy.py'),canonicalValidatorPath=path.join(canonicalCorrectionToolRoot,'synthetic-validation.py');
const correctedBGateReceiptPath=path.join(root,prerequisiteNamespaces.correctedBGateEvidence,'gate-receipt.json');
const failedFullReceiptPath=path.join(root,prerequisiteNamespaces.preservedFailedFullEvidence,'certification-receipt.json');
const hHarnessCorrectionReceiptPath=path.join(root,prerequisiteNamespaces.hHarnessCorrectionEvidence,'receipt.json');
const h2HarnessCorrectionReceiptPath=path.join(root,prerequisiteNamespaces.h2HarnessCorrectionEvidence,'receipt.json');
const preservedFailedHCorrectedReceiptPath=path.join(root,prerequisiteNamespaces.preservedFailedHCorrectedEvidence,'certification-receipt.json');
const inputNames=['pre-execution-gate.json','campaign-config.json','generation-authorization.txt','baseline.json','candidate-before.json','installed-before.json','candidate-identity.json','runtime.json','historical-before.json','vectors-prepared.json','wrong-name-prepared.json','prepared-wrong-name/expected-result.json','recovered-inventory.json','inventory-validation.json','harness-review.json','observation-method.json'];
const fixedLimits={helperWholeLifecycleMs:9000,helperSuccess:'elapsedMs < 9000',helperTimeout:'elapsedMs >= 9000',aggregateHelperActiveMs:28000,aggregateSuccess:'helperActiveMs < 28000',aggregateTimeout:'helperActiveMs >= 28000',cliRenameAdmissionMs:30000,apiWorkerMs:10000,failureCleanupMs:2000};
const fixedExecution={once:true,caseRetry:false,replacement:false,warmup:false,adaptiveExpansion:false,diagnosticPromotion:false,lateSuccessRecovery:false,stopAtFirstMandatoryFailure:true,semanticNonzeroExitsAcceptedWhenExpected:true};
function prerequisiteChainBindings(){return Object.fromEntries(Object.entries(prerequisiteNamespaces).map(([name,relative])=>{const base=path.join(root,relative),members=walk(base);assert.equal(members.length,prerequisiteMemberCounts[name],name);assert.ok(members.every(row=>!row.link),name+' contains a symbolic link');return [name,{root:relative,members:members.map(row=>record(path.join(base,row.path)))}];}));}
function prerequisiteRecords(seal){return Object.values(seal.prerequisiteChain??{}).flatMap(entry=>Array.isArray(entry?.members)?entry.members:[]);}
function expectedSealBindings(){
  const baseline=json(path.join(E,'baseline.json'));
  const tools=walk(T).map(r=>record(path.join(T,r.path)));
  const dependencies=dependencyPaths.map(p=>record(path.join(root,p)));
  const fixtureBindings=walk(path.join(root,'repositories/cca-conformance/fixtures/mo1307')).map(r=>record(path.join(root,'repositories/cca-conformance/fixtures/mo1307',r.path)));
  const candidateMembers=[...baseline.source.map(r=>record(path.join(root,'repositories/memoryos-readiness',r.path))),...baseline.installed.map(r=>record(path.join(packageRoot,r.path)))];
  const preparedBindings=json(path.join(E,'vectors-prepared.json')).vectors.flatMap(v=>v.input.map(r=>record(path.join(v.inputRoot,r.path))));
  const wrong=json(path.join(E,'wrong-name-prepared.json'));for(const r of wrong.input)preparedBindings.push(record(path.join(wrong.inputRoot,r.path)));
  const inputs=inputNames.map(n=>record(path.join(E,n)));
  const prerequisiteChain=prerequisiteChainBindings();
  assert.equal(tools.length,26);assert.equal(dependencies.length,dependencyPaths.length);assert.equal(candidateMembers.length,178);assert.equal(inputs.length,16);
  return {tools,dependencies,fixtureBindings,candidateMembers,preparedBindings,inputs,prerequisiteChain};
}
function validateSeal(seal){
  assert.equal(seal.kind,'MO1307Phase3AR2C3VBNativeInstalledCampaignSeal');assert.equal(seal.version,'1.0.0');
  assert.ok(Number.isFinite(Date.parse(seal.sealedAt)));
  assert.equal(seal.candidate,HEAD);assert.equal(seal.productionCommit,'98b766f9218b209f52251147213839b9775f6da3');assert.equal(seal.productionTree,'b9dabf54572e06c96bb5e48c4e20671f2cc24053');assert.equal(seal.integrationAuthority,authority);assert.equal(seal.helperAuthority,helperAuthority);
  assert.deepEqual(seal.order,steps);assert.deepEqual(seal.inventory,record(inventoryPath));assert.deepEqual(seal.limits,fixedLimits);assert.deepEqual(seal.execution,fixedExecution);
  assert.equal(seal.historicalCharacterizationH,'NOT_ESTABLISHED');assert.equal(seal.replacementHelperBoundH,'NOT_ESTABLISHED');assert.equal(seal.hFailureClassification,'H_HARNESS_MARGIN_DEFECT');assert.deepEqual(seal.timelyHelperEngineeringEnvelope,{artificialEofDelayMs:0,maxMs:5000,deadlineMarginMs:4000});assert.equal(seal.admittedRenameSettlement,'NO_FINITE_BOUND_ESTABLISHED');
  assert.equal(seal.historicalEvidencePromoted,false);assert.equal(seal.scope,'PHASE_3AR2_ONLY');assert.equal(seal.preservedPhase3BR2,'4d92f0f21c9c3aad8202f4558d61b9229c7214fc');assert.equal(seal.phase3BR2Rerun,false);assert.equal(seal.preservedPhase3CR2,'7d2006c6e19bb50bffb6c710672be996e3c3590b');assert.equal(seal.phase3CR2Rerun,false);assert.equal(seal.phase3CR2ExecutedHere,false);assert.equal(seal.phase3D,false);assert.deepEqual(seal.preCertificationBGate,record(correctedBGateReceiptPath));assert.deepEqual(seal.preservedFailedPreCertificationBGate,record(historicalFailedBGateReceiptPath));assert.deepEqual(seal.topologyObserverCorrection,record(topologyObserverCorrectionReceiptPath));assert.deepEqual(seal.hHarnessCorrection,record(hHarnessCorrectionReceiptPath));assert.deepEqual(seal.preservedFailedFullGeneration,record(failedFullReceiptPath));
  assert.deepEqual(seal.h2HarnessCorrection,record(h2HarnessCorrectionReceiptPath));assert.deepEqual(seal.preservedFailedHCorrectedGeneration,record(preservedFailedHCorrectedReceiptPath));assert.deepEqual(seal.h2FailureClassifications,h2FailureClassifications);assert.deepEqual(seal.aggregateHelperEngineeringEnvelope,aggregateHelperEngineeringEnvelope);assert.equal(seal.eventOrderingRule,'MO1307_OBSERVER_EVENT_ORDERING@1.0.0');assert.deepEqual(seal.h2FixtureRoots,h2FixtureRoots);assert.deepEqual(seal.h3Rebinding,record(path.join(root,prerequisiteNamespaces.h3RebindingEvidence,'receipt.json')));assert.deepEqual(seal.preservedBlockedH2Generation,{path:prerequisiteNamespaces.preservedBlockedH2Evidence+'/certification-receipt.json',byteLength:13870,sha256:'sha256:a740a4b6e7032af7f7db0beeb3b42ceac33489bf43188906c4de917a849cd0c0'});
  const h2Correction=json(h2HarnessCorrectionReceiptPath),preservedFailedHCorrected=json(preservedFailedHCorrectedReceiptPath);assert.equal(h2Correction.kind,'MO1307Phase3AR2FinalH2HarnessCorrectionReceipt');assert.equal(h2Correction.result,'PASS');assert.equal(h2Correction.zeroProductValidation,'PASS');assert.deepEqual(h2Correction.classifications,h2FailureClassifications);assert.deepEqual(h2Correction.aggregateControl,aggregateHelperEngineeringEnvelope);assert.deepEqual(h2Correction.execution,{certificationRuns:0,helperRuns:0,nativeObserverRuns:0,productRuns:0,workerRuns:0,engineeringInterpreterInvocations:2});assert.equal(h2Correction.retry,false);assert.deepEqual(record(preservedFailedHCorrectedReceiptPath),{path:prerequisiteNamespaces.preservedFailedHCorrectedEvidence+'/certification-receipt.json',byteLength:463330,sha256:'sha256:719ebafbbabe4c89f1502271310109dc8d6cb4efff8bc43da313b7dd7411e031'});assert.equal(preservedFailedHCorrected.result,'PHASE3AR2_CONCRETE_BLOCKER');assert.deepEqual(preservedFailedHCorrected.completed,['A','B','C','D','E','F','G']);assert.equal(preservedFailedHCorrected.steps.find(row=>row.step==='H').result,'FAIL');assert.deepEqual(preservedFailedHCorrected.unexecuted,['I','J','K','L','M','N','O']);for(const fixtureRoot of h2FixtureRoots)assert.ok(seal.fixtureBindings.some(row=>row.path.startsWith(fixtureRoot+'/')),fixtureRoot);assert.equal(fs.existsSync(path.join(root,h2FixtureRoots[0],'absent-output')),false,'Sealed aggregate absent-output target must remain absent');
  const expectedProductionCommit='98b766f9218b209f52251147213839b9775f6da3',expectedProductionTree='b9dabf54572e06c96bb5e48c4e20671f2cc24053',expectedPolicy='MO1307_TOPOLOGY_IDENTITY_POLICY@1.0.0';
  const sharedAuthorities=[helperAuthority,authority],bLimits={helperWholeLifecycleMs:9000,helperSuccess:'elapsedMs < 9000',helperTimeout:'elapsedMs >= 9000',aggregateHelperActiveMs:28000,aggregateSuccess:'helperActiveMs < 28000',aggregateTimeout:'helperActiveMs >= 28000',cliMs:30000,apiWorkerMs:10000,cleanupMs:2000};
  const failedBGate=json(historicalFailedBGateReceiptPath),failedTopology=json(historicalFailedTopologyReceiptPath),correction=json(topologyObserverCorrectionReceiptPath),correctedBGate=json(correctedBGateReceiptPath);
  const failedGateBinding=record(historicalFailedBGateReceiptPath),failedTopologyBinding=record(historicalFailedTopologyReceiptPath),correctionBinding=record(topologyObserverCorrectionReceiptPath);
  assert.equal(failedGateBinding.byteLength,7140);assert.equal(failedGateBinding.sha256,'sha256:6236c0976bb13bc6a8705962b2729f1dbb581917f2556c85dc372ff0d42d34b5');assert.equal(failedTopologyBinding.byteLength,26064);assert.equal(failedTopologyBinding.sha256,'sha256:46501796f6b73e8d63c0b4e2287b412a0e0e61df51cd7f022204f1161d39fb78');
  assert.equal(failedBGate.kind,'MO1307Phase3AR2FinalPreCertificationBGateReceipt');assert.equal(failedBGate.version,'1.0.0');assert.equal(failedBGate.result,'FAIL');assert.equal(failedBGate.outcome,'PHASE3AR2_CONCRETE_BLOCKER');assert.equal(failedBGate.candidate,HEAD);assert.equal(failedBGate.productionCommit,expectedProductionCommit);assert.equal(failedBGate.productionTree,expectedProductionTree);assert.deepEqual(failedBGate.authorities,sharedAuthorities);assert.equal(failedBGate.certification,false);assert.equal(failedBGate.semanticInvocations,1);assert.equal(failedBGate.noRetry,true);assert.equal(failedBGate.replacementExecutions,0);assert.equal(failedBGate.diagnosticsRun,0);assert.deepEqual(failedBGate.limits,bLimits);assert.deepEqual(failedBGate.bindings.topology,failedTopologyBinding);assert.equal(failedBGate.fullCertificationStarted,false);assert.equal(failedBGate.push,false);assert.equal(failedBGate.tag,false);
  assert.equal(failedTopology.kind,'MO1307Phase3AR2FinalBGateLifecycleObservation');assert.equal(failedTopology.result,'FAIL');assert.equal(failedTopology.semanticInvocations,1);assert.equal(failedTopology.driverExit,0);assert.equal(failedTopology.observerExit,0);assert.equal(failedTopology.expectedHelpers,9);assert.equal(failedTopology.helperPairs.length,9);assert.equal(failedTopology.identityOrSnapshotFailures,1);assert.equal(failedTopology.observationErrors.length,1);assert.deepEqual({event:failedTopology.observationErrors[0].event,pid:failedTopology.observationErrors[0].pid,parentPid:failedTopology.observationErrors[0].parentPid,error:failedTopology.observationErrors[0].error},{event:'candidate_identity_unknown',pid:2540,parentPid:2140,error:{operation:'QueryFullProcessImageNameW',winerror:31}});
  assert.equal(correctionBinding.byteLength,5603);assert.equal(correctionBinding.sha256,'sha256:dd1083bfd5592a7170b0b36b4d3e745210e7fc5a1822fa4abdc9dd4df14aa0b9');
  assert.equal(correction.kind,'MO1307Phase3AR2TopologyObserverSyntheticValidationReceipt');assert.equal(correction.version,'1.0.0');assert.equal(correction.result,'PASS');assert.equal(correction.candidate,HEAD);assert.equal(correction.productionCommit,expectedProductionCommit);assert.equal(correction.productionTree,expectedProductionTree);assert.equal(correction.policy,expectedPolicy);assert.deepEqual(correction.cases,{acceptedExactly:['B','F'],allRequiredCasesPassed:true,failedClosedExactly:['A','C','D','E','G'],passed:7,required:['A','B','C','D','E','F','G']});assert.deepEqual(correction.execution,{engineeringInterpreterInvocations:1,helperRuns:0,nativeObserverRuns:0,productRuns:0,retry:false,semanticProductInvocations:0});assert.deepEqual(correction.defect,{event:'candidate_identity_unknown',historicalIdentityOrSnapshotFailures:1,operation:'QueryFullProcessImageNameW',parentPid:2140,pid:2540,winerror:31});
  for(const key of ['initialIdentityFailureStillFailsClosed','pidReuseFailsClosed','requiresExactCreationAndExitIdentity','requiresParentImageRoleAndLifetimeConsistency','requiresPriorPositiveIdentity','requiresSameObserverSession','toolhelpSnapshotClockIsPostCaptureUpperBound','unrelatedErrorsFailClosed'])assert.equal(correction.security[key],true,key);assert.equal(correction.security.win32Error31GloballyIgnored,false);assert.equal(correction.productionModified,false);assert.equal(correction.budgetsModified,false);assert.equal(correction.wireModified,false);assert.equal(correction.push,false);assert.equal(correction.tag,false);
  const probes=new Map(correction.additionalSecurityProbes.map(row=>[row.id,row])),crossSession=probes.get('CROSS_SESSION'),postExit=probes.get('POST_EXIT_SNAPSHOT_CLOCK');assert.deepEqual([...probes.keys()],['CROSS_SESSION','POST_EXIT_SNAPSHOT_CLOCK']);assert.equal(crossSession.result,'PASS');assert.equal(crossSession.expected,'CROSS_SESSION_IDENTITY_REJECTED');assert.equal(crossSession.actual.accepted,false);assert.equal(crossSession.actual.classification,'CROSS_SESSION_IDENTITY_REJECTED');assert.equal(crossSession.actual.policy,expectedPolicy);assert.equal(crossSession.actual.checks.sameObserverSession,false);assert.equal(postExit.result,'PASS');assert.equal(postExit.expected,'POST_IDENTITY_REQUERY_UNAVAILABLE');assert.equal(postExit.actual.accepted,true);assert.equal(postExit.actual.classification,'POST_IDENTITY_REQUERY_UNAVAILABLE');assert.equal(postExit.actual.policy,expectedPolicy);assert.ok(Object.values(postExit.actual.checks).every(value=>value===true));
  const correctionRoot=path.join(root,prerequisiteNamespaces.topologyObserverCorrectionEvidence),correctionSources=json(topologyObserverCorrectionSourcesPath);assert.deepEqual(correction.bindings.authorization,record(path.join(correctionRoot,'authorization.txt')));assert.deepEqual(correction.bindings.inputs,record(path.join(correctionRoot,'cases.json')));assert.deepEqual(correction.bindings.results,record(path.join(correctionRoot,'case-results.json')));assert.deepEqual(correction.bindings.sources,record(topologyObserverCorrectionSourcesPath));assert.deepEqual(correction.bindings.zeroExecutionProof,record(topologyObserverCorrectionZeroExecutionPath));assert.deepEqual(correctionSources.historicalFailedGate,failedGateBinding);assert.deepEqual(correctionSources.historicalFailedTopology,failedTopologyBinding);assert.deepEqual(correctionSources.correctedObserver,record(canonicalObserverPath));assert.deepEqual(correctionSources.policy,record(canonicalPolicyPath));assert.deepEqual(correctionSources.validator,record(canonicalValidatorPath));assert.equal(record(topologyObserverCorrectionSourcesPath).sha256,'sha256:bc9a6812c4ab33ca806838318021fbc8530e5e0ab744282dd83aa1e620069732');assert.equal(record(topologyObserverCorrectionZeroExecutionPath).sha256,'sha256:388a870f3f04e528f2469bad82b243f34af3845dd57127db3a0868cb75fc930b');assert.equal(record(canonicalObserverPath).sha256,'sha256:7b525e2b3ff09d6296a0ad3fa0e51eda0782cfb420a3f0759ddd5904c11aa4cd');assert.equal(record(canonicalPolicyPath).sha256,'sha256:83026a453c397b5fe56e82bad5bab64d3b580a419cef8869f93f4cbcd9649013');assert.equal(record(canonicalValidatorPath).sha256,'sha256:cc91d7d2ac498d43885e0cf1e3be09bcfa45d5d2f62e09e4ab5955ee6e83ff91');
  assert.equal(correctedBGate.kind,'MO1307Phase3AR2FinalCorrectedPreCertificationBGateReceipt');assert.equal(correctedBGate.version,'1.0.0');assert.equal(correctedBGate.result,'PASS');assert.equal(correctedBGate.outcome,'PRE_CERTIFICATION_B_GATE_PASS');assert.equal(correctedBGate.failure,null);assert.equal(correctedBGate.candidate,HEAD);assert.equal(correctedBGate.productionCommit,expectedProductionCommit);assert.equal(correctedBGate.productionTree,expectedProductionTree);assert.deepEqual(correctedBGate.authorities,sharedAuthorities);assert.equal(correctedBGate.identityPolicy,expectedPolicy);assert.equal(correctedBGate.certification,false);assert.equal(correctedBGate.semanticInvocations,1);assert.equal(correctedBGate.noRetry,true);assert.equal(correctedBGate.replacementExecutions,0);assert.equal(correctedBGate.diagnosticsRun,0);assert.equal(correctedBGate.priorFailedGatePreserved,true);assert.equal(correctedBGate.syntheticCorrectionValidated,true);assert.equal(correctedBGate.fullCertificationStarted,false);assert.equal(correctedBGate.push,false);assert.equal(correctedBGate.tag,false);assert.deepEqual(correctedBGate.requirements,{expectedReadiness:'READY',noHelperTimeout:true,allHelpersAccepted:true,scheduledTopologyRssWitness:'PASS',zeroUnresolvedTopologyIdentities:true,correctedObserverPolicy:true,cleanupSettlement:'PASS'});assert.deepEqual(correctedBGate.limits,bLimits);
  assert.ok(correctedBGate.details.helperUsedMs<28000);assert.ok(correctedBGate.details.productLifecycleElapsedMs<30000);assert.equal(correctedBGate.details.cleanupConfirmed,true);assert.equal(correctedBGate.details.package.members,89);assert.equal(correctedBGate.details.package.identity,'sha256:0890ca4893ef76118eefbb2b5676ad084c60c70408d9e489f92aa33b74ba45b7');assert.equal(correctedBGate.details.publication.phase,'COMMITTED');assert.equal(correctedBGate.details.publication.admitted,true);assert.equal(correctedBGate.details.publication.namespaceVerified,true);assert.equal(correctedBGate.details.publication.deadlineExpiredAfterAdmission,false);assert.equal(correctedBGate.details.publication.cancelledAfterAdmission,false);assert.equal(correctedBGate.details.topologyIdentity.policy,expectedPolicy);assert.equal(typeof correctedBGate.details.topologyIdentity.observerSession,'string');assert.ok(correctedBGate.details.topologyIdentity.observerSession.length>0);assert.equal(correctedBGate.details.topologyIdentity.unresolvedIdentityFailures,0);assert.ok(Number.isSafeInteger(correctedBGate.details.topologyIdentity.acceptedPostIdentityRequeryUnavailableCount)&&correctedBGate.details.topologyIdentity.acceptedPostIdentityRequeryUnavailableCount>=0);assert.ok(Number.isSafeInteger(correctedBGate.details.topologyIdentity.acceptedTerminatedKnownIdentityCount)&&correctedBGate.details.topologyIdentity.acceptedTerminatedKnownIdentityCount>=0);assert.equal(correctedBGate.details.topologyIdentity.acceptedIdentityProofsConsistent,true);assert.ok(correctedBGate.details.maxima.productRoles<=3);assert.ok(correctedBGate.details.maxima.helpers<=1);assert.ok(correctedBGate.details.maxima.helperConsoles<=1);assert.ok(correctedBGate.details.maxima.productWorkingSetBytes<=536870912);
  const correctionEvidenceMembers=walk(correctionRoot);assert.equal(correctionEvidenceMembers.length,6);assert.deepEqual(correctedBGate.bindings.historicalFailedGate,failedGateBinding);assert.deepEqual(correctedBGate.bindings.historicalFailedTopology,failedTopologyBinding);assert.deepEqual(correctedBGate.bindings.syntheticCorrectionReceipt,correctionBinding);assert.deepEqual(correctedBGate.bindings.syntheticCorrectionSourceBindings,record(topologyObserverCorrectionSourcesPath));assert.deepEqual(correctedBGate.bindings.syntheticCorrectionZeroExecutionProof,record(topologyObserverCorrectionZeroExecutionPath));assert.deepEqual(correctedBGate.bindings.canonicalCorrectedObserver,record(canonicalObserverPath));assert.deepEqual(correctedBGate.bindings.canonicalIdentityPolicy,record(canonicalPolicyPath));assert.deepEqual(correctedBGate.bindings.canonicalSyntheticValidator,record(canonicalValidatorPath));assert.equal(correctedBGate.bindings.syntheticCorrectionEvidence.root,prerequisiteNamespaces.topologyObserverCorrectionEvidence);assert.deepEqual(correctedBGate.bindings.syntheticCorrectionEvidence.members,correctionEvidenceMembers);
  assert.deepEqual(correctedBGate.details.correction.receipt,correctionBinding);assert.deepEqual(correctedBGate.details.correction.sourceBindings,record(topologyObserverCorrectionSourcesPath));assert.deepEqual(correctedBGate.details.correction.zeroExecutionProof,record(topologyObserverCorrectionZeroExecutionPath));assert.deepEqual(correctedBGate.details.correction.canonicalObserver,record(canonicalObserverPath));assert.deepEqual(correctedBGate.details.correction.canonicalPolicy,record(canonicalPolicyPath));assert.deepEqual(correctedBGate.details.correction.canonicalValidator,record(canonicalValidatorPath));assert.deepEqual(correctedBGate.details.correction.preservedFailedGate,failedGateBinding);assert.deepEqual(correctedBGate.details.correction.preservedFailedTopology,failedTopologyBinding);assert.deepEqual(correctedBGate.details.correction.evidence,correctionEvidenceMembers);
  const correctedToolRoot=path.join(root,prerequisiteNamespaces.correctedBGateTools);assert.deepEqual(fs.readFileSync(path.join(correctedToolRoot,'runtime-controls-observer.py')),fs.readFileSync(canonicalObserverPath));assert.deepEqual(fs.readFileSync(path.join(correctedToolRoot,'topology_identity_policy.py')),fs.readFileSync(canonicalPolicyPath));
  const failedFullBinding=record(failedFullReceiptPath),failedFull=json(failedFullReceiptPath),hCorrectionBinding=record(hHarnessCorrectionReceiptPath),hCorrection=json(hHarnessCorrectionReceiptPath);assert.deepEqual(failedFullBinding,{path:'repositories/cca-conformance/evidence/mo1307/phase3ar2-final/certification-receipt.json',byteLength:337821,sha256:'sha256:c0b83b89a3216892460d668f8eef5426a60a4f787b2f93b01af58b4ec57fe0df'});assert.equal(failedFull.result,'PHASE3AR2_CONCRETE_BLOCKER');assert.deepEqual(failedFull.completed,['A','B','C','D','E','F','G']);assert.equal(failedFull.steps.find(row=>row.step==='H').result,'FAIL');assert.deepEqual(failedFull.unexecuted,['I','J','K','L','M','N','O']);assert.equal(hCorrection.result,'PASS');assert.equal(hCorrection.classification,'H_HARNESS_MARGIN_DEFECT');assert.deepEqual(hCorrection.correctedControl,{artificialEofDelayMs:0,engineeringMaxMs:5000,engineeringMinMs:null,productDeadlineMs:9000});assert.equal(hCorrection.zeroProductValidation,'PASS');assert.deepEqual(hCorrection.execution,{certificationRuns:0,helperRuns:0,nativeObserverRuns:0,productRuns:0,workerRuns:0});assert.equal(hCorrection.retry,false);assert.deepEqual(hCorrectionBinding,seal.hHarnessCorrection);assert.equal(git('cat-file','-t',seal.preservedPhase3BR2).toString().trim(),'commit');assert.equal(git('cat-file','-t',seal.preservedPhase3CR2).toString().trim(),'commit');
  const expected=expectedSealBindings();for(const key of Object.keys(expected))assert.deepEqual(seal[key],expected[key],key);
  const prefix=path.relative(root,T).replaceAll('\\','/');assert.deepEqual(seal.tools.map(r=>r.path).sort(),toolNames.map(n=>prefix+'/'+n).sort());
  assert.deepEqual(seal.dependencies.map(r=>r.path),dependencyPaths);assert.deepEqual(seal.inputs.map(r=>r.path),inputNames.map(n=>rel+'/'+n));
  return seal;
}
if(mode==='seal'){
  assert.equal(exists('campaign-seal.json'),false);assert.equal(exists('campaign-run-start.json'),false);
  for(const name of ['campaign-run-finished.json','generation-stopped.json','acceptance-validation.json','phase3br2-final-binding-delta.json','phase3cr2-final-binding-delta.json','certification-receipt.json','phase3d-handoff.json','closure.json'])assert.equal(exists(name),false,'Pre-run output already exists: '+name);
  for(const name of ['steps','scheduler','runtime-H','runtime-I','cleanup-topology','finalization','security-L','security-M','determinism'])assert.equal(exists(name),false,'Certification output namespace already exists: '+name);
  const statusLines=git('status','--porcelain=v1','--untracked-files=all').toString().trim().split(/\r?\n/).filter(Boolean);
  const toolRel=path.relative(root,T).replaceAll('\\','/'),allowedUntracked=[toolRel,rel,...Object.values(prerequisiteNamespaces),...h2FixtureRoots];assert.ok(statusLines.every(line=>line==='?? docs/mo1307-phase3ar2-final.md'||line==='?? docs/mo1307-phase3ar2-final-h-corrected.md'||line==='?? docs/mo1307-phase3ar2-final-h2-corrected.md'||allowedUntracked.some(prefix=>line.startsWith('?? '+prefix+'/'))),'Unexpected working-tree path before seal');
  const baseline=json(path.join(E,'baseline.json'));
  assert.deepEqual(walk(packageRoot),baseline.installed);assert.deepEqual(walk(path.join(root,'repositories/memoryos-readiness')),baseline.source);
  for(const n of toolNames)assert.ok(fs.existsSync(path.join(T,n)),n);
  assert.ok(fs.existsSync(inventoryPath),'Complete recovered inventory is required');
  assert.ok(exists('harness-review.json'),'Independent static harness review is required');
  const harnessReview=json(path.join(E,'harness-review.json'));assert.equal(harnessReview.result,'PASS');assert.deepEqual(harnessReview.observerCorrection.receipt,record(topologyObserverCorrectionReceiptPath));assert.deepEqual(harnessReview.hHarnessCorrection.receipt,record(hHarnessCorrectionReceiptPath));assert.equal(harnessReview.hHarnessCorrection.classification,'H_HARNESS_MARGIN_DEFECT');assert.deepEqual(harnessReview.preservedFailedFullGeneration,record(failedFullReceiptPath));assert.deepEqual(harnessReview.correctedPreCertificationBGate,record(correctedBGateReceiptPath));assert.deepEqual(harnessReview.preservedFailedPreCertificationBGate,record(historicalFailedBGateReceiptPath));assert.deepEqual(harnessReview.h2HarnessCorrection.receipt,record(h2HarnessCorrectionReceiptPath));assert.deepEqual(harnessReview.h2HarnessCorrection.classifications,h2FailureClassifications);assert.deepEqual(harnessReview.preservedFailedHCorrectedGeneration,record(preservedFailedHCorrectedReceiptPath));
  const preExecution=json(path.join(E,'pre-execution-gate.json'));assert.deepEqual(preExecution.observerCorrection,record(topologyObserverCorrectionReceiptPath));assert.deepEqual(preExecution.hHarnessCorrection,record(hHarnessCorrectionReceiptPath));assert.deepEqual(preExecution.preservedFailedFullGeneration,record(failedFullReceiptPath));assert.deepEqual(preExecution.preCertificationBGate,record(correctedBGateReceiptPath));assert.deepEqual(preExecution.preservedFailedBGate,record(historicalFailedBGateReceiptPath));assert.deepEqual(preExecution.h2HarnessCorrection,record(h2HarnessCorrectionReceiptPath));assert.deepEqual(preExecution.preservedFailedHCorrectedGeneration,record(preservedFailedHCorrectedReceiptPath));
  for(const binding of harnessReview.reviewedModules)check(binding);
  const inventoryValidation=json(path.join(E,'inventory-validation.json'));
  assert.equal(inventoryValidation.result,'PASS');assert.equal(inventoryValidation.candidate,HEAD);assert.equal(inventoryValidation.integrationAuthority,authority);assert.equal(inventoryValidation.totalCases,80);assert.deepEqual(inventoryValidation.sections,steps);assert.deepEqual(inventoryValidation.inventory,record(inventoryPath));assert.equal(inventoryValidation.checks.allCasesNotRun,true);assert.equal(inventoryValidation.checks.historicalOutcomesPromoted,false);
  const bindings=expectedSealBindings();assert.deepEqual(harnessReview.reviewedModules,bindings.tools);
  const seal={kind:'MO1307Phase3AR2C3VBNativeInstalledCampaignSeal',version:'1.0.0',sealedAt:new Date().toISOString(),candidate:HEAD,productionCommit:'98b766f9218b209f52251147213839b9775f6da3',productionTree:'b9dabf54572e06c96bb5e48c4e20671f2cc24053',integrationAuthority:authority,helperAuthority,order:steps,inventory:record(inventoryPath),...bindings,limits:fixedLimits,historicalCharacterizationH:'NOT_ESTABLISHED',replacementHelperBoundH:'NOT_ESTABLISHED',hFailureClassification:'H_HARNESS_MARGIN_DEFECT',timelyHelperEngineeringEnvelope:{artificialEofDelayMs:0,maxMs:5000,deadlineMarginMs:4000},admittedRenameSettlement:'NO_FINITE_BOUND_ESTABLISHED',execution:fixedExecution,historicalEvidencePromoted:false,scope:'PHASE_3AR2_ONLY',preCertificationBGate:record(correctedBGateReceiptPath),preservedFailedPreCertificationBGate:record(historicalFailedBGateReceiptPath),topologyObserverCorrection:record(topologyObserverCorrectionReceiptPath),hHarnessCorrection:record(hHarnessCorrectionReceiptPath),preservedFailedFullGeneration:record(failedFullReceiptPath),h2HarnessCorrection:record(h2HarnessCorrectionReceiptPath),preservedFailedHCorrectedGeneration:record(preservedFailedHCorrectedReceiptPath),h2FailureClassifications,aggregateHelperEngineeringEnvelope,eventOrderingRule:'MO1307_OBSERVER_EVENT_ORDERING@1.0.0',h2FixtureRoots,h3Rebinding:record(path.join(root,prerequisiteNamespaces.h3RebindingEvidence,'receipt.json')),preservedBlockedH2Generation:record(path.join(root,prerequisiteNamespaces.preservedBlockedH2Evidence,'certification-receipt.json')),preservedPhase3BR2:'4d92f0f21c9c3aad8202f4558d61b9229c7214fc',phase3BR2Rerun:false,preservedPhase3CR2:'7d2006c6e19bb50bffb6c710672be996e3c3590b',phase3CR2Rerun:false,phase3CR2ExecutedHere:false,phase3D:false};
  validateSeal(seal);write('campaign-seal.json',seal);validateSeal(json(path.join(E,'campaign-seal.json')));
  console.log(JSON.stringify({result:'SEALED',inventory:record(inventoryPath),seal:record(path.join(E,'campaign-seal.json')),certificationCasesExecuted:0}));
}
if(mode==='run'){
  for(const name of [...inputNames,'campaign-seal.json'])assert.ok(exists(name),'Refusing run: '+name+' is missing; prepare, inventory, method, review and seal must all succeed in this generation first');
  const seal=json(path.join(E,'campaign-seal.json'));
  validateSeal(seal);
  for(const b of [...seal.tools,...seal.dependencies,...seal.fixtureBindings,...seal.candidateMembers,...seal.preparedBindings,...seal.inputs,...prerequisiteRecords(seal)])check(b);
  assert.equal(exists('campaign-run-start.json'),false,'Finite campaign cannot be restarted');
  assert.equal(exists('generation-stopped.json'),false);
  for(const name of ['campaign-run-finished.json','acceptance-validation.json','phase3br2-final-binding-delta.json','phase3cr2-final-binding-delta.json','certification-receipt.json','phase3d-handoff.json','closure.json'])assert.equal(exists(name),false,'Pre-existing run/closure output: '+name);
  write('campaign-run-start.json',{candidate:HEAD,startedAt:new Date().toISOString(),seal:record(path.join(E,'campaign-seal.json')),singleExecution:true});
  let failure=null,currentStep=null;
  try{for(const step of steps){
    currentStep=step;
    assert.equal(exists('generation-stopped.json'),false);
    for(const b of [...seal.tools,...seal.dependencies,...seal.fixtureBindings,...seal.candidateMembers,...seal.preparedBindings,...seal.inputs,...prerequisiteRecords(seal)])check(b);
    const script='ABCDEO'.includes(step)?'core.mjs':'FG'.includes(step)?'decisions-tags.mjs':'stage.mjs';
    const args=[path.join(T,script),step],at=performance.now();
    write('scheduler/'+step+'-launch.json',{step,executable:process.execPath,args,startedAt:new Date().toISOString(),env,noRetry:true});
    const r=spawnSync(process.execPath,args,{cwd:root,env,windowsHide:true,shell:false,encoding:null,maxBuffer:8*1024*1024});
    const row={step,exit:r.status,error:r.error?.code??null,signal:r.signal,elapsedMs:performance.now()-at,stdout:put('scheduler/'+step+'.stdout.data',r.stdout??Buffer.alloc(0)),stderr:put('scheduler/'+step+'.stderr.data',r.stderr??Buffer.alloc(0))};
    const receipt=exists('steps/'+step+'.json')?json(path.join(E,'steps/'+step+'.json')):null;
    row.result=r.status===0&&!r.error&&receipt?.result==='PASS'&&!exists('generation-stopped.json')?'PASS':'FAIL';
    write('scheduler/'+step+'-receipt.json',row);console.log(JSON.stringify({step,result:row.result,exit:r.status,elapsedMs:row.elapsedMs}));
    if(row.result!=='PASS'){
      failure={step,scheduler:record(path.join(E,'scheduler/'+step+'-receipt.json')),caseFailure:receipt?.failure??null};
      if(!exists('generation-stopped.json'))write('generation-stopped.json',{step,at:new Date().toISOString(),reason:'FIRST_MANDATORY_FAILURE_OR_HARNESS_INTERRUPTION',failure,noRetry:true,noLaterSteps:true});
      break;
    }
  }}catch(error){failure={step:currentStep,reason:'SCHEDULER_FAILURE_OR_INTERRUPTION',error:{name:error.name,message:error.message,code:error.code??null,stack:error.stack}};
    if(!exists('generation-stopped.json'))write('generation-stopped.json',{step:currentStep,at:new Date().toISOString(),reason:'FIRST_MANDATORY_FAILURE_OR_HARNESS_INTERRUPTION',failure,noRetry:true,noLaterSteps:true});
  }finally{write('campaign-run-finished.json',{finishedAt:new Date().toISOString(),result:failure?'FAILED_INCOMPLETE':'ALL_STEPS_COMPLETED',failure,noFurtherProductExecution:true});}
  process.exitCode=failure?1:0;
}
if(mode==='close'){
  for(const name of [...inputNames,'campaign-seal.json','campaign-run-start.json'])assert.ok(exists(name),'Refusing close: '+name+' is missing; close applies only to a sealed generation whose one-shot run was started');
  const integrityFailures=[];
  assert.equal(exists('certification-receipt.json'),false);
  if(!exists('campaign-run-start.json'))integrityFailures.push({type:'CAMPAIGN_START_MISSING',path:rel+'/campaign-run-start.json'});
  if(!exists('campaign-run-finished.json')){
    if(!exists('generation-stopped.json'))write('generation-stopped.json',{at:new Date().toISOString(),reason:'INTERRUPTED_STARTED_CAMPAIGN',noRetry:true,noLaterSteps:true});
    write('campaign-run-finished.json',{finishedAt:new Date().toISOString(),result:'FAILED_INCOMPLETE',failure:'INTERRUPTED_STARTED_CAMPAIGN',noFurtherProductExecution:true});
  }
  const safeGenerated=(file,type)=>{try{return json(file);}catch(error){integrityFailures.push({type,path:path.relative(root,file).replaceAll('\\','/'),message:error.message});return null;}};
  const safeObject=(file,type)=>{const value=safeGenerated(file,type);if(value&&typeof value==='object'&&!Array.isArray(value))return value;integrityFailures.push({type:type+'_SCHEMA',path:path.relative(root,file).replaceAll('\\','/'),message:'Expected a JSON object'});return null;};
  const safeArrayField=(value,field,type,file)=>{if(Array.isArray(value?.[field]))return value[field];integrityFailures.push({type,path:path.relative(root,file).replaceAll('\\','/'),field,message:'Expected an array'});return [];};
  const validNamedRows=(rows,type,context)=>{const valid=[];for(const [index,row] of rows.entries()){if(row&&typeof row==='object'&&!Array.isArray(row)&&typeof row.name==='string'&&typeof row.result==='string')valid.push(row);else integrityFailures.push({type,context,index,message:'Expected an object with string name and result'});}return valid;};
  const safeWalk=(directory,type)=>{try{return walk(directory);}catch(error){integrityFailures.push({type,path:path.relative(root,directory).replaceAll('\\','/'),message:error.message});return [];}};
  const safeRecord=(file,type)=>{try{return record(file);}catch(error){integrityFailures.push({type,path:path.relative(root,file).replaceAll('\\','/'),message:error.message});return null;}};
  const baseline=safeObject(path.join(E,'baseline.json'),'BASELINE_MALFORMED')??{},seal=safeObject(path.join(E,'campaign-seal.json'),'CAMPAIGN_SEAL_MALFORMED')??{};
  const baselineSource=safeArrayField(baseline,'source','BASELINE_SOURCE_SCHEMA',path.join(E,'baseline.json')),baselineInstalled=safeArrayField(baseline,'installed','BASELINE_INSTALLED_SCHEMA',path.join(E,'baseline.json'));
  try{validateSeal(seal);}catch(error){integrityFailures.push({type:'CAMPAIGN_SEAL_INVALID',message:error.message});}
  const runStart=safeObject(path.join(E,'campaign-run-start.json'),'CAMPAIGN_START_MALFORMED')??{};
  const runFinished=safeObject(path.join(E,'campaign-run-finished.json'),'CAMPAIGN_FINISH_MALFORMED')??{result:'FAILED_INCOMPLETE',failure:'CAMPAIGN_FINISH_MALFORMED',noFurtherProductExecution:true};
  const observerCorrectionReceipt=safeObject(topologyObserverCorrectionReceiptPath,'OBSERVER_CORRECTION_RECEIPT_MALFORMED')??{};
  const hHarnessCorrectionReceipt=safeObject(hHarnessCorrectionReceiptPath,'H_HARNESS_CORRECTION_RECEIPT_MALFORMED')??{};
  const h2HarnessCorrectionReceipt=safeObject(h2HarnessCorrectionReceiptPath,'H2_HARNESS_CORRECTION_RECEIPT_MALFORMED')??{};
  const preservedFailedFullReceipt=safeObject(failedFullReceiptPath,'PRESERVED_FAILED_FULL_RECEIPT_MALFORMED')??{};
  const correctedBGateReceipt=safeObject(correctedBGateReceiptPath,'CORRECTED_B_GATE_RECEIPT_MALFORMED')??{};
  const preservedFailedBGateReceipt=safeObject(historicalFailedBGateReceiptPath,'PRESERVED_FAILED_B_GATE_RECEIPT_MALFORMED')??{};
  try{assert.deepEqual(runStart.seal,record(path.join(E,'campaign-seal.json')));assert.equal(runStart.candidate,HEAD);assert.equal(runStart.singleExecution,true);}catch(error){integrityFailures.push({type:'CAMPAIGN_START_BINDING_INVALID',message:error.message});}
  const closeBindings=['tools','dependencies','fixtureBindings','candidateMembers','preparedBindings','inputs'].flatMap(key=>Array.isArray(seal[key])?seal[key]:(integrityFailures.push({type:'CAMPAIGN_SEAL_ARRAY_INVALID',field:key}),[]));
  if(!seal.prerequisiteChain||typeof seal.prerequisiteChain!=='object'||Array.isArray(seal.prerequisiteChain))integrityFailures.push({type:'CAMPAIGN_SEAL_PREREQUISITE_CHAIN_INVALID'});else for(const [name,entry] of Object.entries(seal.prerequisiteChain)){if(!entry||typeof entry.root!=='string'||!Array.isArray(entry.members))integrityFailures.push({type:'CAMPAIGN_SEAL_PREREQUISITE_ENTRY_INVALID',name});else closeBindings.push(...entry.members);}
  for(const b of closeBindings){try{check(b);}catch{integrityFailures.push({type:'SEALED_INPUT_CHANGED',binding:b});}}
  const sourceNow=safeWalk(path.join(root,'repositories/memoryos-readiness'),'SOURCE_WALK_FAILED'),installedNow=safeWalk(packageRoot,'INSTALLED_WALK_FAILED');
  const sourceUnchanged=JSON.stringify(sourceNow)===JSON.stringify(baselineSource),installedUnchanged=JSON.stringify(installedNow)===JSON.stringify(baselineInstalled);
  const historicalBefore=safeObject(path.join(E,'historical-before.json'),'HISTORICAL_BASELINE_MALFORMED')??{},history=safeArrayField(historicalBefore,'members','HISTORICAL_BASELINE_MEMBERS_SCHEMA',path.join(E,'historical-before.json'));
  const historicalChanged=history.filter(b=>{try{const actual=record(b.absolutePath);return actual.byteLength!==b.byteLength||actual.sha256!==b.sha256;}catch{return true;}});
  const candidateIdentity=safeObject(path.join(E,'candidate-identity.json'),'CANDIDATE_IDENTITY_MALFORMED')??{};
  const archive=candidateIdentity.archive&&typeof candidateIdentity.archive==='object'&&!Array.isArray(candidateIdentity.archive)?candidateIdentity.archive:(integrityFailures.push({type:'CANDIDATE_ARCHIVE_SCHEMA',path:rel+'/candidate-identity.json',message:'Expected archive object'}),{});try{check(archive);}catch{integrityFailures.push({type:'ARCHIVE_CHANGED',binding:archive});}
  const runtimeReceipt=safeObject(path.join(E,'runtime.json'),'RUNTIME_RECEIPT_MALFORMED')??{};
  const installedBeforeBinding=safeRecord(path.join(E,'installed-before.json'),'INSTALLED_BEFORE_BINDING_MISSING');
  const inventoryBinding=safeRecord(inventoryPath,'INVENTORY_BINDING_MISSING'),sealBinding=safeRecord(path.join(E,'campaign-seal.json'),'CAMPAIGN_SEAL_BINDING_MISSING'),runStartBinding=safeRecord(path.join(E,'campaign-run-start.json'),'CAMPAIGN_START_BINDING_MISSING'),runFinishedBinding=safeRecord(path.join(E,'campaign-run-finished.json'),'CAMPAIGN_FINISH_BINDING_MISSING');
  const historicalPhase3BR2DeltaBinding=safeRecord(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/phase3br2-binding-delta.json'),'HISTORICAL_PHASE3BR2_DELTA_BINDING_MISSING'),historicalPhase3CR2DeltaBinding=safeRecord(path.join(root,'repositories/cca-conformance/evidence/mo1307/prospective-helper-aggregate-bound-v2-candidate/phase3cr2-aggregate-delta.json'),'HISTORICAL_PHASE3CR2_DELTA_BINDING_MISSING');
  const reportPath=path.join(root,'docs/mo1307-phase3ar2-final-h3-corrected.md'),reportPreexisting=fs.existsSync(reportPath);if(reportPreexisting)integrityFailures.push({type:'REPORT_PATH_PREEXISTING',path:path.relative(root,reportPath).replaceAll('\\','/')});
  const productionDiff=git('diff','--name-only',HEAD,'--','repositories/memoryos-readiness').toString();
  const noProductionMutation=sourceUnchanged&&productionDiff==='';
  const results=steps.map(step=>{const p=path.join(E,'steps',step+'.json'),schedulerPath=path.join(E,'scheduler',step+'-receipt.json');if(fs.existsSync(p)){const data=safeObject(p,'STEP_RECEIPT_MALFORMED'),scheduler=fs.existsSync(schedulerPath)?safeObject(schedulerPath,'SCHEDULER_RECEIPT_MALFORMED'):null,stepBinding=safeRecord(p,'STEP_RECEIPT_BINDING_MISSING'),schedulerBinding=fs.existsSync(schedulerPath)?safeRecord(schedulerPath,'SCHEDULER_RECEIPT_BINDING_MISSING'):null;if(!data)return {step,result:'FAIL',failure:{reason:'Malformed step receipt'},binding:stepBinding,scheduler:scheduler?{...scheduler,binding:schedulerBinding}:null};const identityMatches=data.step===step&&scheduler?.step===step,result=data.result==='PASS'&&scheduler?.result==='PASS'&&identityMatches?'PASS':'FAIL';return {step,...data,result,binding:stepBinding,scheduler:scheduler?{...scheduler,binding:schedulerBinding}:null,...(!identityMatches?{closeFailure:{reason:'Step/scheduler identity mismatch',expectedStep:step,stepReceiptStep:data.step??null,schedulerStep:scheduler?.step??null}}:{})};}if(fs.existsSync(schedulerPath)){const scheduler=safeObject(schedulerPath,'SCHEDULER_RECEIPT_MALFORMED');return {step,result:'FAIL',failure:{reason:'No complete step receipt',scheduler},binding:safeRecord(schedulerPath,'SCHEDULER_RECEIPT_BINDING_MISSING')};}return {step,result:'NOT_RUN',reason:'Stopped at first mandatory failure'};});
  const sealedInventory=safeObject(inventoryPath,'SEALED_INVENTORY_MALFORMED')??{};
  const inventorySteps=safeArrayField(sealedInventory,'steps','SEALED_INVENTORY_STEPS_SCHEMA',inventoryPath);
  const expectedCaseIds={};
  for(const step of steps){const row=inventorySteps.find(item=>item&&typeof item==='object'&&item.step===step),cases=safeArrayField(row,'cases','SEALED_INVENTORY_CASES_SCHEMA',inventoryPath);expectedCaseIds[step]=cases.map(item=>typeof item?.case==='string'?item.case:null).filter(Boolean);if(expectedCaseIds[step].length!==cases.length)integrityFailures.push({type:'SEALED_INVENTORY_CASE_ID_SCHEMA',step});}
  const passingNames=(relative,field)=>{if(!exists(relative))return [];const file=path.join(E,relative),data=safeObject(file,'CASE_RECEIPT_MALFORMED'),rows=safeArrayField(data,field,'CASE_RECEIPT_ROWS_SCHEMA',file);return validNamedRows(rows,'CASE_RECEIPT_ROW_SCHEMA',relative).filter(row=>row.result==='PASS').map(row=>row.name);};
  const completedCaseIds=step=>{
    const stepResult=results.find(row=>row.step===step);
    if('ABCDEO'.includes(step))return stepResult?.result==='PASS'?[...expectedCaseIds[step]]:[];
    if(step==='F'||step==='G'){if(stepResult?.result==='NOT_RUN')return [];const rows=Array.isArray(stepResult?.cases)?stepResult.cases:(integrityFailures.push({type:'STEP_CASES_SCHEMA',step}),[]);return validNamedRows(rows,'STEP_CASE_ROW_SCHEMA',step).filter(row=>row.result==='PASS').map(row=>row.name);}
    if(step==='H'||step==='I')return passingNames('runtime-'+step+'/receipt.json','cases');
    if(step==='J')return stepResult?.result==='PASS'?[...expectedCaseIds.J]:[];
    if(step==='K')return passingNames('finalization/receipt.json','cases');
    if(step==='L'||step==='M')return passingNames('security-'+step+'/receipt.json','rows');
    if(step==='N'&&stepResult?.result==='PASS'&&exists('determinism/receipt.json')){const file=path.join(E,'determinism/receipt.json'),receipt=safeObject(file,'DETERMINISM_RECEIPT_MALFORMED'),vectors=validNamedRows(safeArrayField(receipt,'vectors','DETERMINISM_VECTORS_SCHEMA',file),'DETERMINISM_VECTOR_ROW_SCHEMA','determinism/receipt.json');return receipt?.result==='PASS'&&vectors.length===5&&vectors.every(row=>row.result==='PASS')?[...expectedCaseIds.N]:[];}
    return [];
  };
  const caseCompletion=steps.map(step=>{const stepResult=results.find(row=>row.step===step),expected=expectedCaseIds[step],completedCases=completedCaseIds(step),exact=JSON.stringify(completedCases)===JSON.stringify(expected);return {step,expected,completed:completedCases,remaining:expected.filter(name=>!completedCases.includes(name)),result:exact&&stepResult?.result==='PASS'?'PASS':stepResult?.result==='NOT_RUN'?'NOT_RUN':'FAIL_OR_INCOMPLETE'};});
  const observations=safeWalk(E,'EVIDENCE_WALK_FAILED').filter(x=>x.path.endsWith('/observation.json')).map(x=>{const file=path.join(E,x.path),data=safeObject(file,'OBSERVATION_MALFORMED');if(data&&!Array.isArray(data.requests))integrityFailures.push({type:'OBSERVATION_REQUESTS_SCHEMA',path:x.path,message:'Expected requests array'});if(Array.isArray(data?.requests))for(const [index,row] of data.requests.entries())if(!row||typeof row!=='object'||Array.isArray(row))integrityFailures.push({type:'OBSERVATION_REQUEST_ROW_SCHEMA',path:x.path,index,message:'Expected a request object'});return {binding:safeRecord(file,'OBSERVATION_BINDING_MISSING'),data};});
  const native=observations.map(({binding,data:d})=>d&&Array.isArray(d.requests)?{binding,pid:d.pid,exit:d.productExit,productLifecycleElapsedMs:d.productLifecycleElapsedMs,maxRssKiB:d.maxRssKiB,requests:d.requests.map(q=>q&&typeof q==='object'&&!Array.isArray(q)?{ordinal:q.ordinal,sequence:q.sequence,operation:q.operation,fileCount:q.fileCount,pid:q.pid,disposition:q.disposition,error:q.error,durationMs:q.durationMs,chargedThisExchangeMs:q.chargedThisExchangeMs,exitCode:q.exitCode,exitSignal:q.exitSignal,transportClosed:q.transportClosed,responseComplete:q.responseComplete,responseAcceptedByTransport:q.responseAcceptedByTransport}:{schemaFailure:true}),supervisors:d.supervisors,events:d.events}:{binding,parseOrSchemaFailure:true});
  const bindings=safeWalk(E,'EVIDENCE_BINDING_WALK_FAILED').map(row=>safeRecord(path.join(E,row.path),'EVIDENCE_MEMBER_BINDING_MISSING')).filter(Boolean);
  const externalTopologyBinding=exists('topology-B/receipt.json')?safeRecord(path.join(E,'topology-B/receipt.json'),'EXTERNAL_TOPOLOGY_BINDING_MISSING'):null,cleanupControlsBinding=exists('cleanup-topology/receipt.json')?safeRecord(path.join(E,'cleanup-topology/receipt.json'),'CLEANUP_CONTROLS_BINDING_MISSING'):null;
  const integrity={result:noProductionMutation&&installedUnchanged&&!historicalChanged.length&&!integrityFailures.length?'PASS':'FAIL',sourceUnchanged,installedUnchanged,installedMembers:installedNow.length,historicalFiles:history.length,historicalChanged,integrityFailures,productionDiff,noProductionMutation};
  write('integrity-after.json',integrity);
  write('resource-and-cleanup-observations.json',{limits:seal.limits,replacementHelperBoundH:'NOT_ESTABLISHED',hFailureClassification:'H_HARNESS_MARGIN_DEFECT',timelyHelperEngineeringEnvelope:{artificialEofDelayMs:0,maxMs:5000,deadlineMarginMs:4000,productDeadlineMs:9000},hHarnessCorrection:record(hHarnessCorrectionReceiptPath),h2FailureClassifications,aggregateHelperEngineeringEnvelope,h2HarnessCorrection:record(h2HarnessCorrectionReceiptPath),native,externalTopology:externalTopologyBinding,cleanupControls:cleanupControlsBinding,notes:'The <5000-ms timely-helper cap and the 5700-ms aggregate EOF delay are engineering envelopes, not product limits. Observed product cleanup confirmation is distinct from held-process-object external cleanup proof; unexecuted controls make no certification claim.'});
  bindings.push(record(path.join(E,'integrity-after.json')),record(path.join(E,'resource-and-cleanup-observations.json')));
  const completed=results.filter(r=>r.result==='PASS').map(r=>r.step),failed=results.find(r=>r.result==='FAIL'),unexecuted=results.filter(r=>r.result==='NOT_RUN').map(r=>r.step);
  const completedMandatoryCases=caseCompletion.reduce((sum,row)=>sum+row.completed.length,0);
  const remainingMandatoryCases=caseCompletion.flatMap(row=>row.remaining.map((name,index)=>({step:row.step,case:name,status:row.step===failed?.step&&index===0?'FAILED_OR_INCOMPLETE':'NOT_RUN'})));
  const allPassed=completed.length===15&&completedMandatoryCases===80&&caseCompletion.every(row=>row.result==='PASS')&&integrity.result==='PASS'&&runFinished.result==='ALL_STEPS_COMPLETED'&&!runFinished.failure&&!exists('generation-stopped.json');
  const concreteBlocker=allPassed?null:failed??runFinished.failure??(remainingMandatoryCases[0]??null)??{type:'INTEGRITY_BLOCKER',integrityFailures,sourceUnchanged,installedUnchanged,historicalChanged,noProductionMutation};
  assert.equal(allPassed||concreteBlocker!==null,true);
  const outcome=allPassed?'PHASE3AR2_ACCEPTED_FINAL_CANDIDATE':'PHASE3AR2_CONCRETE_BLOCKER';
  const handoffDisposition=allPassed
    ?'Exact C3VB Phase 3AR2 receipt is eligible as an immutable input to a later, independent Phase 3D. Phase 3D was not performed.'
    :'No Phase 3D handoff exists for this concrete-blocker Phase 3AR2 stream.';
  let acceptanceValidationBinding=null,phase3BR2DeltaBinding=null,phase3CR2DeltaBinding=null;
  if(allPassed){
    const oldC3TB='119e68bdcf0ffc906b4ca03a912aadcb25908346',oldC3T='65e24b2debdd70ecb8e52fbccbd6c101621f1917',oldProductionTree='324bf600b6cbfaa8564db27fce2d999711270cb8';
    const gitArtifact=(commit,file,byteLength,sha256,gitBlob)=>{const bytes=git('show',commit+':'+file),actual={commit,path:file,byteLength:bytes.length,sha256:hash(bytes),gitBlob:git('rev-parse',commit+':'+file).toString().trim()};assert.deepEqual(actual,{commit,path:file,byteLength,sha256,gitBlob});return actual;};
    const phase3BR2Accepted={
      commit:'4d92f0f21c9c3aad8202f4558d61b9229c7214fc',rerun:false,
      receipt:gitArtifact('4d92f0f21c9c3aad8202f4558d61b9229c7214fc','repositories/cca-conformance/evidence/mo1307/phase3br2-c3tb/certification-receipt.json',5277,'sha256:1c9ee7957dbc032b9b93b13cd98aeb8bf73253207cfa6d468af5e5cdbe0263bf','0a19da2f62fdf577743f8be7bb2a588536dfd9ca'),
      evidenceSeal:gitArtifact('4d92f0f21c9c3aad8202f4558d61b9229c7214fc','repositories/cca-conformance/evidence/mo1307/phase3br2-c3tb/evidence-seal.json',23631,'sha256:c9f78b56f172eb940ced16868c8f34352e55a473da2dfccf8abd0cdf4c41539b','053f5a434e47d0e2dcaf8690b3555219c309202b'),
      finalValidation:gitArtifact('4d92f0f21c9c3aad8202f4558d61b9229c7214fc','repositories/cca-conformance/evidence/mo1307/phase3br2-c3tb/final-validation.json',3103,'sha256:9db2331140dfcfd39098c16e49cea67ef671d5ea89424e2cf5384dcd676de2ab','5b93c28405e3ab21f2a7580cc3a8f32d13073535')
    };
    const phase3CR2Accepted={
      commit:'7d2006c6e19bb50bffb6c710672be996e3c3590b',rerun:false,
      receipt:gitArtifact('7d2006c6e19bb50bffb6c710672be996e3c3590b','repositories/cca-conformance/evidence/mo1307/phase3cr2-c3tb-g7/certification-receipt.json',425464,'sha256:7066132bb79578e06eb9e1d2aa1a9471854f33f36709f8f3a01ad11ef6add7e7','3d3173b634b36108beffbea197c07f84cf3d5c63'),
      finalSeal:gitArtifact('7d2006c6e19bb50bffb6c710672be996e3c3590b','repositories/cca-conformance/evidence/mo1307/phase3cr2-c3tb-g7/final-seal.json',409970,'sha256:bb8a78b0336c45f13f108b817290a75f7cc6b4c11f831dc82c55415eb343e77f','64ea847859d5b26317037de1026eac258e3b66ea'),
      finalValidation:gitArtifact('7d2006c6e19bb50bffb6c710672be996e3c3590b','repositories/cca-conformance/evidence/mo1307/phase3cr2-c3tb-g7/final-validation.json',25361,'sha256:96ead677c255df7a3d95b6bb41402367ad9c210e350e8e34bd015470efb8e6ce','0a1507b0dcf45b3f656393202a65babaaff1f82e')
    };
    assert.equal(git('rev-parse',oldC3TB+':repositories/memoryos-readiness').toString().trim(),oldProductionTree);assert.equal(git('rev-parse',HEAD+':repositories/memoryos-readiness').toString().trim(),seal.productionTree);
    const changedSpecifications=[
      ['README.md',6022,'630e47271992519eba8776c730f8d2800b3ad8d9e3cf67b582cc9efc86d1c418','164b8bf94a35b036de5e7f136ffdda41739d6d4e78f225f7482ab2619ed1e6a6'],
      ['contracts/contract.json',7981,'c86fabf739d8073ec8fa39a17795f904d5c429da7858dafe25583d2ca4b4efdc','d2b599026d9e44cc629567e351b9a8b5ff8fcfef80d2c14810c4bfc27bf426ad'],
      ['contracts/definitions.json',16555,'4457989aded2dd4a6ff58dc1b14fafa12b9e3f597d1e8dfe40698e8289c60a66','4d031fff7ade1abe513086bb384a5e3a0428e35c2e57a7d755b0accb68891ac7'],
      ['distribution-manifest.json',12631,'91dc9624de1b89b5d83bdf795ccbc0f745b41d958fc8c1dd7abb997f0f88d73c','bfc879d7fa1511a1c3216ba4b22c815af056f5c19b552ed23defb4f2d7067f10'],
      ['helpers/README.md',null,'038e931e9919d652291ba43651071e8aa9bf8204d49789ebbf5b1a7a715e0f44','db3b27c33835356499c5c63e035c986333c3d7c9adc27929c0c190b4643d60c5'],
      ['sbom.spdx.json',47328,'1510fdb9c0366023b4e49b81ce20cceeb1527a1dfaa2f7b4ded52a9bff737fda','c0e4ca54e7e2a9ae83b1824eaa47d596985042434c67bc6bb596736ec680efe3'],
      ['src/constants.mjs',16791,'e4ac8f64d2d0d610d1ff00e46da5a4773dbcbd5e33d0cc5cd83b317be2c7a409','98e8721dedc01b593aca81d524e076cc0fe3936a03955198ff2a91ca5c163be1']
    ];
    const transition=baselineSource.map(current=>{const repoPath='repositories/memoryos-readiness/'+current.path,oldBytes=git('show',oldC3TB+':'+repoPath),newBytes=git('show',HEAD+':'+repoPath),oldBinding={commit:oldC3TB,path:repoPath,byteLength:oldBytes.length,sha256:hash(oldBytes)},newBinding={commit:HEAD,path:repoPath,byteLength:newBytes.length,sha256:hash(newBytes)};assert.equal(newBinding.sha256,current.sha256);assert.equal(newBinding.byteLength,current.byteLength);return {path:current.path,changed:oldBinding.sha256!==newBinding.sha256,before:oldBinding,after:newBinding};});
    const changedDependencySet=transition.filter(row=>row.changed),unchangedDependencySet=transition.filter(row=>!row.changed);assert.equal(changedDependencySet.length,7);assert.equal(unchangedDependencySet.length,82);assert.deepEqual(changedDependencySet.map(row=>row.path),changedSpecifications.map(row=>row[0]));
    for(const [file,byteLength,oldSha,newSha] of changedSpecifications){const row=changedDependencySet.find(item=>item.path===file);if(byteLength!==null){assert.equal(row.before.byteLength,byteLength);assert.equal(row.after.byteLength,byteLength);}assert.equal(row.before.sha256,'sha256:'+oldSha);assert.equal(row.after.sha256,'sha256:'+newSha);}
    assert.equal(transition.filter(row=>row.path.startsWith('schemas/')).length,52);assert.ok(transition.filter(row=>row.path.startsWith('schemas/')).every(row=>!row.changed));
    const generatedPaths=['contracts/definitions.json','contracts/contract.json','distribution-manifest.json','sbom.spdx.json','src/constants.mjs'];
    const generatedBindings=generatedPaths.map(name=>changedDependencySet.find(row=>row.path===name));assert.ok(generatedBindings.every(Boolean));
    const runtimeH=json(path.join(E,'runtime-H/receipt.json')),timely=runtimeH.cases.find(row=>row.name==='timely-helper'),strictBoundary=record(path.join(E,'runtime-H/strict-9000-boundary.json'));assert.equal(runtimeH.result,'PASS');assert.equal(timely.result,'PASS');assert.ok(timely.elapsedMs<5000);assert.deepEqual(timely.engineeringElapsedEnvelope,{minMs:null,maxMs:5000,productDeadlineOverride:false});assert.deepEqual(runtimeH.strictBoundaryChecks.map(row=>[row.elapsedMs,row.actual]),[[8000,'PASS'],[8999,'PASS'],[9000,'MO1307_TIMEOUT']]);
    const aggregateCase=runtimeH.cases.find(row=>row.name==='aggregate-helper-exhaustion'),aggregateCalculation=record(path.join(E,'runtime-H/aggregate-calculation.json'));assert.equal(aggregateCase.result,'PASS');assert.equal(aggregateCase.error?.code,'MO1307_TIMEOUT');assert.equal(runtimeH.aggregateFixture.targetAbsent,true);assert.deepEqual(runtimeH.aggregateFixture.after,runtimeH.aggregateFixture.before);assert.deepEqual(runtimeH.inputFixture.after,runtimeH.inputFixture.before);
    const acceptanceValidation={kind:'MO1307Phase3AR2FinalAcceptanceValidation',version:'1.0.0',result:'PASS',createdAt:new Date().toISOString(),outcome,candidate:{name:'C3VB',commit:HEAD,productionCommit:seal.productionCommit,productionTree:seal.productionTree},steps:completed,allStepsPassed:true,completedMandatoryCases,allMandatoryCasesPassed:true,noRemainingMandatoryCases:remainingMandatoryCases.length===0,integrity:record(path.join(E,'integrity-after.json')),campaignSeal:record(path.join(E,'campaign-seal.json')),campaignRunFinished:record(path.join(E,'campaign-run-finished.json')),freshPackage:{archive:candidateIdentity.archive,packageIdentity:candidateIdentity.packageIdentity,members:candidateIdentity.members,installedInventory:record(path.join(E,'installed-before.json'))},hHarnessCorrection:record(hHarnessCorrectionReceiptPath),h2HarnessCorrection:record(h2HarnessCorrectionReceiptPath),runtimeH:record(path.join(E,'runtime-H/receipt.json')),strictBoundary,aggregate:{result:aggregateCase.result,error:aggregateCase.error,elapsedMs:aggregateCase.elapsedMs,calculation:aggregateCalculation,fixtureImmutable:true,targetAbsent:true},cleanup:record(path.join(E,'cleanup-topology/receipt.json')),noRetry:true,historicalEvidencePromoted:false,phase3DPerformed:false,push:false,tag:false};
    write('acceptance-validation.json',acceptanceValidation);acceptanceValidationBinding=record(path.join(E,'acceptance-validation.json'));
    write('phase3br2-final-binding-delta.json',{kind:'MO1307Phase3BR2FinalC3TBToC3VBBindingDelta',version:'1.0.0',result:'PASS',createdAt:new Date().toISOString(),preservedAcceptance:phase3BR2Accepted,from:{bindingCandidate:{name:'C3TB',commit:oldC3TB},productionCandidate:{name:'C3T',commit:oldC3T,tree:oldProductionTree},limits:{helperMs:8000,aggregateHelperActiveMs:20000,cliMs:30000,apiWorkerMs:10000,cleanupMs:2000},historicalCharacterizationH:'NOT_ESTABLISHED'},to:{bindingCandidate:{name:'C3VB',commit:HEAD},productionCandidate:{name:'C3V',commit:seal.productionCommit,tree:seal.productionTree},limits:{helperMs:9000,aggregateHelperActiveMs:28000,cliMs:30000,apiWorkerMs:10000,cleanupMs:2000},historicalCharacterizationH:'NOT_ESTABLISHED'},freshAcceptedPhase3A:{acceptanceValidation:acceptanceValidationBinding,archive:candidateIdentity.archive,packageIdentity:candidateIdentity.packageIdentity,installedMembers:89,installedInventory:record(path.join(E,'installed-before.json'))},changedDependencySet,unchangedDependencyCount:unchangedDependencySet.length,generatedBindings,historicalOutcomePromoted:false,fullPhase3BR2Rerun:false,productExecution:false,phase3DPerformed:false,push:false,tag:false});phase3BR2DeltaBinding=record(path.join(E,'phase3br2-final-binding-delta.json'));
    write('phase3cr2-final-binding-delta.json',{kind:'MO1307Phase3CR2FinalC3TBToC3VBChangedDependencyDelta',version:'1.0.0',result:'PASS',createdAt:new Date().toISOString(),preservedAcceptance:phase3CR2Accepted,from:{bindingCandidate:{name:'C3TB',commit:oldC3TB},productionCandidate:{name:'C3T',commit:oldC3T,tree:oldProductionTree},helperMs:8000,aggregateHelperActiveMs:20000},to:{bindingCandidate:{name:'C3VB',commit:HEAD},productionCandidate:{name:'C3V',commit:seal.productionCommit,tree:seal.productionTree},helperMs:9000,aggregateHelperActiveMs:28000},freshAcceptedPhase3A:{acceptanceValidation:acceptanceValidationBinding,archive:candidateIdentity.archive,packageIdentity:candidateIdentity.packageIdentity,installedInventory:record(path.join(E,'installed-before.json'))},changedDependencySet,generatedBindings,unchangedDependencyProof:{members:unchangedDependencySet.length,schemas:52,bindings:unchangedDependencySet},affectedResourceControls:{strictHelperBoundary:{expected:[[8000,'PASS'],[8999,'PASS'],[9000,'MO1307_TIMEOUT']],binding:strictBoundary},timelyHelper:{artificialEofDelayMs:0,engineeringMaxMs:5000,elapsedMs:timely.elapsedMs,result:timely.result},overDeadlineTimeout:true,lateSuccessRejected:true,cancelBeforeDuringAndBetween:true,cleanup:true,noOverlap:true,noRetry:true,aggregate:{accepted:'helperActiveMs < 28000',timeout:'helperActiveMs >= 28000',equality:'TIMEOUT'},runtimeH:record(path.join(E,'runtime-H/receipt.json')),cleanupReceipt:record(path.join(E,'cleanup-topology/receipt.json')),resourceCleanup:record(path.join(E,'resource-and-cleanup-observations.json'))},staticEquality:{helperRuntimeProtocolTransportAndWireBytesUnchanged:true,schemaBytesUnchanged:true,unchangedMemberCount:unchangedDependencySet.length},phase3CR2CampaignRerun:false,unrelatedSecurityControlsRerun:false,productExecution:false,historicalOutcomePromoted:false,phase3DPerformed:false,push:false,tag:false});phase3CR2DeltaBinding=record(path.join(E,'phase3cr2-final-binding-delta.json'));
    bindings.push(acceptanceValidationBinding,phase3BR2DeltaBinding,phase3CR2DeltaBinding);
  }
  const receipt={
    kind:allPassed?'MO1307Phase3AR2CertificationAcceptedReceipt':'MO1307Phase3AR2ConcreteBlockerReceipt',version:'1.0.0',createdAt:new Date().toISOString(),result:outcome,certificationPassed:allPassed,allMandatoryPassed:allPassed,
    candidate:{name:'C3VB',commit:HEAD,productionCommit:seal.productionCommit??null,productionTree:seal.productionTree??null},integrationAuthority:seal.integrationAuthority??null,helperAuthority:seal.helperAuthority??null,worktree:root,branch:'codex/mo1307-phase3ar2-c3ub',
    runtime:runtimeReceipt,package:candidateIdentity,installedMemberVerification:installedBeforeBinding,
    preCertificationBGate:seal.preCertificationBGate??null,preCertificationBGateResult:{result:correctedBGateReceipt.result??null,outcome:correctedBGateReceipt.outcome??null,semanticInvocations:correctedBGateReceipt.semanticInvocations??null,noRetry:correctedBGateReceipt.noRetry??null,helperUsedMs:correctedBGateReceipt.details?.helperUsedMs??null,productLifecycleElapsedMs:correctedBGateReceipt.details?.productLifecycleElapsedMs??null,maxima:correctedBGateReceipt.details?.maxima??null,publication:correctedBGateReceipt.details?.publication??null,cleanupConfirmed:correctedBGateReceipt.details?.cleanupConfirmed??null,topologyIdentity:correctedBGateReceipt.details?.topologyIdentity??null},
    preservedFailedPreCertificationBGate:seal.preservedFailedPreCertificationBGate??null,preservedFailedPreCertificationBGateResult:{result:preservedFailedBGateReceipt.result??null,outcome:preservedFailedBGateReceipt.outcome??null,semanticInvocations:preservedFailedBGateReceipt.semanticInvocations??null,failure:preservedFailedBGateReceipt.failure??null},
    topologyObserverCorrection:seal.topologyObserverCorrection??null,observerDefect:observerCorrectionReceipt.defect??null,syntheticObserverValidation:{result:observerCorrectionReceipt.result??null,policy:observerCorrectionReceipt.policy??null,cases:observerCorrectionReceipt.cases??null,execution:observerCorrectionReceipt.execution??null,security:observerCorrectionReceipt.security??null},hHarnessCorrection:seal.hHarnessCorrection??null,hFailureClassification:'H_HARNESS_MARGIN_DEFECT',hHarnessCorrectionResult:{result:hHarnessCorrectionReceipt.result??null,classification:hHarnessCorrectionReceipt.classification??null,correctedControl:hHarnessCorrectionReceipt.correctedControl??null,zeroProductValidation:hHarnessCorrectionReceipt.zeroProductValidation??null,execution:hHarnessCorrectionReceipt.execution??null},h2HarnessCorrection:seal.h2HarnessCorrection??null,h2FailureClassifications,aggregateHelperEngineeringEnvelope:seal.aggregateHelperEngineeringEnvelope??null,eventOrderingRule:seal.eventOrderingRule??null,preservedFailedHCorrectedGeneration:seal.preservedFailedHCorrectedGeneration??null,preservedFailedFullGeneration:seal.preservedFailedFullGeneration??null,preservedFailedFullResult:{result:preservedFailedFullReceipt.result??null,completed:preservedFailedFullReceipt.completed??null,h:preservedFailedFullReceipt.steps?.find?.(row=>row.step==='H')?.result??null,unexecuted:preservedFailedFullReceipt.unexecuted??null,resumed:false,rewritten:false},h3Rebinding:seal.h3Rebinding??null,preservedBlockedH2Generation:seal.preservedBlockedH2Generation??null,prerequisiteChain:seal.prerequisiteChain??null,
    inventory:inventoryBinding,seal:sealBinding,campaignRunStart:runStartBinding,campaignRunFinished:{...runFinished,binding:safeRecord(path.join(E,'campaign-run-finished.json'),'CAMPAIGN_FINISH_BINDING_MISSING')},acceptanceValidation:acceptanceValidationBinding,limits:seal.limits??null,historicalCharacterizationH:'NOT_ESTABLISHED',replacementHelperBoundH:'NOT_ESTABLISHED',timelyHelperEngineeringEnvelope:seal.timelyHelperEngineeringEnvelope??null,
    steps:results,caseCompletion,completedMandatoryCases,remainingMandatoryCases,completed,concreteBlocker,firstMandatoryFailure:concreteBlocker,unexecuted,resourceCleanup:record(path.join(E,'resource-and-cleanup-observations.json')),integrity:record(path.join(E,'integrity-after.json')),historicalEvidencePreserved:integrity.historicalChanged.length===0,historicalEvidencePromoted:false,diagnosticsRun:0,retries:0,replacementExecutions:0,
    preservedPhase3BR2:'4d92f0f21c9c3aad8202f4558d61b9229c7214fc',phase3BR2Rerun:false,phase3BR2Delta:phase3BR2DeltaBinding,historicalPhase3BR2Delta:historicalPhase3BR2DeltaBinding,preservedPhase3CR2:'7d2006c6e19bb50bffb6c710672be996e3c3590b',phase3CR2Rerun:false,phase3CR2ExecutedHere:false,phase3CR2Delta:phase3CR2DeltaBinding,historicalPhase3CR2Delta:historicalPhase3CR2DeltaBinding,phase3D:false,push:false,tag:false,determinism:results.find(r=>r.step==='N')?.result??'NOT_RUN',cliApiParity:results.filter(r=>'ABCDEO'.includes(r.step)).map(r=>({step:r.step,result:r.result,rows:r.rows??[]})),startedAt,finishedAt:new Date().toISOString(),evidenceMembers:bindings,handoffDisposition
  };
  write('certification-receipt.json',receipt);
  let handoff=null;
  if(allPassed){
    write('phase3d-handoff.json',{kind:'MO1307Phase3AR2ToPhase3DHandoff',version:'1.0.0',result:'READY_FOR_SEPARATE_PHASE3D_INTEGRATION',createdAt:new Date().toISOString(),candidate:receipt.candidate,authorities:[seal.helperAuthority,seal.integrationAuthority],packageIdentity:receipt.package.packageIdentity,installedMemberCount:receipt.package.members,installedMemberVerification:record(path.join(E,'installed-before.json')),inventory:record(inventoryPath),seal:record(path.join(E,'campaign-seal.json')),acceptanceValidation:acceptanceValidationBinding,certificationReceipt:record(path.join(E,'certification-receipt.json')),phase3AR2Result:outcome,hFailureClassification:'H_HARNESS_MARGIN_DEFECT',hHarnessCorrection:seal.hHarnessCorrection,h2FailureClassifications,h2HarnessCorrection:seal.h2HarnessCorrection,preservedFailedHCorrectedGeneration:seal.preservedFailedHCorrectedGeneration,preservedFailedFullGeneration:seal.preservedFailedFullGeneration,topologyObserverCorrection:seal.topologyObserverCorrection,preCertificationBGate:seal.preCertificationBGate,preservedFailedPreCertificationBGate:seal.preservedFailedPreCertificationBGate,prerequisiteChain:seal.prerequisiteChain,preservedPhase3BR2:{commit:'4d92f0f21c9c3aad8202f4558d61b9229c7214fc',rerun:false,finalDelta:phase3BR2DeltaBinding},preservedPhase3CR2:{commit:'7d2006c6e19bb50bffb6c710672be996e3c3590b',rerun:false,executedHere:false,finalDelta:phase3CR2DeltaBinding},requiredBeforePhase3D:['PRESERVED_FAILED_FULL_GENERATION','ZERO_PRODUCT_H_HARNESS_MARGIN_CORRECTION','PRESERVED_FAILED_H_CORRECTED_GENERATION','ZERO_PRODUCT_H2_HARNESS_CORRECTION','PRESERVED_BLOCKED_H2_GENERATION','ZERO_PRODUCT_H3_REBINDING','FRESH_PHASE3AR2_ACCEPTANCE','PRESERVED_PHASE3BR2_ACCEPTANCE_AND_FINAL_DELTA','PRESERVED_PHASE3CR2_ACCEPTANCE_AND_FINAL_DELTA'],phase3DPerformed:false,push:false,tag:false,commit:null,commitBinding:'The local certification commit containing these already-existing immutable bytes is reported externally; a Git object cannot embed its own future commit hash.'});
    handoff=record(path.join(E,'phase3d-handoff.json'));
  }
  const defect=observerCorrectionReceipt.defect??{},bDetails=correctedBGateReceipt.details??{},bMaxima=bDetails.maxima??{};
  const correctionAcceptedExactly=Array.isArray(observerCorrectionReceipt.cases?.acceptedExactly)?observerCorrectionReceipt.cases.acceptedExactly:[],correctionFailedClosedExactly=Array.isArray(observerCorrectionReceipt.cases?.failedClosedExactly)?observerCorrectionReceipt.cases.failedClosedExactly:[];
  const lines=[
    '# MO-1307 Phase 3AR2 native Windows installed-runtime certification','',
    `**${outcome}.**`,'',
    `Candidate: C3VB \`${HEAD}\`; production commit C3V \`${seal.productionCommit}\`; production tree \`${seal.productionTree}\`.`,
    `Authorities: preserved helper \`${seal.helperAuthority}\`; aggregate \`${seal.integrationAuthority}\`. Worktree: \`${root}\`; branch: \`codex/mo1307-phase3ar2-c3ub\`.`,
    '',
    '## H harness correction','',
    'Exact H failure cause: the preserved generation artificially withheld helper stdin EOF for 8200 ms, leaving only 774.3405 ms after stdin settlement before the immutable 9000-ms product deadline; the real lifecycle reached 9036.9764 ms and correctly returned MO1307_TIMEOUT.',
    'Classification: `H_HARNESS_MARGIN_DEFECT` (not a product-deadline defect and not an expectation/authority conflict).',
    'Exact harness correction: only timely-helper changed from `{eofDelayMs:8200,minMs:8000,maxMs:9000}` to `{eofDelayMs:0,maxMs:5000}`. The <5000-ms value is an engineering envelope with 4000 ms of deadline headroom; the product authority remains strict success `<9000` and timeout `>=9000`.',
    `Zero-execution harness validation: ${hHarnessCorrectionReceipt.zeroProductValidation??'MISSING'}; product/helper/worker/native-observer/certification runs ${hHarnessCorrectionReceipt.execution?.productRuns??'?'}/${hHarnessCorrectionReceipt.execution?.helperRuns??'?'}/${hHarnessCorrectionReceipt.execution?.workerRuns??'?'}/${hHarnessCorrectionReceipt.execution?.nativeObserverRuns??'?'}/${hHarnessCorrectionReceipt.execution?.certificationRuns??'?'}. The exact 8000 PASS, 8999 PASS, 9000 TIMEOUT controls and all timeout/late/cancel/cleanup/no-overlap/no-retry controls were structurally preserved.`,
    `Preserved failed generation: ${preservedFailedFullReceipt.completed?.join('-')??'A-G'} PASS, H ${preservedFailedFullReceipt.steps?.find?.(row=>row.step==='H')?.result??'FAIL'}, ${preservedFailedFullReceipt.unexecuted?.join('-')??'I-O'} NOT_RUN; resumed false, rewritten false, promoted false.`,
    '',
    '## H2 harness correction','',
    'Exact H2 failure cause: in the preserved H-corrected generation, aggregate-helper-exhaustion expected MO1307_TIMEOUT but returned MO1307_FILESYSTEM_BOUNDARY at 23579.1962 ms (five helpers, one worker, 23257.1216 ms charged). The harness had placed the absent-output CHECK_OUTPUT target beneath the live runtime-H evidence directory; harness evidence writes changed that parent directory byteLength from 16384 (slot 4) to 24576 (slot 5) with the same file ID, and the product correctly rejected the changed stable-identity chain.',
    'Classifications: `H_AGGREGATE_FIXTURE_INPUT_ISOLATION_DEFECT` (harness; not product, not authority) and, for the independent PID 2124 `LIFETIME_CONTRADICTION`, `H_OBSERVER_EVENT_ORDERING_DEFECT` (the observer advanced lastSeenAt from a snapshot row after the held process object had already recorded its exit time).',
    'Exact harness corrections: the absent-output parent and the READ_SET input root are pre-created, sealed, quiescent fixture roots outside every evidence, cache and report write path; the aggregate control uses a 5700-ms engineering EOF delay, at most five helpers, and no publication-state mutation, so the unchanged 28000-ms product aggregate deadline terminates the fifth (CHECK_OUTPUT) helper; the observer advances lastSeenAt only while the exact held object reports exitTime100ns == 0 (`MO1307_OBSERVER_EVENT_ORDERING@1.0.0`). Product code, identity policy, expectations and limits are unchanged.',
    `Zero-product H2 validation: ${h2HarnessCorrectionReceipt.zeroProductValidation??'MISSING'}; product/helper/worker/native-observer/certification runs ${h2HarnessCorrectionReceipt.execution?.productRuns??'?'}/${h2HarnessCorrectionReceipt.execution?.helperRuns??'?'}/${h2HarnessCorrectionReceipt.execution?.workerRuns??'?'}/${h2HarnessCorrectionReceipt.execution?.nativeObserverRuns??'?'}/${h2HarnessCorrectionReceipt.execution?.certificationRuns??'?'} (${seal.h2HarnessCorrection?.sha256??'MISSING'}).`,
    'Preserved H-corrected generation: A-G PASS, H FAIL, I-O NOT_RUN; resumed false, rewritten false, promoted false.',
    '',
    '## Topology-observer correction','',
    `Exact defect: the historical B observer re-queried already-authenticated helper PID ${defect.pid??'UNKNOWN'} (parent PID ${defect.parentPid??'UNKNOWN'}) after signal activity; ${defect.operation??'QueryFullProcessImageNameW'} returned Win32 error ${defect.winerror??'UNKNOWN'} and was incorrectly counted as a fresh unknown identity.`,
    `Correction: policy \`${observerCorrectionReceipt.policy??'UNKNOWN'}\` preserves a same-session prior positive PID/role/parent/image/lifetime binding only when every no-reuse, timing, object-identity, and contradiction check passes. Initial unknown identity, parent/image contradiction, PID replacement, and unrelated errors remain fail-closed.`,
    `Synthetic observer validation: ${observerCorrectionReceipt.result??'MISSING'}; A-G ${observerCorrectionReceipt.cases?.passed??0}/7, accepted exactly ${correctionAcceptedExactly.join('/')||'none'}, failed closed exactly ${correctionFailedClosedExactly.join('/')||'none'}, product/helper/native-observer runs ${observerCorrectionReceipt.execution?.productRuns??'?'}/${observerCorrectionReceipt.execution?.helperRuns??'?'}/${observerCorrectionReceipt.execution?.nativeObserverRuns??'?'}.`,
    `Preserved historical failed B: ${preservedFailedBGateReceipt.result??'MISSING'}, exactly ${preservedFailedBGateReceipt.semanticInvocations??'?'} semantic invocation (${seal.preservedFailedPreCertificationBGate?.sha256??'MISSING'}).`,
    `Corrected pre-certification B: ${correctedBGateReceipt.result??'MISSING'}, READY, exit 0, 9/9 helpers, helper-active ${bDetails.helperUsedMs??'?'} ms, CLI lifecycle ${bDetails.productLifecycleElapsedMs??'?'} ms, cleanup ${bDetails.cleanupConfirmed===true?'confirmed':'not confirmed'}, publication ${bDetails.publication?.phase??'UNKNOWN'}, topology maxima ${bMaxima.productRoles??'?'} product roles / ${bMaxima.helpers??'?'} helper / ${bMaxima.helperConsoles??'?'} console, RSS ${bMaxima.productWorkingSetBytes??'?'} bytes, unresolved identities ${bDetails.topologyIdentity?.unresolvedIdentityFailures??'?'}. Exactly one invocation; no retry (${seal.preCertificationBGate?.sha256??'MISSING'}).`,
    '',
    `Fresh offline package: \`${archive.sha256??'MISSING'}\`, ${archive.byteLength??'MISSING'} bytes. Exactly 89 installed members and zero external production dependencies verified byte-for-byte against C3VB before execution; post-run integrity ${integrity.result}.`,
    `Runtime: Node 24.21.0 win-x64, SHA-256 ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32; native Windows PowerShell ${receipt.runtime?.powershell?.powerShellVersion??'MISSING'}.`,
    `Mandatory inventory completed: ${completedMandatoryCases}/80 cases.`,'',
    '| Step | Result |','|---|---|',...results.map(r=>`| ${r.step} | ${r.result} |`),'',
    allPassed?'Every mandatory A-O step and all 80 cases completed successfully.':`Concrete blocker: ${JSON.stringify(concreteBlocker)}. Exact expected/actual case, errors, clocks, process state, integrity and cleanup state are retained in the receipt.`,
    `Phase 3A status: ${allPassed?'ACCEPTED FINAL CANDIDATE':'CONCRETE BLOCKER / INCOMPLETE'}; final A-O result ${outcome}.`,
    `Completed steps: ${completed.join(', ')||'none'}. Unexecuted steps: ${unexecuted.join(', ')||'none'}. Remaining mandatory cases: ${remainingMandatoryCases.length}.`,
    '',
    'Limits: whole-helper lifecycle success <9000 ms; timeout >=9000 ms; helper-active aggregate success <28000 ms and timeout >=28000 ms; CLI/rename admission ceiling 30000 ms; API/worker 10000 ms; cleanup 2000 ms. Historical H remains NOT_ESTABLISHED. No retry, grace, late-success recovery, helper/helper overlap, or helper/worker overlap.',
    '',
    `Historical evidence: ${history.length} tracked baseline files checked, ${historicalChanged.length} changed; none promoted. The complete failed-B, topology-correction, corrected-B, failed full-generation, zero-product H-correction, failed H-corrected generation, and zero-product H2-correction tool/evidence trees and the sealed H2 fixture roots are sealed and rechecked through closure. No diagnostic campaign, production change, push, tag, Phase 3BR2 rerun, Phase 3CR2 rerun, or Phase 3D execution.`,
    `Repository status: tracked production diff ${productionDiff===''?'clean':'CHANGED'}; source snapshot ${sourceUnchanged?'unchanged':'CHANGED'}; installed snapshot ${installedUnchanged?'unchanged':'CHANGED'}; local untracked harness/evidence/report artifacts are retained for the final evidence commit.`,
    `Preserved accepted Phase 3BR2 commit: \`4d92f0f21c9c3aad8202f4558d61b9229c7214fc\`; full rerun false; exact C3TB -> C3VB final binding delta ${receipt.phase3BR2Delta?.sha256??(allPassed?'MISSING':'NOT_CREATED_ON_BLOCKER')}.`,
    `Preserved accepted Phase 3CR2 commit: \`7d2006c6e19bb50bffb6c710672be996e3c3590b\`; full/unrelated-security rerun false; exact changed-dependency final delta ${receipt.phase3CR2Delta?.sha256??(allPassed?'MISSING':'NOT_CREATED_ON_BLOCKER')}.`,
    `CLI/API parity and cleanup claims are limited to retained completed observations. Byte determinism stage N: ${receipt.determinism}.`,
    '',
    `Receipt: [certification-receipt.json](../${rel}/certification-receipt.json). Evidence commit is not self-embedded and is reported externally after these immutable receipt bytes exist.`,
    `Sealed inventory: [recovered-inventory.json](../${rel}/recovered-inventory.json).`,
    `Resource/cleanup: [resource-and-cleanup-observations.json](../${rel}/resource-and-cleanup-observations.json).`,
    ...(handoff?[`Phase 3BR2 final delta: [phase3br2-final-binding-delta.json](../${rel}/phase3br2-final-binding-delta.json).`,`Phase 3CR2 final delta: [phase3cr2-final-binding-delta.json](../${rel}/phase3cr2-final-binding-delta.json).`]:[]),
    ...(handoff?[`Phase 3D handoff: [phase3d-handoff.json](../${rel}/phase3d-handoff.json).`]:[]),'',handoffDisposition,''
  ];
  let report=null,reportBinding=null,reportWriteFailure=null;
  if(!reportPreexisting){try{fs.writeFileSync(reportPath,lines.join('\n'),{flag:'wx'});report=reportPath;reportBinding=record(reportPath);}catch(error){reportWriteFailure={name:error.name,message:error.message,code:error.code??null};}}
  write('closure.json',{result:outcome,receipt:record(path.join(E,'certification-receipt.json')),acceptanceValidation:acceptanceValidationBinding,phase3BR2FinalDelta:phase3BR2DeltaBinding,phase3CR2FinalDelta:phase3CR2DeltaBinding,handoff,report:reportBinding,reportWriteFailure,integrity:record(path.join(E,'integrity-after.json')),commit:null,commitBinding:'Subsequent local evidence commit includes these already-existing bytes; no future self-hash is embedded.'});
  console.log(JSON.stringify({result:outcome,completed,concreteBlocker,unexecuted,integrity:integrity.result,receipt:record(path.join(E,'certification-receipt.json')),handoff,report,reportWriteFailure}));
}
