/** One isolated offline install and bounded installed smoke, with host interruption evidence. */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {queryEvents,classify} from '../mo1305-host-guard.mjs';
const root=resolve(import.meta.dirname,'../../../..');
const evidence='repositories/cca-conformance/evidence/mo1305-phase3-correction/accepted/';
const tooling='repositories/cca-conformance/tools/mo1305-phase3-correction/';
const python='C:/Users/melsa/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const node=resolve(root,'.cache/mo1304-phase3-toolchain/node-v24.21.0-win-x64/node.exe');
const npm=resolve(node,'../node_modules/npm/bin/npm-cli.js');
const sha=b=>createHash('sha256').update(b).digest('hex');
const ref=path=>{const b=readFileSync(resolve(root,path));return {path,byteLength:b.length,sha256:sha(b)};};
const paths=[...['install.py','installed-probe.mjs','distribution.py','spdx.py','package-allowlist.json','schema_validation.py','schema-runtime.json','execute.mjs'].map(n=>tooling+n),...['mo1305-host-guard.mjs','mo1305-host-events.ps1','mo1305-host-guard-policy.json','mo1305-phase1/validate-launch.ps1'].map(n=>'repositories/cca-conformance/tools/'+n),evidence+'source-tree.json'];
const inputs=paths.map(ref),archive=JSON.parse(readFileSync(resolve(root,evidence+'reproducibility.json'))).archive;
assert.deepEqual(ref(archive.path),archive);
process.env.PATH='C:/Windows/System32;C:/Windows/System32/WindowsPowerShell/v1.0';
const stamp=()=>({ns:process.hrtime.bigint().toString(),utcMs:Date.now(),domain:'MONOTONIC_RELEASE_CORRECTION_'+process.pid});
const start=stamp(),args=['-B','-X','utf8',resolve(root,tooling+'install.py'),'--archive',resolve(root,archive.path),'--node',node,'--npm',npm,'--expected-sha256',archive.sha256,'--output',resolve(root,evidence+'installed.json')];
const child=spawn(python,args,{cwd:root,env:process.env,windowsHide:true,stdio:['ignore','pipe','pipe']});
let bytes=Buffer.alloc(0),timeout=false;
const append=b=>{bytes=Buffer.concat([bytes,b]);if(bytes.length>1048576){timeout=true;child.kill();}};
child.stdout.on('data',append);child.stderr.on('data',append);
const timer=setTimeout(()=>{timeout=true;child.kill();},300000);
const result=await new Promise((done,fail)=>{child.once('error',fail);child.once('close',(code,signal)=>done({code,signal}));}).finally(()=>clearTimeout(timer));
const end=stamp(),events=await queryEvents(start.utcMs,end.utcMs),observation=classify({start,end,attemptId:'release-metadata-smoke',candidateId:archive.sha256,caseId:'installed-smoke',phase:'release-correction',index:0,sampleId:'release-metadata-smoke'},events);
const output=evidence+'installed-execution.log';writeFileSync(resolve(root,output),bytes,{flag:'wx'});
assert.deepEqual(paths.map(ref),inputs,'HARNESS_CHANGED');
const state=!timeout&&result.code===0&&observation.classification==='NORMAL'&&observation.evidenceState==='AVAILABLE'?'PASS':'FAIL';
writeFileSync(resolve(root,evidence+'execution.json'),JSON.stringify({kind:'MemoryOSRESTReleaseCorrectionExecution',version:'1.0.0',state,archive,inputs,start,end,host:{events,observation},result,timeout,log:ref(output),installed:existsSync(resolve(root,evidence+'installed.json'))?ref(evidence+'installed.json'):null}),{flag:'wx'});
process.stdout.write(JSON.stringify({state,result,host:observation.classification,evidenceState:observation.evidenceState})+'\n');
assert.equal(state,'PASS');
