// Exact correction implementation and binding child; no future-hash references.
import assert from 'node:assert/strict';
import {evidence,baseline,str,record,write,blobs,json,check,implementationSubject,bindingSubject} from './common.mjs';
assert.equal(str('branch','--show-current'),'main');
const inventoryPath=evidence+'/changed-file-inventory.json';
const allowed=p=>['repositories/memoryos-readiness/helpers/windows-inspect.ps1','repositories/memoryos-readiness/sbom.spdx.json','repositories/memoryos-readiness/distribution-manifest.json','docs/mo1307-phase3a-readset-correction.md','.gitattributes'].includes(p)||p.startsWith(evidence+'/')||p.startsWith('repositories/cca-conformance/tools/mo1307-phase3a-readset-correction/')||p.startsWith('repositories/cca-conformance/tests/mo1307_phase3a_readset_');
if(process.argv[2]==='inventory'){
 assert.equal(str('rev-parse','HEAD'),baseline);assert.equal(str('diff','--cached','--name-only'),'');assert.equal(json(evidence+'/final-validation/receipt.json').result,'PASS');
 const names=[...new Set([...str('diff','--name-only',baseline).split('\n'),...str('ls-files','--others','--exclude-standard').split('\n')].filter(Boolean))].sort();assert.ok(names.length>0);assert.ok(!names.includes(inventoryPath));for(const p of names)assert.ok(allowed(p),p);
 write(inventoryPath,{kind:'MO1307ReadSetCorrectionChangedFileInventory',version:'1.0.0',baseline,members:names.map(p=>record(p)),exclusions:['This inventory excludes itself. C3RB binds its actual C3R bytes and all changed implementation files.'],implementationSubject,bindingSubject,implementationIdentity:'Only bound after the actual C3R exists; no future hash.',certification:false});console.log(JSON.stringify({result:'PASS',members:names.length}));
}else if(process.argv[2]==='stage-check'){
 assert.equal(str('rev-parse','HEAD'),baseline);const members=[...json(inventoryPath).members,record(inventoryPath)].sort((a,b)=>a.path<b.path?-1:1);assert.deepEqual(str('diff','--cached','--name-only').split('\n').filter(Boolean).sort(),members.map(m=>m.path));assert.equal(str('diff','--name-only'),'');assert.equal(str('ls-files','--others','--exclude-standard'),'');const bytes=blobs('',members.map(m=>m.path));members.forEach((m,i)=>{check(m,bytes[i]);check(m);});console.log(JSON.stringify({result:'PASS',exactStagedBlobs:members.length}));
}else if(process.argv[2]==='bind'){
 const commit=str('rev-parse','HEAD');assert.deepEqual(str('show','-s','--format=%P',commit).split(' '),[baseline]);assert.equal(str('show','-s','--format=%s',commit),implementationSubject);assert.equal(str('status','--porcelain'),'');const names=str('diff-tree','--no-commit-id','--name-only','-r',commit).split('\n').filter(Boolean).sort(),bytes=blobs(commit,names);for(const p of names)assert.ok(allowed(p),p);
 write(evidence+'/binding.json',{kind:'MO1307ReadSetCorrectionBinding',version:'1.0.0',implementation:{commit,parent:baseline,tree:str('rev-parse',commit+'^{tree}'),subject:implementationSubject},members:names.map((p,i)=>record(p,bytes[i])),bindingSubject,productionChangesInBindingCommit:false,selfReference:'Only actual existing C3R commit/tree/blobs are bound. No future C3RB identity is embedded.',certification:false,followUp:'Independent targeted Phase3A/3B/3C refresh against actual C3RB is required.'});console.log(JSON.stringify({result:'PASS',C3R:commit,members:names.length}));
}else throw Error('Use inventory, stage-check or bind');