// Select the completed fixed correction evidence without replaying any campaign.
import assert from 'node:assert/strict';
import {evidence,json,record,write} from './common.mjs';
assert.equal(process.argv.length,2);
const receipt=p=>{const r=record(p);assert.equal(json(p).result,'PASS',p);return r;};
const packageReceipt=receipt(evidence+'/package/pass-1/receipt.json'),corpusReceipt=receipt(evidence+'/equivalence/attempt1/receipt.json');
const performanceReceipts=['mo1306-run1','mo1306-run2','mo1306-run3','ready-run1'].map(n=>receipt(evidence+'/performance/'+n+'/receipt.json'));
const cliReceipts=['mo1306','ready'].map(n=>receipt(evidence+'/cli-smoke/'+n+'/receipt.json'));
const regressionReceipts=['cheap','package','phase1-native','phase2c','phase2d','vectors'].map(group=>({group,receipt:receipt(evidence+'/regressions/'+group+'-attempt1/receipt.json')}));
const helpers=performanceReceipts.map(p=>{const r=json(p.path);assert.equal(r.snapshot.cleanupConfirmed,true);assert.equal(r.snapshot.activeRole,null);return{receipt:p,case:r.case,exchangeMs:r.exchangeMs,helperActiveMs:r.helperActiveMs,marginMs:r.marginMs,pid:r.snapshot.events.find(e=>e.type==='observation'&&e.role==='helper').pid,helpers:r.snapshot.helpers,workers:r.snapshot.workers,cleanupConfirmed:true};});
const cli=cliReceipts.map(p=>{const r=json(p.path);assert.ok(r.cleanupConfirmed&&r.processClosed&&r.inputClosed&&r.outputClosed&&r.errorClosed);return{receipt:p,case:r.case,exit:r.exit.code,elapsedMs:r.elapsedMs,directCliAndThreePipesClosed:true,sourceBoundHelperRequests:r.helperRequests,sourceBoundWorkers:r.workers,cleanupBasis:r.cleanupBasis};});
const corpus=json(corpusReceipt.path);assert.equal(corpus.cases.length,39);assert.ok(corpus.cases.every(c=>[c.b2,c.candidate].every(r=>r.code===0&&r.closeObserved&&r.pipesClosed)));
write(evidence+'/acceptance.json',{kind:'MO1307ReadSetCorrectionAcceptance',version:'1.0.0',result:'PASS',optimizationPasses:[1],packageReceipt,corpusReceipt,performanceReceipts,cliReceipts,regressionReceipts,diagnosticBinding:receipt(evidence+'/diagnostic-binding.json'),sourceReview:receipt(evidence+'/helper-security-review.json'),securityFreshness:receipt(evidence+'/security-freshness.json'),sourcePreservation:receipt(evidence+'/source-certification-after.json'),certificationImpact:record(evidence+'/certification-impact.json'),cleanup:{productHelpers:helpers,packagedCli:cli,corpusHelperInvocations:78,corpusExitAndCloseObserved:true,noAdditionalProcessCensusPerformed:true},countPolicy:'12 freshness cases plus5 additional native-final-path perturbations are17 controlled mutations;32 negative cases include them. Phase2C219 includes all57/24/24/7/13 subsets without double-counting.',historicalPhase3A:'CERTIFICATION_BLOCKED; ROOT_CAUSE_ESTABLISHED',historicalReadyFailureResolved:false,phase3B:'TARGETED_REFRESH_REQUIRED',phase3C:'TARGETED_REFRESH_REQUIRED',certification:false,compiledFrom:record('repositories/cca-conformance/tools/mo1307-phase3a-readset-correction/summarize.mjs')});
console.log(JSON.stringify({result:'PASS',regressions:[8,25,219,58],exactVectors:16,corpus:39,productHelperRuns:4,cliSmokes:2}));