// Execute each declared core vector once, with immediate stop on any mandatory failure.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {pathToFileURL} from 'node:url';
import {root,E,T,cache,packageRoot,HEAD,env,hash,json,record,walk,write,put,identity,canonical} from './common.mjs';
identity();const step=process.argv[2];assert.ok(['A','B','C','D','E','O'].includes(step));assert.equal(fs.existsSync(path.join(E,'generation-stopped.json')),false,'Generation already stopped');
const name={A:'mo1306-qualified',B:'ready',C:'not-ready',D:'could-not-evaluate',E:'rest-qualified',O:'mo1306-qualified'}[step];
const previous={B:'A',C:'B',D:'C',E:'D',O:'N'}[step];if(previous)assert.equal(json(path.join(E,'steps',previous+'.json')).result,'PASS');assert.equal(fs.existsSync(path.join(E,'steps',step+'.json')),false);assert.equal(fs.existsSync(path.join(E,'steps',step+'-start.json')),false,'This finite step was already started');
const vector=json(path.join(E,'vectors-prepared.json')).vectors.find(v=>v.name===name);const fixture=path.join(root,'repositories/cca-conformance/fixtures/mo1307/bundles',name),read=n=>fs.readFileSync(path.join(fixture,n));
const pins=JSON.parse(read('pins.json')),expected=read('expected-result.json'),result=JSON.parse(expected),manifest=JSON.parse(read('manifest.json'));const destination=path.join(vector.parent,step==='O'?'final':'primary');assert.equal(fs.existsSync(destination),false);
const expectedExit={READY:0,READY_WITH_QUALIFICATIONS:2,NOT_READY:3,COULD_NOT_EVALUATE:4}[result.assessment.readiness];const rows=[],before=walk(packageRoot);assert.deepEqual(before,json(path.join(E,'baseline.json')).installed);
const errorRecord=e=>({name:e.name,code:e.code??null,stage:e.stage??null,message:e.message,stack:e.stack});
function compare(bytes){assert.deepEqual(bytes,expected);assert.deepEqual(bytes,canonical(JSON.parse(bytes)));assert.equal(result.assessment.gates.length,22);return {canonicalBytes:true,byteLength:bytes.length,sha256:hash(bytes),gates:22,qualifications:result.assessment.qualifications.length,readiness:result.assessment.readiness,readinessDigest:result.readinessDigest,proofBindingDigest:result.proofBindingDigest,fields:['candidate','candidateDigest','profile','stage','gates','blockers','cneReasons','qualifications','history','providers','readiness','readinessDigest','proofBindingDigest','canonicalResultBytes']};}
function invoke(operation){const scope='semantics/'+step+'-'+name+'/'+operation,folder=path.join(E,scope);fs.mkdirSync(folder,{recursive:true});const trace=path.join(folder,'observation.json'),bin=path.join(packageRoot,'bin/memoryos-readiness.mjs');const args=[operation,'--input-root',vector.inputRoot,'--config','configuration.json','--authority','authority.json','--authority-sha256',pins.trustedAuthorityDigest,'--candidate-sha256',pins.expectedCandidateDigest,operation==='evaluate'?'--output-root':'--result-root',destination];const sampled=step==='B'&&operation==='evaluate',observerOutput=path.join(E,'topology-B'),observerReady=trace+'.observer-ready.json';const command=[path.join(T,'observer-entry.mjs'),trace,bin,...(sampled?['--observer-ready',observerReady]:[]),...args];
write(scope+'/invocation.json',{startedAt:new Date().toISOString(),generation:'FINAL_FINITE_CERTIFICATION',step,name,operation,executable:process.execPath,args:command,installedBin:bin,productArgs:args,cwd:path.join(cache,'cwd'),env,expectedExit:operation==='evaluate'?expectedExit:0,engineeringGuardMs:45000,noRetry:true,sourceBindings:['observer-entry.mjs','runtime-observer.mjs','transport-observer.mjs','errors-observer.mjs','core.mjs'].map(n=>record(path.join(T,n)))});
const start=performance.now();let r,observerReceipt=null;if(sampled){const python='C:/Users/melsa/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';const observerArgs=['-B',path.join(T,'observe-command.py'),'--output',observerOutput,'--ready',observerReady,'--cwd',path.join(cache,'cwd'),'--expected-exit',String(expectedExit),'--expected-helpers','9','--',process.execPath,...command];write(scope+'/observer-invocation.json',{executable:python,args:observerArgs,role:'ENGINEERING_SIBLING_SAMPLER',additionalSemanticExecutions:0});const wrapped=spawnSync(python,observerArgs,{cwd:root,env,windowsHide:true,shell:false,encoding:null,timeout:65000,maxBuffer:1024*1024});put(scope+'/observer-wrapper.stdout.data',wrapped.stdout??Buffer.alloc(0));put(scope+'/observer-wrapper.stderr.data',wrapped.stderr??Buffer.alloc(0));if(fs.existsSync(path.join(observerOutput,'receipt.json')))observerReceipt=json(path.join(observerOutput,'receipt.json'));r={status:observerReceipt?.driverExit??null,signal:wrapped.signal,error:wrapped.error,stdout:fs.existsSync(path.join(observerOutput,'driver.stdout.data'))?fs.readFileSync(path.join(observerOutput,'driver.stdout.data')):Buffer.alloc(0),stderr:fs.existsSync(path.join(observerOutput,'driver.stderr.data'))?fs.readFileSync(path.join(observerOutput,'driver.stderr.data')):Buffer.alloc(0)};}else{r=spawnSync(process.execPath,command,{cwd:path.join(cache,'cwd'),env,windowsHide:true,shell:false,encoding:null,timeout:45000,maxBuffer:1024*1024});}const row={step,name,operation,elapsedMs:performance.now()-start,exit:r.status,signal:r.signal,error:r.error?.code??null,stdout:put(scope+'/stdout.data',r.stdout??Buffer.alloc(0)),stderr:put(scope+'/stderr.data',r.stderr??Buffer.alloc(0)),result:'FAIL'};
try{assert.ifError(r.error);assert.equal(r.signal,null);if(sampled){assert.ok(observerReceipt,'Missing observer receipt');assert.equal(observerReceipt.result,'PASS','Scheduled topology/RSS witness failed');row.observer=record(path.join(observerOutput,'receipt.json'));}assert.equal(r.status,operation==='evaluate'?expectedExit:0,(r.stderr??Buffer.alloc(0)).toString());assert.equal(r.stderr.length,0);const observation=json(trace),sup=observation.supervisors[0]?.snapshot;row.observation=record(trace);assert.equal(observation.bootstrapError,null);assert.equal(observation.actualInstalledBinExecuted,true);assert.equal(observation.productExit,r.status);assert.equal(observation.supervisors.length,1);assert.equal(sup.helpers,operation==='evaluate'?9:4);assert.equal(observation.requests.length,sup.helpers);assert.deepEqual(observation.requests.map(q=>q.sequence),Array.from({length:sup.helpers},(_,i)=>i+1));assert.deepEqual(observation.requests.map(q=>q.operation),operation==='evaluate'?['READ_SET','READ_SET','READ_SET','CHECK_OUTPUT','CHECK_OUTPUT','INSPECT_OUTPUT_ROOT','CHECK_STAGE_ROOT','INSPECT_PENDING','CHECK_FINALIZATION']:['READ_SET','READ_SET','READ_SET','READ_SET']);assert.equal(observation.hookMatches.length,3);assert.equal(sup.workers,1);assert.equal(sup.cleanupConfirmed,true);assert.equal(sup.terminalCode,null);assert.ok(sup.helperUsedMs<20000);assert.ok(observation.productLifecycleElapsedMs<30000);assert.ok(observation.maxRssKiB*1024<=512*1024*1024);for(const q of observation.requests){assert.equal(q.disposition,'RESOLVED');assert.ok(q.durationMs<5000);assert.equal(q.exitCode,0);assert.equal(q.transportClosed,true);assert.equal(q.responseAcceptedByTransport,true);}if(operation==='evaluate'){assert.equal(sup.publication.phase,'COMMITTED');assert.equal(sup.publication.deadlineExpiredAfterAdmission,false);assert.equal(sup.publication.cancelledAfterAdmission,false);}const summary=JSON.parse(r.stdout);assert.equal(summary.readiness,result.assessment.readiness);assert.equal(summary.operation,operation);assert.equal(summary.readinessDigest,result.readinessDigest);assert.equal(summary.proofBindingDigest,result.proofBindingDigest);assert.equal(summary.decision,null);row.parity=compare(fs.readFileSync(path.join(destination,'memoryos-readiness-result.json')));assert.deepEqual(fs.readdirSync(destination),['memoryos-readiness-result.json']);row.helperUsedMs=sup.helperUsedMs;row.productLifecycleElapsedMs=observation.productLifecycleElapsedMs;row.result='PASS';return row;}catch(error){row.failure=errorRecord(error);throw error;}finally{rows.push(row);write(scope+'/receipt.json',row);}}
let failure=null;
try{
 write('steps/'+step+'-start.json',{step,name,startedAt:new Date().toISOString(),expectedExit,expectedReadiness:result.assessment.readiness,destination,noRetry:true});
 invoke('evaluate');invoke('verify');
 const api=await import(pathToFileURL(path.join(packageRoot,'src/index.mjs')).href);
 const input={configurationBytes:read('configuration.json'),candidateBytes:read('candidate.json'),authorityBytes:read('authority.json'),manifestBytes:read('manifest.json'),files:manifest.entries.map(x=>({id:x.id,bytes:read(x.path)})),expectedCandidateDigest:pins.expectedCandidateDigest,trustedAuthorityDigest:pins.trustedAuthorityDigest};
 const apiRow={name,operation:'api',result:'FAIL',expectedReadiness:result.assessment.readiness,expectedResult:{sha256:hash(expected),byteLength:expected.length},currentOperation:'evaluate'};
 let apiStarted=performance.now();
 try{
  const evaluated=await api.evaluateReadiness(input);apiRow.evaluateMs=performance.now()-apiStarted;
  apiRow.evaluateBytes=put('semantics/'+step+'-'+name+'/api-evaluate-result.data',Buffer.from(evaluated.resultBytes));
  apiRow.evaluate=compare(Buffer.from(evaluated.resultBytes));assert.ok(apiRow.evaluateMs<10000);
  apiRow.currentOperation='verify';apiStarted=performance.now();
  const verified=await api.verifyReadiness({...input,resultBytes:Buffer.from(evaluated.resultBytes),decisionBytes:null});apiRow.verifyMs=performance.now()-apiStarted;
  apiRow.verifyBytes=put('semantics/'+step+'-'+name+'/api-verify-result.data',Buffer.from(verified.resultBytes));
  apiRow.verify=compare(Buffer.from(verified.resultBytes));assert.ok(apiRow.verifyMs<10000);
  apiRow.result='PASS';apiRow.currentOperation=null;
 }catch(error){apiRow.failure=errorRecord(error);apiRow.failedOperationElapsedMs=performance.now()-apiStarted;throw error;}
 finally{write('semantics/'+step+'-'+name+'/api-parity.json',apiRow);rows.push(apiRow);}
 if(step==='A'||step==='O')assert.equal(result.assessment.qualifications.length,10);
 if(step==='O'){const primary=json(path.join(E,'steps/A.json'));assert.deepEqual(fs.readFileSync(path.join(primary.destination,'memoryos-readiness-result.json')),fs.readFileSync(path.join(destination,'memoryos-readiness-result.json')));}
}catch(error){failure=errorRecord(error);if(!fs.existsSync(path.join(E,'generation-stopped.json')))write('generation-stopped.json',{step,name,at:new Date().toISOString(),reason:'FIRST_MANDATORY_FAILURE',failure,noRetry:true,noLaterSteps:true});}
finally{
 let installedUnchanged=false,integrityError=null;
 try{assert.deepEqual(walk(packageRoot),before);installedUnchanged=true;}
 catch(error){integrityError=errorRecord(error);failure??=integrityError;if(!fs.existsSync(path.join(E,'generation-stopped.json')))write('generation-stopped.json',{step,name,at:new Date().toISOString(),reason:'INSTALLED_INTEGRITY_FAILURE',failure,noRetry:true,noLaterSteps:true});}
 const receipt={step,name,result:failure?'FAIL':'PASS',failure,integrityError,rows,destination,installedUnchanged,finishedAt:new Date().toISOString()};
 write('steps/'+step+'.json',receipt);console.log(JSON.stringify({step,name,result:receipt.result,failure,rows:rows.map(r=>({operation:r.operation??'api',exit:r.exit,result:r.result,elapsedMs:r.elapsedMs}))}));process.exitCode=failure?1:0;
}

